Azure/azure-functions-core-tools

- src/Azure.Functions.Cli/Actions/LocalActions/AddSettingAction.cs
added in verbiage to the add settings action letting the user know that the setting will be encrypted and the file will not be portable.
> Added verbiage to add action re encryption

- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
After adding the Azure Search .NET SDK to an existing function, I received the 'Inheritance security rules violated by type' error documented in issue [#11100](https://github.com/dotnet/corefx/issues/11100) in the corefx repo. Our project was using neither .NET 4.6.1 nor System.Net.Http 4.1.1, but I discovered the functions tooling shipped with and was loading version 4.1.1.0 of System.Net.Http. I checked the distributed func.exe.config and saw a binding redirect to 4.1.1.0, but saw a binding redirect to 4.0.0.0 in the app.config from the source. I built the project with detailed logging and saw the following in the logs:
```
There was a conflict between "System.Net.Http, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "System.Net.Http, Version=4.0.0.0, …
```
> disable auto generation of binding redirects

- src/Azure.Functions.Cli/Actions/AzureActions/BaseAzureAccountAction.cs
- src/Azure.Functions.Cli/Actions/AzureActions/BaseAzureAction.cs
- src/Azure.Functions.Cli/Actions/AzureActions/LoginAction.cs
- src/Azure.Functions.Cli/Arm/ArmManager.cs
- src/Azure.Functions.Cli/Arm/IArmManager.cs
- test/Azure.Functions.Cli.Tests/ActionsTests/LoginActionTests.cs
- test/Azure.Functions.Cli.Tests/Azure.Functions.Cli.Tests.csproj
- test/Azure.Functions.Cli.Tests/packages.config
Closes #160 
If you guys are cool with this, let me know and I'll get some tests written.
> allow for explicit login credentials

- test/Azure.Functions.Cli.Tests/ActionsTests/ResolveActionTests.cs
I found tests that were failing because of removing func functionapp context from InitAction #143.
> Removed 2 failing tests that were not needed 

- test/Azure.Functions.Cli.Tests/ActionsTests/ResolveActionTests.cs
Host start test was failing because of dependency with host.json file that didn't exist. It wasn't needed to keep that dependency during that test. Mocking ISecretsManager allows to avoid an exception caused by that dependency.
> Repaired host start test

- src/Azure.Functions.Cli/npm/lib/install.js
- src/Azure.Functions.Cli/npm/package-lock.json
- src/Azure.Functions.Cli/npm/package.json
If a .targets file is in the worker directory, we'll execute the logic on install.
This enables consistent install logic between VS project & cli.
Example worker target which installs the correct grpc native module for platform: https://github.com/Azure/azure-functions-nodejs-worker/blob/dev/Microsoft.Azure.Functions.NodeJsWorker.targets
> Enable worker targets on osx/linux

- src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
Could determine debug ports if specified in `--workers` for launch.json, but I think that's out of scope for now, created https://github.com/Azure/azure-functions-cli/issues/258 to track
> Reenable launch.json creation

- src/Azure.Functions.Cli/npm/package.json
Causes issues when installing `@core` if the restriction is not met - instead of seeing an error, one of the 1.0.0 versions is installed.
> Remove node engine restriction

- src/Azure.Functions.Cli/Actions/LocalActions/AddExtensionAction.cs
- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
- src/Azure.Functions.Cli/ConsoleApp.cs
- src/Azure.Functions.Cli/Context.cs
- src/Azure.Functions.Cli/ExtensionsProj.txt
resolves #265 
@fabiocav @ahmelsayed 
`func extensions add --package Microsoft.Azure.WebJobs.Extensions.EventHubs --version 3.0.0-beta3 --output ./bin`
creates `functions-extensions/extensions.csproj` with metadata generator included, adds event hubs nuget, runs a build on `extensions.csproj` to `--output` dir
> Add extensions command

- src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
- src/Azure.Functions.Cli/packages.config
- test/Azure.Functions.Cli.Tests/Azure.Functions.Cli.Tests.csproj
- test/Azure.Functions.Cli.Tests/packages.config
Update to latest runtime version of WebJobs.Script which includes the proxy dlls for running locally
> Update to latest runtime version of WebJobs.Script

- src/Azure.Functions.Cli/Actions/LocalActions/CreateFunctionAction.cs
- src/Azure.Functions.Cli/Common/Template.cs
Implements #298
- Displays " (Experimental)" next to each template which is assigned to category experimental
- Displays " (Experimental)" next to each language for which all templates are experimental
The change is for 1.x branch, since 2.0 branches don't have experimental templates at all.
Note that PHP and TypeScript are not classified as experimental at the moment due to https://github.com/Azure/azure-webjobs-sdk-templates/issues/619. If/when that fix is merged, these languages will be shown as experimental with no further change required in CLI.
> Mark experimental languages and templates in `func new` dialog

- CONTRIBUTING.md
Start a contributing file for the 2.0 runtime as part of https://github.com/Azure/azure-functions-cli/issues/360 . Build instructions from what I’ve pieced together and contributing instructions adapted from the webjobs sdk repo
For the love of everything can we do something about the tests totally failing? Even if it means removing them for now?
Also includes writing up stuff found in that I could confirm on my macbook
- https://github.com/Azure/azure-functions-cli/issues/217
- https://github.com/Azure/azure-functions-cli/issues/283
> Make a start on a contributing file for the v2 runtime

- src/Azure.Functions.Cli/Common/Constants.cs
- src/Azure.Functions.Cli/Helpers/DebuggerHelper.cs
As per issue #361 I added support for debugging .NET Core Functions in the `launch.json` file for VS Code. This makes the experience a lot better and works out of the box! Only available against the v2 (core) branch as traditional v1 C# functions can't work or be debugged in VS code.
> Added support for .net core debug in launch.json #361

- README.md
@ahmelsayed Is there any reason not to delete the windows-only note?
> remove windows-only note from readme

- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
Support change to load dependencies from /lib in functionapp root corresponding to @christopheranderson azure-functions-host PR [#2459](https://github.com/Azure/azure-functions-host/pull/2459)
\+ @christopheranderson @ahmelsayed @fabiocav
> Core Tools - Update Java Worker to Java1.1.0-beta2-10014

- src/Azure.Functions.Cli/npm/lib/install.js
Octal notation required, otherwise results in bad permissions, no error is thrown -- https://nodejs.org/api/fs.html#fs_file_modes
> Fix chmod in post install logic

- src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs
It looks like our .gitignore files are not project specific (i.e. C# vs JavaScript), but we can add `node_modules` to the generated .gitignore to make sure that it's there no matter what.
> Add node_modules to .gitignore

- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
- src/Azure.Functions.Cli/Common/SelfHostWebHostSettingsFactory.cs
- src/Azure.Functions.Cli/Diagnostics/CliLoggerFactoryBuilder.cs
- src/Azure.Functions.Cli/Diagnostics/ColoredConsoleLogger.cs
- src/Azure.Functions.Cli/Diagnostics/ColoredConsoleLoggerProvider.cs
- src/Azure.Functions.Cli/Diagnostics/ConsoleTraceWriter.cs
Fixes #130.
Had to handle some special cases as simply adding a ConsoleLoggerProvider wouldn't work:
1. Since we set `Console.Out` to null, no console output could come from elsewhere.
2. The standard console logger doesn't look anything like our existing logging, so I wanted to use ConsoleTraceWriter internally so everything looked nice.
3. TraceWriter traces are forwarded to ILoggers to make App Insights work as expected, but this can cause duplicate logs. Making sure this doesn't happen.
4. We log to both TraceWriter and ILogger everywhere in the host, so I've restricted this output to be strictly for function logs.
> adding console output for ILogger

- test/Azure.Functions.Cli.Tests/ActionsTests/ResolveActionTests.cs
https://github.com/Azure/azure-functions-core-tools/pull/440
I don't think `--version` falls into the category of helpAction, since it doesn't really provide documentation on how to use `func`, and its a little short to create new action, so I am leaving it like this
> fix test for --version

- src/Azure.Functions.Cli/Arm/ArmClient.cs
- src/Azure.Functions.Cli/Arm/ArmManager.cs
- src/Azure.Functions.Cli/Arm/ArmTokenManager.cs
this is a bandage fix, will take time to refactor before merge
1. when making arm request for the first time, there's no persistent setting, hence tenant id will be empty, so constructing `authenticationcontext` will error out with `'authority' Uri should have at least one segment in the path (i.e. https://<host>/<path>/...) Parameter name: authority`
2. in these scenarios we will perform user login to try get tenantid, however there's a small bug where we retry with the cached tenantid instead of the one acquired from login:
https://github.com/Azure/azure-functions-core-tools/blob/4d8cc0a639b1ecac6bcd14b149bc1d582430c1a7/src/Azure.Functions.Cli/Arm/ArmTokenManager.cs#L46-L59
3. hence 4 repetitive retries are performed and only when you rerun the command (now the tenantid is presented in …
> update tenantid after login, #408

- src/Azure.Functions.Cli/Helpers/LanguageWorkerHelper.cs
PR https://github.com/Azure/azure-functions-host/pull/3047 moves JavaWorker to use generic worker provider.
> Update Java worker config

- src/Azure.Functions.Cli/Common/Constants.cs
Looks like commit https://github.com/Azure/azure-functions-core-tools/commit/4c6db1c00884b0c5aae9d24adb01292f01e1fec8 missed updating the CLI version number.. @soninaren FYI
> Update CLI Version tag (for runtime 1.0.11913)

- README.md
- src/Azure.Functions.Cli/Actions/LogsActions/GetLogsAction.cs
- src/Azure.Functions.Cli/Helpers/KubernetesHelper.cs
Allows for func logs --name <function-name> --platform <platform> to get the logs of functions running on custom backends such as Kubernetes
> added func logs functionality

- tools/python/packapp.py
There is a version mismatch between the sdist filename and the actual
package version which confused packapp.
Fixes: https://github.com/Azure/azure-functions-python-worker/issues/175
> packapp: Fix NLTK installation

- src/Azure.Functions.Cli/Actions/LocalActions/CreateFunctionAction.cs
- src/Azure.Functions.Cli/Helpers/WorkerRuntimeLanguageHelper.cs
- test/Azure.Functions.Cli.Tests/E2E/CreateFunctionTests.cs
Created a mapping for getting the template names from the worker, for now, assuming each worker supports only one language for the template. Let me know if I should change the implementation to not rely on the worker runtime. Thanks!
> Fixes #481 - Support language alias when creating templates

- src/Azure.Functions.Cli/Common/Constants.cs
- src/Azure.Functions.Cli/Helpers/ExtensionsHelper.cs
- src/Azure.Functions.Cli/StaticResources/ExtensionsProj.csproj.template
Updating CLI to use latest metadata generator package for `func extension install` command and default extension csproj
> Updating extension command and csproj template to install latest metadata generator package

- src/Azure.Functions.Cli/Actions/LocalActions/CreateFunctionAction.cs
- src/Azure.Functions.Cli/Common/Utilities.cs
- test/Azure.Functions.Cli.Tests/E2E/CreateFunctionTests.cs
Any template names should work across all languages (Http Trigger, httptrigger, etc).
> Fixes #650 - Ensure template names to be consistent

- build.fsx
- src/Azure.Functions.Cli/Helpers/PythonHelpers.cs
I made the change to move distlib install to build script. I noticed that some files are involved in the zip signing. Please let me know if that's something the downloaded library will have to contribute to.
> Potential fix #718 - move distlib install to buildtime

- src/Azure.Functions.Cli/Arm/Models/ArmArrayWrapper.cs
- src/Azure.Functions.Cli/Helpers/AzureHelper.cs
I made the change to go to retrieve all the functionapps.
I didn't add the suggested `resource-group` flag yet. I was unable to make a successful request to the ARM with a resource group that would give me my functionapp using the link suggested in the issue. It there's a specific format of the link and if we want this flag, please let me know, I will update the PR.
> Fixes #738 - show functionapp if it's in the next page

- README.md
This adds generic installation instructions that should work on most Linux distributions. They were specifically tested to work against Fedora 27.
> Add installation instructions for other Linux distros

- src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
- src/Azure.Functions.Cli/Diagnostics/DisableConsoleConfigurationBuilder.cs
Fixes #776. 
The ConsoleLogger was being registered at both the WebHost and ScriptHost levels so we'd get unnecessary messages showing up without the formatting of the ColoredConsoleLogger.
> improving console output

- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
- src/Azure.Functions.Cli/Common/Constants.cs
- src/Azure.Functions.Cli/Helpers/PythonHelpers.cs
- src/Azure.Functions.Cli/StaticResources/StaticResources.cs
- src/Azure.Functions.Cli/StaticResources/python_bundle_script.py.template
- src/Azure.Functions.Cli/StaticResources/python_docker_build.sh.template
**Note: Please do not merge yet, still working on testing different scenarios.**
Add ability to bundle the python worker with the modules from `requirements.txt` using pyinstaller.
In addition, please review- https://github.com/Azure/azure-functions-docker/pull/34
Additional work to be done (in case we take this path):
1) Make sure venv is not included in the zip created by pack
2) Make `--build-native-deps` the default, as we will need to take the docker path if we use pyinstaller.
> Add ability to bundle python modules with worker

- src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
Hi,
While working with Azure Functions CLI and localhost, I often find it difficult to immediately know, how a function triggered via HTTP request should be called(which HTTP method should I use). This PR proposes a simple solution by prepending e.g. [POST, GET] to the displayed function URL when a host runs.
Regards,
Kamil
> Displaying HTTP methods for functions triggered with [HttpTrigger]

- src/Azure.Functions.Cli/Common/Constants.cs
Token extension should depend on AuthTokens nuget, not MicrosoftGraph nuget.
> Bug: Token extension installs wrong nuget

- src/Azure.Functions.Cli/Diagnostics/ColoredConsoleLogger.cs
We were ignoring exceptions in the console unless they were logged with `LogLevel.Error`. Did a quick test with this code:
```
[FunctionName("LogSomething")]
public static async Task<IActionResult> Run(
[HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequest req,
ILogger log)
{
try
{
throw new InvalidOperationException("Boom!");
}
catch (Exception ex)
{
log.Log(LogLevel.Information, ex, "Something happened. But it's okay.");
}
return new OkObjectResult($"Hello");
}
```
Before:
After:
> logging exception for all LogLevels

- src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
- src/Azure.Functions.Cli/Arm/Models/ArmWebsiteConfig.cs
- src/Azure.Functions.Cli/Arm/Models/Site.cs
- src/Azure.Functions.Cli/Common/Constants.cs
- src/Azure.Functions.Cli/Helpers/AzureHelper.cs
The check will only fail if they have a linuxFxVersion set to something in the portal. Let me know, if I should also fail if they don't have a version configured on linux dedicated.
> Fixes #762 - Add verification for linuxFxVersion while publishing

- src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
- src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
- src/Azure.Functions.Cli/Helpers/DotnetHelpers.cs
One additional thing to note is:
Before this change, if you were to try and do `azure functionapp publish <name>` on a dotnet runtime project without a `.csproj`, it would error out complaining that it couldn't build as 0 `.csproj` was found. 
But, after this, it would still continue informing the user that the build step was skipped. I think it makes sense to keep it this way if someone wants to just publish their built project directly. I can't imagine a case where this would be a breaking change.
Let me know if you prefer me to keep the publishing the original way, I can update the PR.
> Fixes #553, #765 - dotnet build by default

- src/Azure.Functions.Cli/StaticResources/python_docker_build.sh.template
There was some race condition causing issues when trying to delete the venv occasionally. So, instead of deleting it, I made a change to exclude it from the zip file when necessary.
Additionally instead of using `source <venv>/bin/activate` and `deactivate`, it's better to use the `<venv>/bin/pip` and `venv/bin/python`.
> Fix issue with bundling python in venv

- src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
- src/Azure.Functions.Cli/Common/SimpleProgressBar.cs
- src/Azure.Functions.Cli/Common/Utilities.cs
- src/Azure.Functions.Cli/Helpers/ZipHelper.cs
Closes #696 
Closes #513
Closes #681
I still have to test it on a linux console though 
it should work for both /zipdeploy and uploading to storage.
> Display size and progress bar for uploads file uploads.

- src/Azure.Functions.Cli/StaticResources/python_bundle_script.py.template
Fixed pyinstaller ignoring submodules.
Also, removed ignoring `__pycache__` as it may help up speed certain executions.
> Fixes #882 - Pyinstaller ignoring certain submodules while bundling

- src/Azure.Functions.Cli/Actions/LocalActions/CreateFunctionAction.cs
- src/Azure.Functions.Cli/Helpers/ExtensionsHelper.cs
I am not doing the check for when worker-runtime is dotnet. Currently, it should fail as expected because cli runs the `dotnet` command.
> Fixes #876 - Ensure dotnet for functions with extensions

- src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs
- src/Azure.Functions.Cli/Helpers/WorkerRuntimeLanguageHelper.cs
Adding `(preview)` while displaying the selection wizard on `func init` without affecting the parameter `--worker-runtime`. `func init --worker-runtime python` should still be valid.
> Fixes #887 - Add preview flag to python

- src/Azure.Functions.Cli/StaticResources/python_bundle_script.py.template
This is a minor fix to change the way we pass hidden-imports to pyinstaller for bundling.
`os.path.splitext("test_approximate.cpython-36.so")`  returns `['test_approximate.cpython-36', 'so']`
while,
`"test_approximate.cpython-36.so".split(os.extsep)` returns `['test_approximate','cpython-36','so']`
We need the latter because `import test_approximate` is the valid syntax while `import test_approximate.cpython-36` is not.
> Minor fix in file extensions python

- src/Azure.Functions.Cli/Actions/DurableActions/DurableGetInstances.cs
- src/Azure.Functions.Cli/Actions/DurableActions/DurablePurgeHistory.cs
- src/Azure.Functions.Cli/Common/DurableManager.cs
- test/Azure.Functions.Cli.Tests/E2E/DurableTests.cs
Fixes #944 
I considered forcing the output in the purge command to use the invariant culture so that the test could retain non-computed values for the assertion, but there seems to be a precedent for locale-based date output in [ColoredConsoleLogger](https://github.com/Azure/azure-functions-core-tools/blob/cd919dc1f4e993a631a9fdc43bd0946660a4ca86/src/Azure.Functions.Cli/Diagnostics/ColoredConsoleLogger.cs#L47)
> Allow for regional date formats in Durable Test

- src/Azure.Functions.Cli/npm/npm-shrinkwrap.json
- src/Azure.Functions.Cli/npm/package.json
We need to make sure to update `npm-shrinkwrap.json` `"version"` variable.
`npm version` should take care of that.
-Tested on Windows and Mac.
-`unzipper@0.9.6` had the problem, it seems fixed in `unzipeer@0.9.7`.
> Fixes #939 - Add a shrinkwrap and lock dependencies

- README.md
- src/Azure.Functions.Cli/Actions/DeployActions/DeployFunctionAction.cs
- src/Azure.Functions.Cli/Actions/DeployActions/Platforms/KnativePlatform.cs
- src/Azure.Functions.Cli/Actions/DeployActions/Platforms/Models/FunctionJson.cs
- src/Azure.Functions.Cli/Actions/DeployActions/Platforms/Models/KnativeService.cs
- src/Azure.Functions.Cli/Actions/DeployActions/Platforms/PlatformFactory.cs
This PR adds knative as a target platform to the 'func deploy' command.
Non-HTTP trigger workloads are supported - the minScale annotation is added to non-HTTP trigger functions in order to avoid scale-to-zero.
> Added knative support

- src/Azure.Functions.Cli/Common/DurableManager.cs
The Durable Functions documentation for [host.json](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-bindings#host-json) indicates that `HubName` should be capitalized. As seen in [this issue](https://github.com/Azure/azure-functions-durable-extension/issues/448#issuecomment-454887043), Visual Studio indicates it should be `hubName`. This PR allows for either capitalization.
> Case insensitive hub name from host.json

- src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs
- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
- src/Azure.Functions.Cli/StaticResources/StaticResources.cs
- src/Azure.Functions.Cli/StaticResources/profile.ps1.template
- test/Azure.Functions.Cli.Tests/E2E/InitTests.cs
When a PowerShell Function App is created, it will also be created with a profile.ps1 which is a script that will be executed at "cold start".
Initially, this profile.ps1 will automatically authenticate you to Azure if you have the Az.Accounts module available and also have setup MSI. The profile also has an example on how to enable the old AzureRm alias.
I didn't see any tests for the InitAction but if they are hiding somewhere, please let me know and I will gladly add tests.
cc @daxian-dbw @SteveL-MSFT @joeyaiello @anirudhgarg @paulbatum @ahmelsayed @pragnagopa
> add profile.ps1 creation for PowerShell Function Apps

- src/Azure.Functions.Cli/Actions/AzureActions/BaseAzureAction.cs
In the official 1.0 release of `Az` they renamed `Az.Profile` to `Az.Accounts`. This change reflects that.
I _think_ since `Az` wasn't at 1.0 we don't have to be backward compatible here - I updated the error text to specify the Az.Accounts module that needs to be installed. If you think I should be backwards compatible with Az.Profile, let me know and I can update this PR.
AzureRm will still work... but no new features are going into it so I'm not calling it out in the error text.
thoughts on this design? @joeyaiello @stevel-msft @anirudhgarg @Francisco-Gamino
> Update to Az.Accounts

- src/Azure.Functions.Cli/Common/Utilities.cs
- test/Azure.Functions.Cli.Tests/E2E/CreateFunctionTests.cs
I didn't find any other rules for namespaces that I should look out for. If you are aware of any additional ones, let me know and I will update
> Add rules to sanitize namespace literal

- src/Azure.Functions.Cli/Common/Constants.cs
- src/Azure.Functions.Cli/Helpers/PythonHelpers.cs
This will help us a ton when creating end to end tests for packaging using the development version of Docker images.
> Add ability to override the docker image used to package

- src/Azure.Functions.Cli/Actions/AzureActions/ListFunctionsActions.cs
- src/Azure.Functions.Cli/Helpers/AzureHelper.cs
- This also mean if a user does `func azure functionapp list-functions --show-keys`, we won't show keys if their functions are anonymous, which make sense because there's really no keys to show.
> Fixes #889 - Do not show query param if anonymous

- src/Azure.Functions.Cli/Common/Constants.cs
`microsoft/azure-functions-dotnet2.0` is not a valid image. The correct image is `microsoft/azure-functions-dotnet-core2.0`
> Fix image version

- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
Update powershell worker to 0.1.69-preview
this handles all gRPC messages and moves to PowerShell SDK 6.2.0-rc.1 which includes needed feature for F5 debugging experience
> Update PowerShell to 0.1.69-preview

- src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
Updated logic:
````
if (Consumption Linux):
publish run from package = sas
else if (Dedicated Linux OR "--no-zip"): 
publish zip deploy
else:
publish run from package = 1 and zip deploy
````
Resolves https://github.com/Azure/azure-functions-core-tools/issues/1086
> Update publish function app to do run from package = 1

- README.md
- src/Azure.Functions.Cli/Actions/DeployActions/DeployFunctionAction.cs
- src/Azure.Functions.Cli/Actions/DeployActions/Platforms/KnativePlatform.cs
- src/Azure.Functions.Cli/Actions/DeployActions/Platforms/KubernetesPlatform.cs
- src/Azure.Functions.Cli/Actions/DeployActions/Platforms/Models/Kubernetes.cs
- src/Azure.Functions.Cli/Interfaces/IHostingPlatform.cs
This PR enables the following use cases for deploying to Kubernetes:
* using a private docker registry by specifying a pull secret
* deploying to a namespace of choice,  (default today is  ```azure-functions```)
Minor semantic fixes along the way.
Knative implementation should follow shortly.
> Enable Kubernetes deployment using a private registry, namespace support 

- src/Azure.Functions.Cli/Helpers/PythonHelpers.cs
- src/Azure.Functions.Cli/StaticResources/python_docker_build.sh
Will run my e2e tests and update with results.
After this change, we can make it very clear to users about our deployment path. They can see `.python_packages` that will be created with or without `--build-native-deps`. In case if they don't want to restore custom dependencies in subsequent publish commands, they will now be able to just do `publish --no-build` and it will work.
@asavaritayal, once merged, we should update our docs as well.
> Fixes #1015 - Consistent way to provide user dependencies

- src/Azure.Functions.Cli/Common/Constants.cs
Technically, this change wouldn't be needed unless with update python-worker version. But probably a good idea to keep things updated.
> Update docker version

- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
* Revved version of PowerShell SDK to 6.2.0
* Made binding info dictionary case-insensitive to support case-insensitive binding names
* Updated logic to clean up jobs started during the function execution
* System logging improvements to reflect the correct worker pool size when the environment variable is not set
For more information, please see https://github.com/Azure/azure-functions-powershell-worker/releases/tag/0.1.90
> Update PowerShell worker to 0.1.90-preview.

- src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
- src/Azure.Functions.Cli/Common/Constants.cs
- test/Azure.Functions.Cli.Tests/ActionsTests/StartHostActionTests.cs
Note that, even after this change, kafka dotnet functions will still see the warning `Missing value for AzureWebJobsStorage in local.settings.json. This is required for all triggers other than HTTP.` because of https://github.com/Azure/azure-functions-vs-build-sdk/blob/87d3faf121b1b443f6288b4b1d54c5b72f22ee39/src/Microsoft.NET.Sdk.Functions.Generator/FunctionJsonConverter.cs#L206.
@jeffhollan, fyi.
I will make a PR to that repo as well and post an update here.
Update:
https://github.com/Azure/azure-functions-vs-build-sdk/pull/303
> Fixes #1133 - AzureWebJobsStorage is not required for kafka trigger

- src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs
- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
- src/Azure.Functions.Cli/Helpers/PowerShellHelper.cs
- src/Azure.Functions.Cli/Helpers/SelectionMenuHelper.cs
- src/Azure.Functions.Cli/Helpers/WorkerRuntimeLanguageHelper.cs
- src/Azure.Functions.Cli/StaticResources/StaticResources.cs
- src/Azure.Functions.Cli/StaticResources/gitignore
- src/Azure.Functions.Cli/StaticResources/powershell.host.json
- src/Azure.Functions.Cli/StaticResources/requirements.psd1
- test/Azure.Functions.Cli.Tests/E2E/InitTests.cs
This PR contains the following changes:
*  Adding support in func init to enable managed dependencies for PowerShell.
* Unit test for 'init --worker-runtime powershell --managed-dependencies'
* Adding PowerShell (preview) to drop down list of available runtime workers.
**Installation flow**
At function app creation, the user has the option to opt into Managed Dependencies for PowerShell function apps using the --managed-dependencies switch. Managed dependencies enables modules to be automatically managed by the Functions service. Currently, only the Azure Az module is supported. 
If the user opts in, we add an entry to host.json and create a requirements.psd1.
Scenario 1: User opts into managed dependencies for PowerShell
```
init --worker-runtime powershell --managed-dependencies
Writing …
```
> Enable managed dependencies for PowerShell function apps.

- build/BuildSteps.cs
- build/Program.cs
- build/Settings.cs
**Before:**
```
206M    Azure.Functions.Cli.linux-x64.2.4.9999.zip
56M     Azure.Functions.Cli.min.win-x64.2.4.9999.zip
53M     Azure.Functions.Cli.min.win-x86.2.4.9999.zip
186M    Azure.Functions.Cli.no-runtime.2.4.9999.zip
170M    Azure.Functions.Cli.osx-x64.2.4.9999.zip
170M    Azure.Functions.Cli.win-x64.2.4.9999.zip
168M    Azure.Functions.Cli.win-x86.2.4.9999.zip
```
**After:**
```
156M    Azure.Functions.Cli.linux-x64.2.4.9999.zip
56M     Azure.Functions.Cli.min.win-x64.2.4.9999.zip
53M     Azure.Functions.Cli.min.win-x86.2.4.9999.zip
186M    Azure.Functions.Cli.no-runtime.2.4.9999.zip
119M    Azure.Functions.Cli.osx-x64.2.4.9999.zip
120M    Azure.Functions.Cli.win-x64.2.4.9999.zip
116M    Azure.Functions.Cli.win-x86.2.4.9999.zip
```
I kept all the platform runtimes in …
> Fixes #1141 : Remove extra platform runtimes powershell

- src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs
- src/Azure.Functions.Cli/Helpers/SelectionMenuHelper.cs
Enabling Managed Dependencies (MDs) by default for PowerShell function apps.
Scenario 1: User creates a PowerShell function app and enables MDs using the --managed-dependencies switch. 
```
PS E:\MyFunctions\MyFuncApp> E:\CLI\func.exe init --worker-runtime powershell  --managed-dependencies
Writing profile.ps1
Writing requirements.psd1
Writing .gitignore
Writing host.json
Writing local.settings.json
Writing E:\MyFunctions\MyFuncApp\.vscode\extensions.json
PS E:\MyFunctions\MyFuncApp> gc .\host.json
{
"version": "2.0",
"managedDependency": {
"enabled": true
}
}
PS E:\MyFunctions\MyFuncApp> gc .\requirements.psd1
#
@{
'Az' = '1.*'
}
PS E:\MyFunctions\MyFuncApp>
```
Scenario 2: User creates a PowerShell function app. By default MDs is enabled. This generates the same output as scenario 1. …
> Enabling managed dependencies by default for PowerShell function apps.

- src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
- src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
- src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs
- src/Azure.Functions.Cli/Actions/LocalActions/InstallExtensionAction.cs
- src/Azure.Functions.Cli/Actions/LocalActions/PackAction.cs
- src/Azure.Functions.Cli/Actions/LocalActions/SyncExtensionsAction.cs
- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
- src/Azure.Functions.Cli/Common/TemplatesManager.cs
- src/Azure.Functions.Cli/ConsoleApp.cs
- src/Azure.Functions.Cli/ExtensionBundle/ExtensionBundleConfigurationBuilder.cs
- src/Azure.Functions.Cli/ExtensionBundle/ExtensionBundleHelper.cs
- src/Azure.Functions.Cli/StaticResources/StaticResources.cs
- src/Azure.Functions.Cli/StaticResources/bundleConfig.json
`func host start` will load extensions from extension bundle if it is configured in host.json
closes #1105 
`func init . --extension-bundle` will add default extension bundling config to host.json
closes #1106 
`func extensions install` will be a no-op with a warning if extension bundle is configured in host.json
closes #1109 
`func new` will load the templates from extension bundle if it is configured in host.json
closes #1108
> Updating, "func extensions install", "func new", "func init ." and "func host start" actions

- src/Azure.Functions.Cli/Common/CommandChecker.cs
https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.start?view=netframework-4.8#System_Diagnostics_Process_Start_System_Diagnostics_ProcessStartInfo_ 
Process.Start(processStartInfo) will return a new Process that is associated with the process resource, or null if no process resource is started.
> Add null propagation for the process

- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
The feature for this release is to support the dependency download to happen on a background thread spawned by the FunctionLoad request and if the dependency download is still in progress and the function execution is invoked from the azure portal then the user will get the message on the azure portal log window that the dependency download is in progress and the function execution will continue when the download is done.
Release link:
https://github.com/Azure/azure-functions-powershell-worker/releases/tag/v0.1.97-preview
> Updating PowerShellWorker to version "0.1.97-preview"

- src/Azure.Functions.Cli/Actions/DeployActions/Platforms/KnativePlatform.cs
Related to: #866 
A Loadbalancer can actually have an IP or a Hostname (or both I think). Both should be fair game for the purposes of printing them out here.
Also added a bit more lenient error handling so the whole command doesn't fail if this cannot be determined by the CLI.
> Allow Knative service to be backed by a hostname and don't fail eagerly.

- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
In 0.1.97-preview, local debugging (both in VSCode and console debugging) stopped working entirely.
We've root caused the issue, but we don't have a fix yet. This rolls back the PowerShell Worker for now to get us back in a good state.
Since PowerShell support in Azure FUnctions is in Public Preview starting today.... and PowerShell Summit NA started today (and the Keynote included a PowerShell in Azure Functions demo) this should be hotfixed as soon as possible.
NOTE: only a Core Tools release is needed. The host is fine with the change that caused the regression.
cc @anirudhgarg @daxian-dbw @joeyaiello @eamonoreilly @SatishRanjan
> HOTFIX: Rollback PowerShell Worker

- src/Azure.Functions.Cli/Actions/LocalActions/CreateFunctionAction.cs
On an empty directory, `_templatesManager` seems to create a `host.json` when there isn't one. This causes `WorkerRuntimeLanguageHelper.GetCurrentWorkerRuntimeLanguage` to believe that there is a function app in the current directory. This messes up our logic for function app creation.
Running the template manager after trying to get the worker runtime fixes this scenario, as now `GetCurrentWorkerRuntimeLanguage` can throw an error when `host.json` is not present.
> Fix func new creating host.json

- src/Azure.Functions.Cli/StaticResources/gitignore
Removing ManagedDependencies folder from gitignore since the app dependencies will not be installed under the function app root.
> Removing ManagedDependencies folder from gitignore since the app dependencies will not be installed under the function app root.

- build/Settings.cs
It looks like Powershell launches `dotnet` process which then will load the right `runtime`. The bitness of `dotnet` will depend on what the user has installed, not the bitness of `func`. So we need to include both bitness runtimes in the both cli packages for Windows.
> Add all powershell runtimes for windows

- src/Azure.Functions.Cli/Common/Constants.cs
- src/Azure.Functions.Cli/Helpers/DockerHelpers.cs
- src/Azure.Functions.Cli/Helpers/PythonHelpers.cs
NEED TO TEST THIS. (Will do once build completes)
Now we will have 3 configurable choices:
1. If you want CLI to pull and build on a different image, use `FUNCTIONS_PYTHON_DOCKER_IMAGE`
2. If you want CLI to avoid pulling in case you are using 1 for a local image, set `FUNCTIONS_PYTHON_DOCKER_SKIP_PULL` to `true` or `1`.
3. If you want to customize the run command, pass any envs or other flags, use `FUNCTIONS_PYTHON_DOCKER_RUN_COMMAND` + `FUNCTIONS_PYTHON_DOCKER_SKIP_PULL` (ideally).
@ahmelsayed, would you recommend making `FUNCTIONS_PYTHON_DOCKER_SKIP_PULL` to be assumed when setting `FUNCTIONS_PYTHON_DOCKER_RUN_COMMAND`?
> Fixes #1230 - add options to override Docker run

- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
- test/Azure.Functions.Cli.Tests/Azure.Functions.Cli.Tests.csproj
The major changes for this release are:
* Fix regression that made local debugging stop working. This was because a runspace was not created at startup.
* Rev gRPC library versions
* Fix regression where Rpc.RawBody was getting passed in as a hashtable instead of a string
> rev powershell worker to 0.1.102-preview

- src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
If we only call this when function app is linux, we don't need to have this code branch.
Test pending.
> Remove synctriggers path that is never hit

- src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
Related to https://github.com/Azure/azure-functions-core-tools/issues/1258
> Fix warning message for empty/null strings in local.settings.json and environment variables with existing values.

- src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
This will write out errors if someone is overriding (or adding additional) services that we require. For now, it's just an error message in the CLI but doesn't break anything.
> re-adding DependencyValidator

- src/Azure.Functions.Cli/Helpers/DockerHelpers.cs
- src/Azure.Functions.Cli/Helpers/PythonHelpers.cs
Fixes #1372 
Made `packapp` to always run on `--verbose`. I think this helps with the actual error and showing the actual download progress is clearer too.
Docker was initially logging permission error for all `docker ps` failures.
> Add error messages to Python failures

- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
The major changes for this release are:
* Proxies fix
* Updated proto files used by PowerShell worker
* Set response Content-Type to 'application/json' when an object is provided to Body
* Managed Dependencies (MDs) enhancements:
-    Added retry logic for module installation with a maximum of 3 retries
-    If unable to reach the PSGallery during installation:
* If this is the first time we are installing MDs, we error out and stop execution
* If there is a previous installation of MDs, log that we could not connect to the PSGallery and continue with the function app execution
* Enhancements to throughput performance
> Update PowerShell worker to v0.1.111-preview.

- src/Azure.Functions.Cli/Helpers/DotnetHelpers.cs
- src/Azure.Functions.Cli/Helpers/ExtensionsHelper.cs
This PR enables the compilation of F# function projects.
> Simply searches for the existence of *.fsproj files additionally to *.csproj files.
> The dotnet build system then builds the project before the function host starts.
Previously:
```
[22.06.2019 07:21:30] Starting JobHost
[22.06.2019 07:21:30] Starting Host (HostId=desktopahhb6e1-383811222, InstanceId=bcf09484-1474-4e67-a381-25c295b34816, Version=2.0.12507.0, ProcessId=15216, AppDomainId=1, InDebugMode=False, InDiagnosticMode=False, FunctionsExtensionVersion=)
[22.06.2019 07:21:30] Loading functions metadata
[22.06.2019 07:21:30] 0 functions loaded
[22.06.2019 07:21:30] Generating 0 job function(s)
[22.06.2019 07:21:30] No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. …
```
> Enable compilation of F# projects.

- src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
- src/Azure.Functions.Cli/Actions/LocalActions/PackAction.cs
- src/Azure.Functions.Cli/Common/BuildOption.cs
- src/Azure.Functions.Cli/Common/Constants.cs
- src/Azure.Functions.Cli/Common/DeploymentStatus.cs
- src/Azure.Functions.Cli/Helpers/AzureHelper.cs
- src/Azure.Functions.Cli/Helpers/KuduLiteDeploymentHelpers.cs
- src/Azure.Functions.Cli/Helpers/PublishHelper.cs
- src/Azure.Functions.Cli/Helpers/PythonHelpers.cs
- src/Azure.Functions.Cli/Helpers/ZipHelper.cs
https://github.com/Azure/azure-functions-host/pull/4585
Allow user to use --server-side-build flag in core tools and enable 
The expected behaviors:
1. User use `func azure functionapp publish <function site name> --server-side-build` to trigger a new build.
2. The core tools will initiate a web request to `https://management.azure.com/subscriptions/<subscription>/resourceGroups/<resource group>/providers/Microsoft.Web/sites/<function site name>/hostruntime/**admin/getsitetoken**` to get an **x-ms-site-restricted-token**. This **x-ms-site-restricted-token** will be used as authentication token in scmsite endpoints.
3. Core tools packs the files in user's local source directory into a zip file.
4. Core tools upload the zip file to `scmsite/api/zipdeploy?isAsync=true`.
4. Core tools will …
> Add support for server side build

- src/Azure.Functions.Cli/Common/CommandChecker.cs
- Fix path to bash so the tools can be used on macOS without throwing "No such file or directory" error.
- Fixes #1403
> Update path to bash

- src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
Previously, we run into an issue where the list function has the old content before the server side build.
To address this issue, after each server side build succeeds, we should perform a sync trigger before listing the functions information.
> Perform sync trigger when server side build succeeds

- src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs
- src/Azure.Functions.Cli/Helpers/PowerShellHelper.cs
- src/Azure.Functions.Cli/StaticResources/requirements.psd1
For PowerShell function apps, we enable Managed Dependencies (MDs) at creation time via func init. During this process, we connect to the www.powershellgallery.com to retrieve the latest available module version for the Azure Az modules. 
After this code change, if the user does not have internet access during func init, we do the following:
1) Write a warning to the console:
2) Provide instructions in requirements.psd1 on what to do next:
```
Contents of requirements.psd1
#
@{
}
```
```func init``` for a PowerShell function app with internet connection continues to work the same. However, the comments in ```requirements.psd1``` file have been updated. Please see below:
```
PS D:\Functions\MyFuction3> E:\CLI\func init --worker-runtime powershell
Writing profile.ps1
Writing …
```
> Handle lack of internet connection when creating PowerShell function apps

- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
The major changes for this release are:
- Ignore function load requests with duplicate FunctionId values
Release details: https://github.com/Azure/azure-functions-powershell-worker/releases/tag/v0.1.120-preview
> Update PowerShellWorker version to 0.1.120-preview

- src/Azure.Functions.Cli/Actions/AzureActions/BaseAzureAction.cs
- src/Azure.Functions.Cli/Actions/AzureActions/BaseFunctionAppAction.cs
- src/Azure.Functions.Cli/Actions/AzureActions/FetchAppSettingsAction.cs
- src/Azure.Functions.Cli/Actions/AzureActions/ListFunctionsActions.cs
- src/Azure.Functions.Cli/Actions/AzureActions/LogStreamAction.cs
- src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
- src/Azure.Functions.Cli/Helpers/AzureHelper.cs
Closes #1381, #1423 
- Using ARG is a lot faster as we don't need to go through subscription(s) page by page to find a Function App. It also saves an `az` call.
- Slot support for all azure commands.
> Add slot support, and use ARG for function app

- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
**BEFORE MERGING THIS:** This is synchronizing the Node worker with the runtime version, but it causes a downgrade. We can combine this with an update to the host, but this change is important to make sure we don't get out of sync here.
> Removing explicit language worker dependencies

- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
- Major Managed Dependencies update:
- Allowed specifying any (not just `Az`) module from PowerShell Gallery in `requirements.psd1` (up to 10 entries).
- Allowed specifying exact module versions in `requirements.psd1` (as opposed to just `<MajorVersion>.*` 
pattern), including pre-release versions.
- More reliable implementation of module upgrades (fixing [#247](https://github.com/Azure/azure-functions-powershell-worker/issues/247), [#248](https://github.com/Azure/azure-functions-powershell-worker/issues/248), [#252](https://github.com/Azure/azure-functions-powershell-worker/issues/252), and other intermittent issues).
- Improved cold start performance.
- Added a warning when `managedDependencies` is enabled in `host.json` but no dependencies are specified in …
> Update PowerShellWorker to 0.1.152-preview

- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
- src/Azure.Functions.Cli/Extensions/ZipArchiveExtensions.cs
Fixes #1484 
@jeffhollan @alexkarcher-msft, once the build completes, I can give you artifacts to verify.
I did quick tests and this should work fine. 
@ahmelsayed, this should likely also solve issues with fuse mounting a zip package. I wanted to write tests for that. But, I would need a bit of additional work and don't want to block the P0 issue for it.
I tried a couple of different scenarios that this may have affected (building from unix deploying to Windows, vice-versa), but all looks file. Let me know if you can think of additional tests you would want me to perform.
> Inherit file permissions for a Linux package

- src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
- src/Azure.Functions.Cli/Common/FileSystemHelpers.cs
- src/Azure.Functions.Cli/Helpers/ZipHelper.cs
- src/Azure.Functions.Cli/StaticResources/funcignore
1. tsconfig.json must be included
2. currently, if the user want to use the extensions
- without extension bundling, it will still upload the extension binaries to remote build
- with extension bundling, it will only upload the source code and settings to remote build
1. dotnet server side build should not have "bin" or "obj" while oryx build will run "dotnet build"
2. expose "additionalIgnoredDirectories" in "GetLocalFiles" for ignoring additional directories when packaging the source folder.
> Support dotnet and node remote build

- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
We need to release core-tools before this Powershell Worker version is available in Azure. So, we have to revert this for now.
> Revert Powershell worker to match prod

- src/Azure.Functions.Cli/Common/Constants.cs
- src/Azure.Functions.Cli/Helpers/PythonHelpers.cs
Fixes Azure/azure-functions-python-worker#511
Fixes https://github.com/Azure/azure-functions-core-tools/issues/1194
An important extension of the work already done in https://github.com/Azure/azure-functions-python-worker/pull/506 and https://github.com/Azure/azure-functions-python-worker/pull/409. With the separation of the worker and the library, the users should now have control over the `azure-functions` library in their `requirements.txt`. This should be included in the startup experience so users publishing to Azure have the knowledge that they are in control of this dependency.
> Add azure-functions to requirements

- src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
If a function app is created before ANT83, the datarole does not contain SCM site.
Thus, core tools cannot find the scm/api/zipdeploy endpoints.
We should warn users from it.
> Add remote build warning message when SCM site is not available

- src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
We add a precise date for function apps that doesn't support remote build.
> Update remote build unavailable warning text change

- src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
With ANT83 completed, we can safely switch Linux Dedicated default publish to RunFromPackage.
Fixes #1069
> Change Linux Dedicated default publish to RunFromPackage

- src/Azure.Functions.Cli/Kubernetes/KubernetesHelpers.cs
- test/Azure.Functions.Cli.Tests/KubernetesHelperUnitTests.cs
Maps the string "rabbitmqtrigger" to "rabbitmq" for Kubernetes. Also populates "host" in metadata with the RabbitMQ connection string.
Details: https://github.com/Azure/azure-functions-rabbitmq-extension/issues/55
@pragnagopa @ahmelsayed @jeffhollan
> Added host and trigger name mapping for rabbitmq

- build/Settings.cs
I am still not 100% sure why `sigcheck.exe` test did not report this to us. When I ran it locally, the sign build failed as expected. Not sure why it went through in our pipeline.
I will look more into this later. But did not want to block on unsigned dlls.
> Add DotNetZip.dll in the list to be signed

- src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
- src/Azure.Functions.Cli/Helpers/KuduLiteDeploymentHelpers.cs
Since we finishes ANT84 deployment, we are now able to remove the site restricted token.
> Remote Build: remove site restricted token

- src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
- src/Azure.Functions.Cli/Common/BuildOption.cs
- src/Azure.Functions.Cli/Helpers/PublishHelper.cs
- src/Azure.Functions.Cli/Helpers/ZipHelper.cs
https://github.com/Azure/azure-functions-core-tools/issues/1556
1. Default Linux Consumption python app to remote build if requirements.txt has content.
1. The user can use **--build local** to opt-out from this default behavior.
2. Add recommendation to use "--build remote" when using "--build-native-deps" flag.
3. Hint old function app user to use "--build local" or "--build-native-deps" if their function app does not have SCM site.
> Remote Build: default python deployment method to remote build

- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
- The blob size limit for PowerShell functions triggered by blob is determined by the Functions host now, which effectively raised the limit from 4 MB to 120 MB (fixed issue https://github.com/Azure/azure-functions-powershell-worker/pull/346).
- Introduced TraceContext parameter (see issue https://github.com/Azure/azure-functions-host/issues/3747).
- Improved system log messages.
For more information, please see https://github.com/Azure/azure-functions-powershell-worker/releases/tag/v1.0.188.
> Update PowerShell worker to 1.0.188

- src/Azure.Functions.Cli/Helpers/ScriptHostHelpers.cs
In the latest host (which hasn't been absorbed here yet -- but I was trying to in the v3.x branch), `FunctionMetadataManager` has changed so this method broke. But it doesn't look like it's used anywhere so maybe we can just get rid of it?
> removing GetFunctionMetadata()

- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
- Resolved an issue that was sometimes making automatically installed modules intermittently unavailable until the first app reboot (issue https://github.com/Azure/azure-functions-powershell-worker/pull/351).
- Improved system log messages related to dependency management.
For more information, please see https://github.com/Azure/azure-functions-powershell-worker/releases/tag/v1.0.194.
> Update PowerShell worker to 1.0.194

- src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
- src/Azure.Functions.Cli/Helpers/PublishHelper.cs
- src/Azure.Functions.Cli/Helpers/PythonHelpers.cs
Previously, due to the change on remote build default, a validation of not consistent build options will always block the --build-native-deps.
This issue is addressed in this PR. Now --no-build and --build-native-deps will have higher precedence over --build flag
> Fix --build-native-deps validation

- src/Azure.Functions.Cli/StaticResources/Dockerfile.python36
The python 3.7 docker file base image already has the correct name.
Changing the python 3.6 docker file to **2.0-python3.6** and **2.0-python3.6-appservice**
> Change python docker init based image

- src/Azure.Functions.Cli/Helpers/PowerShellHelper.cs
The PowerShell gallery contains both prerelease and regular versions of the Az module. 
Updating logic in the ```PowerShellHelper.cs``` to skip prerelease versions.
> PowerShell function apps. Ignore prerelease versions of the Az module.

- src/Azure.Functions.Cli/Helpers/PythonHelpers.cs
- src/Azure.Functions.Cli/StaticResources/python_docker_build.sh
- test/Azure.Functions.Cli.Tests/E2E/InitTests.cs
- tools/python/packapp/__main__.py
- Change **python_docker_build.sh** to use the new python package path `/.python_packages/lib/site-packages`
- Change **packapp/__main__.py** to use the new python package path `/.python_packages/lib/site-packages`
- Change **PythonHelpers.cs** to automatically pick the right python-version
- The build remote will automatically choose the oryx build version, no code change is required
> Enable --build-native-deps and --build local for python 3.7

- build/Settings.cs
https://github.com/Azure/azure-functions-core-tools/issues/718
This bug is introduced by distlib when the 0.2.8 version is released to publish. At that time, we need to get a specific commit with the fix for our packapp tool.
The old commit `15dba58a827f56195b0fa0afe80a8925a92e8bf5` in distlib is removed. Hence, the AddDistLib build step is failing.
Upgrade the distlib version to 0.3.0
> Fix AddDistLib url for CI

- src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
- src/Azure.Functions.Cli/Common/Constants.cs
- src/Azure.Functions.Cli/Helpers/KuduLiteDeploymentHelpers.cs
Previously, we allow customer to update their function app with Azure CLI to create a new SCM site. Unfortunately, the SCM site lacks the SCM_RUN_FROM_PACKAGE setting, and thus, the remote build fails to update the artifact to a valid blob url.
This issue affects Linux Consumption function app created before 8/1/2019
@balag0 suggested a mitigation for current broken SCM sites.
Remove and reset the app setting for AzureWebJobsStorage. However, this method will take the function app offline and it is not recoverable if the core tool fails in the middle of a remote build deployment.
Bala may introduce a solution to refresh the SCM_RUN_FROM_PACKAGE setting when the user updates any of the app setting. Before that, we should discourage our user from manually enabling the SCM site.
resolves …
> Error out if remote build runs on a broken SCM site

- tools/python/packapp/__main__.py
We should do `python -m pip download` instead of `pip download` to avoid issues where `pip` is not in path or points to a different pip version than the one expected.
Fixes https://github.com/Azure/azure-functions-core-tools/issues/1649
> Fix how we run pip to accomodate pip not in path

- azure-pipelines.yml
- src/Azure.Functions.Cli/Actions/AzureActions/BaseAzureAction.cs
- src/Azure.Functions.Cli/Common/Constants.cs
- test/Azure.Functions.Cli.Tests/E2E/AzureResourceManagers/BaseAzureResourceManager.cs
- test/Azure.Functions.Cli.Tests/E2E/AzureResourceManagers/Commons/FunctionApp.cs
- test/Azure.Functions.Cli.Tests/E2E/AzureResourceManagers/Commons/FunctionAppLocation.cs
- test/Azure.Functions.Cli.Tests/E2E/AzureResourceManagers/Commons/FunctionAppOs.cs
- test/Azure.Functions.Cli.Tests/E2E/AzureResourceManagers/Commons/FunctionAppRuntime.cs
- test/Azure.Functions.Cli.Tests/E2E/AzureResourceManagers/Commons/FunctionAppSku.cs
- test/Azure.Functions.Cli.Tests/E2E/AzureResourceManagers/Commons/ListKeysResponse.cs
- test/Azure.Functions.Cli.Tests/E2E/AzureResourceManagers/Commons/ServerFarmPropertiesObject.cs
- test/Azure.Functions.Cli.Tests/E2E/AzureResourceManagers/Commons/ServerFarmSkuObject.cs
- test/Azure.Functions.Cli.Tests/E2E/AzureResourceManagers/Commons/StorageAccountKey.cs
- test/Azure.Functions.Cli.Tests/E2E/AzureResourceManagers/Commons/TestArgResponse.cs
- test/Azure.Functions.Cli.Tests/E2E/AzureResourceManagers/FunctionAppManager.cs
- test/Azure.Functions.Cli.Tests/E2E/AzureResourceManagers/MultiOsResourcesManager.cs
- test/Azure.Functions.Cli.Tests/E2E/AzureResourceManagers/ServerFarmManager.cs
- test/Azure.Functions.Cli.Tests/E2E/AzureResourceManagers/StorageAccountManager.cs
- test/Azure.Functions.Cli.Tests/E2E/DeploymentTests.cs
- test/Azure.Functions.Cli.Tests/E2E/E2ETestConstants.cs
- test/Azure.Functions.Cli.Tests/E2E/Helpers/TestConditions.cs
The deployment helper for Azure Functions Core Tools does not contain tests so far.
This due to a lack of tool-set to change Azure Resource via ARM 
1. Create a test resource group in an Azure Testing Subscription.
2. Generate a service principle to the test resource group.
3. In Azure DevOps pipelines, use **AzureCLI@2** and `az account get-access-token --query "accessToken"` to generate an access token in every build.
4. Pass the access token to **AZCLI_ACCESS_TOKEN**
5. Parse the AZCLI_ACCESS_TOKEN from core tool test helper
6. Use xunit test framework to perform E2E test
- **Common**: contains data models and enums for ARM requests and responses
- **BaseAzureResourceManager**: used for providing Bearer AccessToken, Subscription ID, Resource Group name
- **MultiOsResourcesManager**: …
> [E2E Test] Add features to deploy Azure resources for testing

- src/Azure.Functions.Cli/Actions/KubernetesActions/InstallKedaAction.cs
- src/Azure.Functions.Cli/Kubernetes/KubernetesHelpers.cs
- src/Azure.Functions.Cli/StaticResources/keda.yaml
Closes #1765
The upgrade from pre-1.0 KEDA to 1.0 KEDA is unfortunately breaking. This means if you already have a cluster that you had run `func kubernetes install` on before, you'll need to run `func kubernetes remove && func kubernetes install` to get things into the right shape
> Update keda static resources

- src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs
- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
- src/Azure.Functions.Cli/Common/Constants.cs
- src/Azure.Functions.Cli/Common/WorkerLanguageVersionInfo.cs
- src/Azure.Functions.Cli/Helpers/PythonHelpers.cs
- src/Azure.Functions.Cli/StaticResources/Dockerfile.python38
- src/Azure.Functions.Cli/StaticResources/StaticResources.cs
- test/Azure.Functions.Cli.Tests/PythonHelperTests.cs
✅Host release: 3.0.13113
✅Python BuildEnv image: mcr.microsoft.com/azure-functions/python:3.0.13106-python3.8-buildenv
✅https://mcr.microsoft.com/v2/azure-functions/python/tags/list "3.0-python3.8", "3.0-python3.8-appservice", "3.0-python3.8-buildenv",
1. Add Python 3.8 Dockerfile when using --docker init
2. Allow Python 3.8 to be published with --build local and --build-native-deps
> Add Python 3.8 support in core tools

- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
- Upgraded to PowerShell [6.2.4](https://github.com/PowerShell/PowerShell/releases/tag/v6.2.4).
- Minor internal improvements.
For more information, please see https://github.com/Azure/azure-functions-powershell-worker/releases/tag/v2.0.215.
> Update PowerShell Worker to v2.0.215

- build.ps1
- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
- Upgraded to PowerShell [6.2.4](https://github.com/PowerShell/PowerShell/releases/tag/v6.2.4).
- Minor internal improvements.
For more information, please see https://github.com/Azure/azure-functions-powershell-worker/releases/tag/v3.0.216.
> Update PowerShell Worker to v3.0.216

- src/Azure.Functions.Cli/npm/npm-shrinkwrap.json
- src/Azure.Functions.Cli/npm/package.json
I encountered an issue installing tools on a fresh install where the install script would fail silently before the download of "https://functionscdn.azureedge.net/public/2.4.290/Azure.Functions.Cli.win-x64.2.4.290.zip" would even start. Looking at the unzipper library that is used, I saw that a fix for the issue was merged here: 
https://github.com/ZJONSSON/node-unzipper/pull/169
This issue has similar symptoms to what I experienced, so this may be a fix for that as well:
https://github.com/Azure/azure-functions-core-tools/issues/1804
> Update unzipper npm package to resolve unzip issue during installation

- src/Azure.Functions.Cli/Actions/KubernetesActions/KubernetesDeployAction.cs
- src/Azure.Functions.Cli/Extensions/HttpExtension.cs
- src/Azure.Functions.Cli/Kubernetes/FuncKeys/FuncAppKeysHelper.cs
- src/Azure.Functions.Cli/Kubernetes/FuncKeys/KeyBasedDictionaryComparer.cs
- src/Azure.Functions.Cli/Kubernetes/KubernetesHelpers.cs
- src/Azure.Functions.Cli/Kubernetes/Models/Kubernetes/ContainerV1.cs
- src/Azure.Functions.Cli/Kubernetes/Models/Kubernetes/PodV1.cs
- src/Azure.Functions.Cli/Kubernetes/Models/Kubernetes/RoleBindingV1.cs
- src/Azure.Functions.Cli/Kubernetes/Models/Kubernetes/RoleV1.cs
- src/Azure.Functions.Cli/Kubernetes/Models/Kubernetes/ServiceAccountV1.cs
- src/Azure.Functions.Cli/Kubernetes/Models/Kubernetes/ServiceV1.cs
- test/Azure.Functions.Cli.Tests/KubernetesHelperUnitTests.cs
The changes include creation of below three flags in core tools to manages function keys in Kubernetes
- funcappkeys-secret-name: Kubernetes secret name where default function keys (host, system and function keys) will be created and can be used from the function run time container using secretRef
- funcappkeys-config-map-name: The Kubernetes configMap name where default function keys (host, system and function keys) will be created and can be used from the function run time container using configMapRef
- mount-funcappkeys-as-containervolume: A flag indicating if function keys needs to be mounted in the function run-time container as volume mount at the path "/run/secrets/functions-keys" from either from Kubernetes secret or configMap
Also, service account, role, and role-binding is …
> Initial PR for the changes to manages function keys in Kubernetes

- README.md
For debugging under vscode, x64 installer is required.
After issue #693 x64 install option is available.
Comment in https://github.com/Azure/azure-functions-core-tools/issues/693#issuecomment-573294750 says that clarification in README file is needed for installing x64 bitness from choco.
This PR adds a notice in README.md file on how specify x64 bitness when installing from choco package manager.
> Add x64 notice installing tools for debugging

- src/Azure.Functions.Cli/StaticResources/host.json
- test/Azure.Functions.Cli.Tests/E2E/InitTests.cs
closes https://github.com/Azure/azure-functions-templates/issues/906
> disabling sampling of requests in default host.json

- src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
- src/Azure.Functions.Cli/Common/Constants.cs
- test/Azure.Functions.Cli.Tests/E2E/StartTests.cs
> Check if bundle config exists, hostJson exists

- .gitignore
- publish-scripts/chocolatey/buildNUPKG.py
- publish-scripts/chocolatey/installps_template
- publish-scripts/chocolatey/nuspec_template
- publish-scripts/driver.py
- publish-scripts/shared/constants.py
- publish-scripts/shared/helper.py
- publish-scripts/ubuntu/bulidDEB.py
- publish-scripts/ubuntu/changelog_template
- publish-scripts/ubuntu/control_template
- publish-scripts/ubuntu/copyright
- publish-scripts/ubuntu/postinst_template
Moving the scripts we use in core tools from https://github.com/ahmelsayed/publish-script
I am only moving the `build` portion, as we don't use the others at the moment. And I believe `test` portion needs work, and we can move it later as needed. For now, removing prompts, and just making these into build scripts.
Closes  https://github.com/Azure/azure-functions-core-tools/issues/1918
> Add publish scripts

- publish-scripts/chocolatey/buildNUPKG.py
- publish-scripts/driver.py
- publish-scripts/shared/helper.py
- publish-scripts/ubuntu/bulidDEB.py
- publish-scripts/ubuntu/control_template
This fixes a small bug, and now starts creating two release artifacts `azure-functions-core-tools` and `azure-functions-core-tools`.
> Add build logic for -2 packages

- .gitignore
- azure-pipelines.yml
- build.ps1
- build/BuildSteps.cs
- build/FileHelpers.cs
- build/Program.cs
- build/Settings.cs
- generateMsiFiles.ps1
- generateSha.ps1
- repackageBinaries.ps1
- test/Azure.Functions.Cli.Tests/E2E/DurableTests.cs
- test/Azure.Functions.Cli.Tests/E2E/StartTests.cs
- Have added the logic to sign the binaries only on master and release/3.0
- Using ESRP service that signs the binaries significantly faster
- Added signing verification on all branches
- Added pre and post signing test
- Dynamically remove files that don't need to be signed
Fixes #1916 
Fixes #1917
> Using ESRP signing service instead of funkins, sign on for master and release/3.0

- src/Azure.Functions.Cli/StaticResources/host.json
- test/Azure.Functions.Cli.Tests/E2E/InitTests.cs
Seems like the `samplingExcludedTypes` is actually under `samplingSettings` and is simply `excludedTypes` itself as seen in [this line](https://github.com/Azure/azure-functions-host/blob/123813c244919360c4fbd54f01ee52986989562b/src/WebJobs.Script/Config/ApplicationInsightsLoggerOptionsSetup.cs#L58).
This was brought up on a [docs issue](https://github.com/MicrosoftDocs/azure-docs/issues/50233) since this file is used for new projects.
> Fix app insights sampling setting excludedTypes in template host.json

- src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs
Resolves #1927 
This looks like this is a bug that was introduced during a revert 2 years ago. Although I might be missing something since it's been around for so long unless it's pretty low impact. The code has been trying to set the value of AzureWebJobsStorage in local.settings.json, but it's been using the value it's trying to set as the value it's trying to replace (Setting y to a value of x by searching/replacing x).
> Fixed issue where AzureWebJobsStorage wasn't being properly set in local.settings.json

- src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
- src/Azure.Functions.Cli/Helpers/KuduLiteDeploymentHelpers.cs
Use &forceremotebuild=true to perform remote build in Linux Consumption deployment. This allow KuduLite overwrite WEBSITE_RUN_FROM_PACKAGE app setting once the deployment is finished, eliminating the ambiguity of the hidden app setting SCM_RUN_FROM_PACKAGE
> Use force remote build for Linux Consumption deployment v3

- src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs
- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
- src/Azure.Functions.Cli/Common/Constants.cs
- src/Azure.Functions.Cli/StaticResources/StaticResources.cs
- src/Azure.Functions.Cli/StaticResources/managedDependenciesConfig.json
- src/Azure.Functions.Cli/StaticResources/powershell.host.json
- src/Azure.Functions.Cli/StaticResources/profile.ps1
- test/Azure.Functions.Cli.Tests/E2E/InitTests.cs
This PR contains the following:
* Updated generation of host.json for PowerShell function apps to use the default `host.json` template
*  Fix for https://github.com/Azure/azure-functions-core-tools/issues/2000 -- updated `profile.ps1` template to remove Get-Module call added Disable-AzContextAutosave to improve cold start 
* Updated init_function_app_powershell_and_enable_managed_dependencies test
> Update profile.ps1 template and update generation of host.json for PowerShell function apps 

- src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs
- src/Azure.Functions.Cli/Common/Constants.cs
- test/Azure.Functions.Cli.Tests/E2E/InitTests.cs
This PR addresses https://github.com/Azure/azure-functions-core-tools/issues/1787
Set `"FUNCTIONS_WORKER_RUNTIME_VERSION"` to `"~6"` in `local.settings.json` for PowerShell function apps. 
Here is what the contents of `local.settings.json` will look like: 
```powershell
PS D:\MyFunction> gc .\local.settings.json
{
"IsEncrypted": false,
"Values": {
"FUNCTIONS_WORKER_RUNTIME": "powershell",
"FUNCTIONS_WORKER_RUNTIME_VERSION": "~6",
"AzureWebJobsStorage": "UseDevelopmentStorage=true"
}
}
```
> Add worker version for PowerShell function apps.

- src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs
- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
- src/Azure.Functions.Cli/Common/Constants.cs
- src/Azure.Functions.Cli/StaticResources/StaticResources.cs
- src/Azure.Functions.Cli/StaticResources/managedDependenciesConfig.json
- src/Azure.Functions.Cli/StaticResources/powershell.host.json
- src/Azure.Functions.Cli/StaticResources/profile.ps1
- test/Azure.Functions.Cli.Tests/E2E/InitTests.cs
Set `PowerShellWorkerDefaultVersion` to `'~7'`
Fixes https://github.com/Azure/azure-functions-core-tools/issues/2084
This PR is cherry picking two commits from 2 PRs merged from the dev branch:
* Update profile.ps1 template and update generation of host.json for PowerShell function apps -- https://github.com/Azure/azure-functions-core-tools/pull/2004
* Add worker version for PowerShell function apps -- https://github.com/Azure/azure-functions-core-tools/pull/2045
> Set `PowerShellWorkerDefaultVersion` to `'~7'`

- azure-pipelines.yml
In official builds we were running out of space on VM. Trying to use a Move instead of a Copy to save space.
> Changing CopyItems to a Move in azure pipelines

- src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
- src/Azure.Functions.Cli/Common/Constants.cs
- src/Azure.Functions.Cli/ExtensionBundle/ExtensionBundleConfigurationBuilder.cs
- src/Azure.Functions.Cli/ExtensionBundle/ExtensionBundleHelper.cs
Changing the default bundle download path for OSX. 
fixes #1999
> changing the default bundle download path for osx

- src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
Since we disable setting WEBSITE_RUN_FROM_PACKAGE in kudu-2.11a, we should remove WEBSITE_RUN_FROM_PACKAGE app setting in core tools.
> Remove WEBSITE_RUN_FROM_PACKAGE app setting (v3)

- src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
Since we disable setting WEBSITE_RUN_FROM_PACKAGE in **kudu-2.11a**, we should remove WEBSITE_RUN_FROM_PACKAGE app setting in core tools.
> Remove WEBSITE_RUN_FROM_PACKAGE app setting (v2)

- build/Settings.cs
- src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs
- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
- src/Azure.Functions.Cli/Common/Constants.cs
- src/Azure.Functions.Cli/Common/TemplatesManager.cs
- src/Azure.Functions.Cli/Extensions/StringExtensions.cs
- src/Azure.Functions.Cli/Helpers/GlobalCoreToolsSettings.cs
- src/Azure.Functions.Cli/Helpers/LanguageWorkerHelper.cs
- src/Azure.Functions.Cli/Helpers/WorkerRuntimeLanguageHelper.cs
- src/Azure.Functions.Cli/StaticResources/Dockerfile.custom
- src/Azure.Functions.Cli/StaticResources/StaticResources.cs
- src/Azure.Functions.Cli/StaticResources/customHandlerConfig.json
- test/Azure.Functions.Cli.Tests/E2E/CreateFunctionTests.cs
Port of https://github.com/Azure/azure-functions-core-tools/commit/7dd097e1d7f5ce4d6ef5bd16f425ff0a5b83da4d
This cannot be checked in until https://github.com/Azure/azure-functions-templates/pull/970 is checked in and released due to the dependency here https://github.com/Azure/azure-functions-core-tools/blob/v3.x/build/Settings.cs
> Port func init and new for custom handlers (#2093)

- src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
- src/Azure.Functions.Cli/Common/Constants.cs
- src/Azure.Functions.Cli/ExtensionBundle/ExtensionBundleConfigurationBuilder.cs
- src/Azure.Functions.Cli/ExtensionBundle/ExtensionBundleHelper.cs
This reverts commit b0455000f9001d7c6b531997097becb0ebd1aa48.
This is to fix the issue outlined here - https://github.com/Azure/azure-functions-core-tools/issues/2154
The actual I think is to not use `~` and instead use an expanded path to home directory. In my machine this just creates a directory `~`. But, to fix users right away and avoid any unwanted consequences, we should revert this change and fix this change / commit for the next release.
cc: @soninaren
> Revert "changing the default bundle download path for osx"

- src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
- src/Azure.Functions.Cli/Common/Constants.cs
- src/Azure.Functions.Cli/ExtensionBundle/ExtensionBundleConfigurationBuilder.cs
- src/Azure.Functions.Cli/ExtensionBundle/ExtensionBundleHelper.cs
[Port from V3]
This reverts commit b0455000f9001d7c6b531997097becb0ebd1aa48.
This is to fix the issue outlined here - #2154
The actual I think is to not use ~ and instead use an expanded path to home directory. In my machine this just creates a directory ~. But, to fix users right away and avoid any unwanted consequences, we should revert this change and fix this change / commit for the next release.
cc: @soninaren
> [V2] Revert "changing the default bundle download path for osx"

- src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
- src/Azure.Functions.Cli/Common/Constants.cs
- src/Azure.Functions.Cli/Helpers/ProjectHelpers.cs
- src/Azure.Functions.Cli/Secrets/UserSecretsConfigurationBuilder.cs
Resolves #1970
This will allow a user to make use of dotnet user secrets files detailed [here](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-3.1&tabs=windows). The user would also have to implement dependency injection in their function ([more info](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection)), and access their development secrets through an `IConfiguration` object.
One thing I'm unsure of is the logging I added. If that's the right way to do it, but also if those logs are clear and helpful. I want to give the user insight into the decision making process/where we looked so they are empowered to fix any issues, but I didn't want to bombard them with a bunch of "checking this folder... checking this …
> Add support for dotnet user secrets files

- src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
- src/Azure.Functions.Cli/Common/Constants.cs
- src/Azure.Functions.Cli/Common/PythonPackage.cs
- src/Azure.Functions.Cli/Common/RequirementsTxtParser.cs
- src/Azure.Functions.Cli/Helpers/PythonHelpers.cs
- src/Azure.Functions.Cli/StaticResources/StaticResources.cs
- src/Azure.Functions.Cli/StaticResources/requirements.txt
- test/Azure.Functions.Cli.Tests/E2E/InitTests.cs
- test/Azure.Functions.Cli.Tests/PublishHelperTests.cs
- test/Azure.Functions.Cli.Tests/RequirementsTxtParserTests.cs
1. Add a message for warning users to not include azure-functions-worker in requirements.txt.
```
azure-functions
```
2. Add a parser of requirements.txt in RequirementsTxtParser.cs
3. Add a warning message when `func azure functionapp publish` with `azure-functions-worker` in requirements.txt
> Warn users to stop using azure-functions-worker in requirements.txt (v2)

- test/Azure.Functions.Cli.Tests/E2E/StartTests.cs
The test was timing out because managed dependencies was taking longer to download. Disabling managed dependencies for now in the test.
> Fix powershell test

- src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
- src/Azure.Functions.Cli/Actions/HostActions/Startup.cs
- src/Azure.Functions.Cli/Common/DisplayFunctionsInfoUtilities.cs
- src/Azure.Functions.Cli/Common/Utilities.cs
- src/Azure.Functions.Cli/Diagnostics/ColoredConsoleLogger.cs
- src/Azure.Functions.Cli/Diagnostics/ColoredConsoleLoggerProvider.cs
- src/Azure.Functions.Cli/Diagnostics/LoggingBuilder.cs
- src/Azure.Functions.Cli/Diagnostics/LoggingFilterHelper.cs
- src/Azure.Functions.Cli/ExtensionBundle/ExtensionBundleHelper.cs
- src/Azure.Functions.Cli/Helpers/ProjectHelpers.cs
- src/Azure.Functions.Cli/Secrets/UserSecretsConfigurationBuilder.cs
- test/Azure.Functions.Cli.Tests/ColoredConsoleLoggerTests.cs
- test/Azure.Functions.Cli.Tests/E2E/StartTests.cs
- test/Azure.Functions.Cli.Tests/LoggingFilterHelperTests.cs
- test/Azure.Functions.Cli.Tests/UtilitiesTests.cs
Fixes #2141 Fixes #2143  Fixes #2110
This PR:
- Added `--verbose` flag. Running with `--verbose` flag will give users existing logging behavior
- If running in CI environment - https://github.com/watson/ci-info/blob/master/index.js#L52-L59, `--verbose` flag is set.
- Displays all the functions  (incorporated code from @anthonychu)
- Strips out date from log messages.
- By default `func host start` will have less verbose system logs:
- Default log level for system logs is `Warning`
- Deafult log level for user logs is `Information`
- If `Default` log level is specified in `host.json` - both user logs and system logs level is set to the value specified in `host.json`
- If `host.json` has default loglevel set to `None` - Only whitelisted logs that **VS Code** uses will be logged
- If …
> Less verbose logs on func start

- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
Moving WebJobs.Script.WebHost to 2.0.14248 and Java Worker to
1.7.3-SNAPSHOT
> Update Sprint 79/80 Functions Host references to 2.0.14248

- build/BuildSteps.cs
- build/Program.cs
- build/Settings.cs
The build has been running out of space for V3. I noticed that we ship all Python workers for all runtimes. For example, with `win-x64`, it includes, python worker for 3.6, 3.7 and 3.8 all of which have binaries for Windows, Linux and OSx. In this example, I would remove Linux and OSX as they will never be used for `win-x64` core tools.
Added other minor improvements. Hoping that this fixes the space issue. Long term, we may need a better solution such as self-hosted agents. Or I think that we should do builds separately -- Linux builds in Ubuntu, Windows in Windows. This may also speed up our builds, and solve other issues that we face such as -- `func.exe` missing executable bit in Linux, and needs to be manually added after extracting.
> Reduce size of build

- src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
- src/Azure.Functions.Cli/Common/Utilities.cs
- src/Azure.Functions.Cli/Diagnostics/LoggingFilterHelper.cs
- src/Azure.Functions.Cli/Helpers/ProjectHelpers.cs
- test/Azure.Functions.Cli.Tests/UtilitiesTests.cs
cc @anthonychu 
Fixes #2189 Fixes #2184 
- Added missing Webjobs logging filters defined here: https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Extensions/ScriptLoggingBuilderExtensions.cs#L28
For  now this is a copy of the code until issue https://github.com/Azure/azure-functions-host/issues/6588 is fixed.
- Fixed user category filter to ensure logs with category ILogger<T> are treated as user logs
> Add default webjobs loglevel filter and treat logs with category ILogger<T> as user logs

- src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
- src/Azure.Functions.Cli/Common/Utilities.cs
- src/Azure.Functions.Cli/Diagnostics/LoggingFilterHelper.cs
- test/Azure.Functions.Cli.Tests/ColoredConsoleLoggerTests.cs
- test/Azure.Functions.Cli.Tests/UtilitiesTests.cs
Porting PR https://github.com/Azure/azure-functions-core-tools/pull/2191 to V2
> [V2]Add default webjobs loglevel filter and treat logs with category ILogger<T> as user logs

- src/Azure.Functions.Cli/StaticResources/profile.ps1
- test/Azure.Functions.Cli.Tests/E2E/InitTests.cs
Fixes https://github.com/Azure/azure-functions-core-tools/issues/2206
By default, `Disable-AzContextAutosave` cmdlet call in the profile.ps1 defaults to scope user. We need to set this option for the process, so adding `-Scope Process`. Also, adding Out-Null to omit the cmdlet output.
> Update profile.ps1 template to set Disable-AzContextAutosave scope to process instead of current user.

- src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
- src/Azure.Functions.Cli/Actions/HostActions/Startup.cs
- src/Azure.Functions.Cli/Common/Utilities.cs
- src/Azure.Functions.Cli/Diagnostics/ColoredConsoleLogger.cs
- src/Azure.Functions.Cli/Diagnostics/ColoredConsoleLoggerProvider.cs
- src/Azure.Functions.Cli/Diagnostics/LoggerRuleSelector.cs
- src/Azure.Functions.Cli/Diagnostics/LoggingBuilder.cs
- src/Azure.Functions.Cli/Diagnostics/LoggingFilterHelper.cs
- src/Azure.Functions.Cli/Diagnostics/ProviderAliasUtilities.cs
- src/Azure.Functions.Cli/Helpers/GlobalCoreToolsSettings.cs
- src/Azure.Functions.Cli/Helpers/ProjectHelpers.cs
- src/Azure.Functions.Cli/Secrets/UserSecretsConfigurationBuilder.cs
- test/Azure.Functions.Cli.Tests/ColoredConsoleLoggerTests.cs
- test/Azure.Functions.Cli.Tests/E2E/StartTests.cs
- test/Azure.Functions.Cli.Tests/LoggingFilterHelperTests.cs
- test/Azure.Functions.Cli.Tests/UtilitiesTests.cs
**Resolves #2216** and **Resolves #2220**
- Use registered `LoggerFilterOptions` to filter logs
- Default log levels apply only if `LoggingFilterRule` does not have a `logLevel` for a category.
**Resolves #2217**
- Bring back time stamps in the logs
- Print Function Executing and Executed messages.
> Fix default logging filters - rely on LoggerFilterOptions

- src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
- src/Azure.Functions.Cli/Common/Utilities.cs
- src/Azure.Functions.Cli/Diagnostics/ColoredConsoleLogger.cs
- src/Azure.Functions.Cli/Diagnostics/ColoredConsoleLoggerProvider.cs
- src/Azure.Functions.Cli/Diagnostics/LoggerRuleSelector.cs
- src/Azure.Functions.Cli/Diagnostics/LoggingBuilder.cs
- src/Azure.Functions.Cli/Diagnostics/LoggingFilterHelper.cs
- src/Azure.Functions.Cli/Diagnostics/ProviderAliasUtilities.cs
- test/Azure.Functions.Cli.Tests/ColoredConsoleLoggerTests.cs
- test/Azure.Functions.Cli.Tests/E2E/StartTests.cs
- test/Azure.Functions.Cli.Tests/LoggingFilterHelperTests.cs
- test/Azure.Functions.Cli.Tests/UtilitiesTests.cs
**Resolves #2216** and **Resolves #2220**
- Use registered `LoggerFilterOptions` to filter logs
- Default log levels apply only if `LoggingFilterRule` does not have a `logLevel` for a category.
**Resolves #2217**
- Bring back time stamps in the logs
- Print Function Executing and Executed messages.
port commit # d552c6741a37422684f0efab41d541ebad2b2bd2
> Fix logging filters-rely on LoggerFilterOptions

- src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
- src/Azure.Functions.Cli/Common/Constants.cs
- src/Azure.Functions.Cli/Common/Utilities.cs
- src/Azure.Functions.Cli/Diagnostics/ColoredConsoleLogger.cs
- src/Azure.Functions.Cli/Helpers/EnvironmentHelper.cs
- test/Azure.Functions.Cli.Tests/E2E/StartTests.cs
Some small changes while investigating options for #2222. @pragnagopa let me know what you think.
* Remove ASP.NET Core startup logs if not verbose
* Change formatting to make the beginning of the command stand out a bit more
* Change timestamps to gray to make them less prominent
* Add `FUNCTIONS_CORE_TOOLS_DISPLAY_LOGO` to force ASCII art if set to `1`
> Minor changes to logging and add variable to display ascii logo

- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
- src/Azure.Functions.Cli/packages.config
NuGet tried to remote the `<Private>True</Private>` tag from the webhost references, but I put them back in because they're in the branch now. Please let me know if these shouldn't be there.
> Updated WebHost.Script references to 1.0.13154

- src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
- src/Azure.Functions.Cli/Actions/HostActions/Startup.cs
- src/Azure.Functions.Cli/Common/Constants.cs
- src/Azure.Functions.Cli/Common/Utilities.cs
- src/Azure.Functions.Cli/Helpers/ProjectHelpers.cs
- src/Azure.Functions.Cli/Secrets/UserSecretsConfigurationBuilder.cs
- test/Azure.Functions.Cli.Tests/ActionsTests/StartHostActionTests.cs
- test/Azure.Functions.Cli.Tests/E2E/StartTests.cs
Resolves #2219 
A few design decisions I wanted to explain:
- Because secrets.json is only read after the host has started (during startup), we didn't have access to secrets.json to see if the needed settings were defined. We can't parse the secrets.json ourselves because we don't necessarily know where it is and the format might change. So we create a dummy configuration which parses the secrets.json, and then use that configuration to make sure all necessary settings are defined.
- I changed all the `if (dotnet)`s to `if (userSecretsEnabled)`s because we're doing more (checks, etc...) with user secrets so I thought it would pay off to be more specific
- As a result, I changed the flow so that we're only traversing folders and parsing the csproj for secrets id once. If I had kept it how …
> Fixed warning for missing settings when they're set in user secrets file

- .gitignore
- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
- src/Azure.Functions.Cli/Common/Constants.cs
- src/Azure.Functions.Cli/Helpers/PythonHelpers.cs
- src/Azure.Functions.Cli/StaticResources/Dockerfile.python39
- src/Azure.Functions.Cli/StaticResources/StaticResources.cs
- test/Azure.Functions.Cli.Tests/PythonHelperTests.cs
Adding support for Python 3.9 in CoreTools. It currently only works for macOS and Linux and whenever we would have support for Windows, we'll remove the checks.
> Adding support for Python 3.9

- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
- Update Python Worker to 1.1.8 [Release Note](https://github.com/Azure/azure-functions-python-worker/releases/tag/1.1.8)
- Update Python Worker to 1.1.9 [Release Note](https://github.com/Azure/azure-functions-python-worker/releases/tag/1.1.9)
- Update Python Library to 1.5.0 [Release Note](https://github.com/Azure/azure-functions-python-library/releases/tag/1.5.0)
Python Worker 1.1.9 only reduces the worker size by using manylinux2010 wheel. No CX facing changes.
> Update Python Worker to 1.1.9 (v2)

- build/BuildSteps.cs
- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
- Update Python Worker to 1.1.8 [Release Note](https://github.com/Azure/azure-functions-python-worker/releases/tag/1.1.8)
- Update Python Worker to 1.1.9 [Release Note](https://github.com/Azure/azure-functions-python-worker/releases/tag/1.1.9)
- Update Python Library to 1.5.0 [Release Note](https://github.com/Azure/azure-functions-python-library/releases/tag/1.5.0)
Python Worker 1.1.9 only reduces the worker size by using manylinux2010 wheel. No CX facing changes.
This version of the core tool does not have 3.9 enable, since the Python docker images are not yet ready.
We need to have these docker images for:
1. Linux Consumption/Dedicated/Premium runtime
2. To support `func azure functionapp publish <> --build-native-dependencies`
3. To support `func init --python --docker`
> Update Python Worker to 1.1.9 (v3)

- build/BuildSteps.cs
- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
- src/Azure.Functions.Cli/Helpers/PythonHelpers.cs
- src/Azure.Functions.Cli/StaticResources/Dockerfile.python39
- test/Azure.Functions.Cli.Tests/PythonHelperTests.cs
Python Worker Release note [1.1.10](https://github.com/Azure/azure-functions-python-worker/releases/tag/1.1.10)
Miscellaneous:
Converting CRLF => LF to make the newline character consistent.
> Update v3 Python Worker Version to 1.1.10

- src/Azure.Functions.Cli/Common/Constants.cs
- src/Azure.Functions.Cli/Program.cs
Commit https://github.com/Azure/azure-functions-host/commit/12fff582f5880ee120e3ccd0ed1ea7753e705469 added support for non-overlapping worker recycle 
This PR consumes the host change 
Resolves https://github.com/Azure/azure-functions-core-tools/issues/2317
Note that to get the continuous debug experience, there is still more work required on the VS Code side, but this unblocks those changes.
> Sequential JobHost restart

- test/Azure.Functions.Cli.Tests/E2E/StartTests.cs
These tests were failing and after debugging, it looks like they weren't successfully editing the files they needed to be editing. Directly using the dotnet APIs instead of our `FileSystemHelpers` seemed to do the trick.
> Fixed user secrets failing tests

- src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
This reverts commit cd9bfca26f9c7fe06ce245f5bf69bc6486a685dd.
This allows persisting the permissions of binaries being deployed in linux consumption (Which is needed in case of custom handlers)
> WEBSITE_MOUNT_ENABLED =  1 for linux consumption

- src/Azure.Functions.Cli/ConsoleApp.cs
- src/Azure.Functions.Cli/Program.cs
- test/Azure.Functions.Cli.Tests/E2E/StartTests.cs
Fixes https://github.com/Azure/azure-functions-core-tools/issues/2307
Doing it this way ensures that we don't show the v2 upgrade warning when `func --version` is invoked. This change makes it so we show the warning if any action was found. So any command that does something other than `func --version` should show the warning.
> [v2] Only show upgrade warning when an action is invoked

- test/Azure.Functions.Cli.Tests/E2E/DurableTests.cs
The `JsonInput` function is waiting for 'parse', not 'operation'.
> Fix DurableRaiseEventTest_FileInput E2E test

- NuGet.Config
- build/BuildSteps.cs
Looks like this feed was removed -- https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json
I am not sure why we had a reference to this feed. Assuming that it's an outdated reference as the build seems to work fine without it.
> Remove old myget references

- src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs
- test/Azure.Functions.Cli.Tests/E2E/InitTests.cs
Resolves https://github.com/Azure/azure-functions-core-tools/issues/2377 
**Summary of the changes**
The `requirements.psd1` file gets created at `func init` as follows:
**Scenario 1**: A Functions user creates a PowerShell function app via the Core Tools. In this case, the customer has internet connection and the tooling is able to reach the PowerShell Gallery.
Note: For this scenario, we connect to the PowerShellGallery.com and get the latest major version of the Az module that is currently supported. After that, we replace 'MAJOR_VERSION.*' with this major version value, e.g., '5.*'. Lastly, we leave the Az module entry commented out, so the module is not downloaded when the first function invocation takes place. However, if the user would like to enable downloading/installing the Az …
> Update requirements.psd1 for PowerShell function apps and disable downloading the Az module by default.

- src/Azure.Functions.Cli/Common/Constants.cs
This is to support running Durable Functions with the new SQL backend that's currently under development.
> Add Durable triggers to TriggersWithoutStorage

- src/Azure.Functions.Cli/Kubernetes/KEDA/V2/KedaV2Resource.cs
Adds Keda support for default connection variable names for Azure Service Bus, Azure Queue Storage, and Azure Blob Storage triggers.
This change will cause the PopulateMetadataDictionary method of KedaV2Resource to default to AzureWebJobsStorage for Azure Queue Storage, and Azure Blob Storage triggers, and AzureWebJobsServiceBus in the case of Azure Service Bus triggers.
This will allow users to not have to specify their connection variable name if they intend to use supported defaults.
Resolves Azure/azure-functions-core-tools#2404
> Adds KEDA support for default connection fields for some Azure triggers

- src/Azure.Functions.Cli/Actions/KubernetesActions/KubernetesDeployAction.cs
- src/Azure.Functions.Cli/Helpers/DockerHelpers.cs
Signed-of-by: Brendan Burns
This improves the overall deployment latency by parallelizing the Docker push and the Kubernetes setup. It still waits for the push to complete before creating the final deployment.
> Parallelize the Kubernetes build tasks to improve latency.

- src/Azure.Functions.Cli/Actions/DeployActions/Platforms/KnativePlatform.cs
- src/Azure.Functions.Cli/Actions/KubernetesActions/InstallKedaAction.cs
- src/Azure.Functions.Cli/Actions/KubernetesActions/KubernetesDeployAction.cs
- src/Azure.Functions.Cli/Kubernetes/KubernetesHelpers.cs
- src/Azure.Functions.Cli/Kubernetes/Models/Kubernetes/ObjectMetadataV1.cs
Signed-off-by: Tom Kerkhove <kerkhove.tom@gmail.com>
Open work:
```yaml
data:
AzureWebJobsStorage: VXNlRGV2ZWxvcG1lbnRTdG9yYWdlPXRydWU=
FUNCTIONS_WORKER_RUNTIME: ZG90bmV0
apiVersion: v1
kind: Secret
metadata:
name: foo
namespace: example
---
apiVersion: apps/v1
kind: Deployment
metadata:
name: foo
namespace: example
labels:
app: foo
spec:
selector:
matchLabels:
app: foo
template:
metadata:
labels:
app: foo
spec:
containers:
- name: foo
image: bar.io/foo
env:
- name: AzureFunctionsJobHost__functions__0
value: test
envFrom:
- secretRef:
name: foo
readinessProbe:
failureThreshold: 3
periodSeconds: 10
successThreshold: 1
timeoutSeconds: 240
httpGet:
path: /
port: 80
scheme: HTTP
startupProbe:
failureThreshold: 3
periodSeconds: 10
successThreshold: 1
timeoutSeconds: 240
httpGet:
path: /
port: …
```
> func kubernetes deploy should deploy to the current namespace, not the default

- build/BuildSteps.cs
- build/Program.cs
Add back UploadToStorage stage to publish Core Tools builds. This stage will be removed once we have daily Integration Tests Core Tools builds.
> Add back UploadToStorage stage to publish Core Tools builds

- src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs
- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
- src/Azure.Functions.Cli/StaticResources/Dockerfile.typescript
- src/Azure.Functions.Cli/StaticResources/StaticResources.cs
The old node dockerfile didn't have a build step, and thus on a clean function (e.g. git clone) it didn't work right.
> Add a typescript specific Dockerfile

- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
Update PowerShell Worker (PS7) to 3.0.705 ([Release Notes](https://github.com/Azure/azure-functions-powershell-worker/releases/tag/v3.0.705))
> Update PowerShell Worker (PS7) to 3.0.705

- build/BuildSteps.cs
- src/Azure.Functions.Cli/Helpers/DotnetHelpers.cs
VS Mac relies on our templates. I had changed the name of the templates and added multiple templates for dotnet isolated, but this breaks VS Mac experience (as they rely on a certain structure). To fix this, I am putting these files in the nested directory, as requested by the VS team.
> Fix template issue for VS Mac

- src/Azure.Functions.Cli/Actions/KubernetesActions/KubernetesDeployAction.cs
- src/Azure.Functions.Cli/Helpers/GitHelpers.cs
See https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#hashfiles
and
https://github.com/actions/runner/blob/master/src/Misc/expressionFunc/hashFiles/src/hashFiles.ts
> Improve githash calculation by adding an implementation that matches github actions.

- src/Azure.Functions.Cli/Kubernetes/KEDA/V2/KedaV2Resource.cs
This PR adds support for deploying a Durable Functions app to Kubernetes using the `func kubernetes deploy` command. It's specifically designed to use the new [MSSQL backend for Durable Functions](https://microsoft.github.io/durabletask-mssql) and relies on the [MSSQL KEDA scaler](https://keda.sh/docs/2.2/scalers/mssql/) that is part of KEDA v2.2.  Support for other backends, like the default Azure Storage backend or the new [Netherite backend](https://microsoft.github.io/durabletask-netherite) will come at another time.
I had to refactor some of the existing code because unlike all other trigger types, Durable Functions triggers are _not_ 1:1 with respect to scalers. Rather, all Durable triggers in a function app are powered by a single scaler.
I tested this using a Durable Functions app …
> K8s deployment for MSSQL-based Durable Functions

- src/Azure.Functions.Cli/Common/Constants.cs
Fix: https://github.com/Azure/azure-functions-core-tools/issues/2530
RabbitMQ Trigger doesn't required Storage account, however, It block run locally since it is not registered as non-storage account trigger. 
@yojagad Could you have a look if I am wrong? 
CC: @pragnagopa
> fix the issue of rabbitmq trigger w/o stroage account

- src/Azure.Functions.Cli/Common/Constants.cs
Fix: https://github.com/Azure/azure-functions-core-tools/issues/2530
RabbitMQ Trigger doesn't required Storage account, however, It block run locally since it is not registered as non-storage account trigger. 
v3x version of this PR. 
https://github.com/Azure/azure-functions-core-tools/pull/2531
CC: @pragnagopa
> Adding Rabbit MQ as non-Azure Storage backend for v3

- src/Azure.Functions.Cli/Kubernetes/KEDA/V2/KedaV2Resource.cs
We made some changes in the latest version of the Durable Functions SQL backend that broke Core Tools support. Specifically, we renamed the storage type name from "MicrosoftSQL" to "mssql". This PR now handles both type names.
We also added a new SQL function for getting scale information called `dt.GetScaleRecommendation`. We'd like to use this as the new default expression rather than `dt.GetScaleMetric` (though the latter will still be supported).
> Update support for Durable Functions SQL backend

- azure-pipelines.yml
As per https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/build-artifacts?view=azure-devops&tabs=yaml.
We should use PublishPipelineArtifacts instead of PublishBuildArtifacts to yield more uploading speed.
> Upgrade pipeline task PublishBuildArtifacts to PublishPipelineArtifacts

- src/Azure.Functions.Cli/Common/Constants.cs
- src/Azure.Functions.Cli/Helpers/AzureHelper.cs
PrintFunctionsInfo doesn't show anything if we deploy to the Kubernetes Environment. The reason is, just after the deployment, the restart of the worker process will started. So that we need to wait until the process is re-started again. 
We use the API `/admin/host/status` on Azure Functions Host that checks `processUptime` for watching the time. 
Currently, I set it as 60 sec according to the log and the timeout time of the `worker` process startup. 
I'm limited this behavior is happens only on `Kubernetes Environment`. 
```bash
$ func.exe azure functionapp publish tsushihttp56
Getting site publishing info...
Creating archive for current directory...
Could not find gozip for packaging. Using DotNetZip to package. This may cause problems preserving file permissions when using in a Linux …
```
> Support PrintFunctionsInfo for Kubernetes Environment

- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
Update PowerShell Worker (PS7) to 3.0.833 ([Release Notes](https://github.com/Azure/azure-functions-powershell-worker/releases/tag/v3.0.833))
> Update PowerShell Worker (PS7) to 3.0.833

- src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
In case of the Kubernetes Environment, we need to update AppSettings before the deployment happens for the binding expression update. 
cc @pragnagopa 
https://github.com/Azure/azure-functions-core-tools/issues/2579
> Enable AppSettings update before deployment happens in case of Kubernetes Environment

- src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
- test/Azure.Functions.Cli.Tests/PublishActionTests.cs
fixes #2573 
In dotnet-isolated scenarios, we need to allow the customer to specify what version of .NET they want running in their Function app. Today we assume .NET 5, but with .NET 6 coming, we need to allow this to be specified.
Ideally, we'll be able to auto-detect, but we'll still want this to allow for overrides.
> adding support for dotnet-framework-version during publishing

- src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
- src/Azure.Functions.Cli/Common/Constants.cs
- src/Azure.Functions.Cli/Helpers/AzureHelper.cs
When we use Kubernetes Environment, when we deploy the app, it returns immediately, and returns old information of the Azure Functions App. The problem is, the current version is just watch the `/host/admin/status` 's body `processUptime` is exceed `60 sec`. 
I observe when the new Function App information is available. It is on average 15 sec around. 
New Logic will be `processUptime` should be between 30 sec and 45 sec includes some slack by the experiment.  The polling was 5sec, I make it 3 sec for now.  Through the experiment, I experience some customer's pains, so that I improve that points as well.
This PR is the fix and provide additional feature for improving the customer experience of the deployment.  We need to assume several state for this sub command. 
Move from …
> fix: fetching old value of function information after deployment for Kubernetes Environment

- src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
- test/Azure.Functions.Cli.Tests/E2E/Helpers/RunConfiguration.cs
- test/Azure.Functions.Cli.Tests/PublishActionTests.cs
Fixes two issues related to dotnet-isolated publishing:
1. We would evaluate the `dotnet-version` twice.
2. If `dotnet-version` wasn't specified, it was rolling back to 5.0.
/cc @anthonychu that ran into this
> fixing dotnet-version updates during publish

- src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
- test/Azure.Functions.Cli.Tests/ActionsTests/StartHostActionTests.cs
No longer throw warning when customer uses managed identity (rather than a connection string) to connect to service.
Fixes #2552
> Support secretless extensions 

- src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
Reverting https://github.com/Azure/azure-functions-core-tools/pull/1437/files which was originally required to workaround a limitation.
> Retain Azure Files settings for Linux consumption remote build

- src/Azure.Functions.Cli/StaticResources/Dockerfile.dotnetIsolated
Fixes https://github.com/Azure/azure-functions-dotnet-worker/issues/519
> adding 3.1 to build in dotnet-isolated dockerfile

- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
Update PowerShell Worker (PS7) to 3.0.1045 ([Release Notes](https://github.com/Azure/azure-functions-powershell-worker/releases/tag/v3.0.1045))
> Update PowerShell Worker (PS7) to 3.0.1045

- build/Settings.cs
- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
This PR contains the following changes:
* Add PowerShell Worker 7.2 (package version `4.0.988`)
* Update PowerShell Worker 7.0 (package version `4.0.1049`)
* Remove PowerShell Worker 6
> Add PowerShell Worker 7.2, update PowerShell Worker 7.0, and remove PowerShell Worker 6

- src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
Fixes #2628 
I verified it by having [a dotnet function app](https://shkr-cli-publishconfig-test.azurewebsites.net/api/function1) with `#if DEBUG` conditional expressions as below and verifying the result of the endpoint before & after publishing the app using CLI with change from this PR.
string responseMessage = string.Empty;
#if DEBUG
responseMessage = "Debug build - from local CLI-1228"; 
#else
responseMessage = "Release build - from local CLI-1228"; 
#endif
return new OkObjectResult(responseMessage);
> Use "release" configuration when building dotnet function apps by default

- build/BuildSteps.cs
- build/Package.cs
Update integration tests build logic to account for multiple package versions.
This is the old package list format:
```
[
"Microsoft.Azure.WebJobs.Script",
"Microsoft.Azure.WebJobs.Script.Grpc",
"Microsoft.Azure.WebJobs.Script.WebHost",
"Microsoft.Azure.Functions.NodeJsWorker",
"Microsoft.Azure.Functions.JavaWorker",
"Microsoft.Azure.Functions.PowerShellWorker.PS7",
"Microsoft.Azure.Functions.PythonWorker"
]
```
This is the new list format with key value pairs for the name and version: 
```
[
{
"Name": "Microsoft.Azure.WebJobs.Script",
"MajorVersion": "3"
},
{
"Name": "Microsoft.Azure.WebJobs.Script.Grpc",
"MajorVersion": "3"
},
{
"Name": "Microsoft.Azure.WebJobs.Script.WebHost",
"MajorVersion": "3"
},
{
"Name": "Microsoft.Azure.Functions.NodeJsWorker",
"MajorVersion": "2"
},
{
"Name": …
```
> Update integration tests build logic to account for multiple package versions

- build/BuildSteps.cs
- build/PackageInfo.cs
Update parsing logic for the output of nuget list command
When trying to retrieve the available versions for a single package, `nuget list` returns multiple versions. See example below:
```powershell
nuget list "Microsoft.Azure.Functions.PowerShellWorker.PS7" -source "https://azfunc.pkgs.visualstudio.com/e6a70c92-4128-439f-8012-382fe78d6396/_packaging/AzureFunctionsPreRelease/nuget/v3/index.json"
Microsoft.Azure.Functions.PowerShellWorker.PS7 3.0.1008
Microsoft.Azure.Functions.PowerShellWorker.PS7.2 4.0.1127
```
I am updating the parse logic to account for this case and match the exact package name.
> Update parsing logic for the output of nuget list command

- test/Azure.Functions.Cli.Tests/E2E/StartTests.cs
The suspected cause is updates to ASP.NET Core. The issue will require further investigation and will be listed as an issue on the repo, but it will be disabled for now to allow other tests to take place.
> Disabling start_nodejs test to allow other tests

- src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
Temporary workaround for:
#2600 
#2758 
Suppresses these `LogWarning` messages when running locally:
- https://github.com/Azure/azure-functions-host/blob/12618ff4c0147ab68c30065ce49e865af6d36e51/src/WebJobs.Script/Workers/SharedMemoryDataTransfer/MemoryMappedFileAccessorUnix.cs#L135
- https://github.com/Azure/azure-functions-host/blob/12618ff4c0147ab68c30065ce49e865af6d36e51/src/WebJobs.Script/Workers/SharedMemoryDataTransfer/MemoryMappedFileAccessorUnix.cs#L180
- https://github.com/Azure/azure-functions-host/blob/12618ff4c0147ab68c30065ce49e865af6d36e51/src/WebJobs.Script/Workers/SharedMemoryDataTransfer/MemoryMappedFileAccessorUnix.cs#L194
- https://github.com/Azure/azure-functions-host/blob/12618ff4c0147ab68c30065ce49e865af6d36e51/src/WebJobs.Script/Workers/SharedMemoryDataTransfer/Memo …
> Add filter to suppress shared mem warnings locally

- src/Azure.Functions.Cli/StaticResources/keda-v2.yaml
Cherry-picking change to update KEDA installation to use v2.4 as done in PR https://github.com/Azure/azure-functions-core-tools/pull/2797.
> Cherry-Pick KEDA v2.4 Update to v4.x

- README.md
Resolves #2837
Change also needs to be ported to v3.x and v4.x branches so they are included in the npm readmes.
> Remove "preview" from v4

- src/Azure.Functions.Cli/StaticResources/keda-v2.yaml
We have released KEDA v2.5 and this updates the manifest to use it
> Update KEDA to version v2.5

- src/Azure.Functions.Cli/StaticResources/keda-v2.yaml
We have released KEDA v2.5 and this updates the manifest to use it
This change is [already merged in v3.x](https://github.com/Azure/azure-functions-core-tools/pull/2839)
> Update KEDA v2.5 Version

- src/Azure.Functions.Cli/StaticResources/javascriptPackage.json
- src/Azure.Functions.Cli/StaticResources/package.json
- Updated the version of `@azure/functions` to v3 (see [here](https://github.com/Azure/azure-functions-nodejs-worker/issues/428) for versioning info). This was the main motivation for the PR
- Simplified the scripts. For example, `func extensions install` is no longer necessary. Also I chose to get rid of `npm-run-all`. This [package](https://www.npmjs.com/package/npm-run-all) has not been updated in 3 years and has 9 of its own dependencies, both things I avoid when adding npm packages. IMO its better for the template to be clean & simple
- Made it so that it exactly matches the templates users get in VS Code
I will make a similar PR to the v3.x branch.
> Update Node.js package.json templates for `func init`

- src/Azure.Functions.Cli/StaticResources/javascriptPackage.json
- src/Azure.Functions.Cli/StaticResources/package.json
Only difference is `@azure/functions` version should be 2 instead of 3 (see [here](https://github.com/Azure/azure-functions-nodejs-worker/issues/428) for versioning info)
Original PR: https://github.com/Azure/azure-functions-core-tools/pull/2852
> Port "Update Node.js package.json templates for func init" to v3.x

- src/Azure.Functions.Cli/StaticResources/gitignore
When initializing an Azure Functions via the CLI and switching to VSCode for development the Azurite Extension in Visual Studio Code (<https://marketplace.visualstudio.com/items?itemName=Azurite.azurite>) often gets used for storage emulation in local development. The extension creates several files in the Azure Functions project directory that are only relevant for local development. In analogy to e.g. `local.settings.json` they should be ignored by git by default.
It would be very comfortable if this would also be the case for the CLI.
This pull request contains the required enhancement `.gitignore` file as a proposal to cover the scenario described above.
* [X ] My changes **should not** be added to the release notes for the next release
> Ignore Azurite Files in Function App (CLI v4)

- azure-pipelines.yml
- build.ps1
- build/BuildSteps.cs
- build/Program.cs
- build/Settings.cs
- pipelineUtilities.psm1
resolves #2871. Cherry-pick of changes in PR #2879. Small modifications for V2 include:
- removing `master` from the list of branches that trigger the pipeline, as this branch no longer corresponds with V2
- making the sole .NET SDK dependency on .NET 2.2 in `pipelineUtilities.psm1`
- removing everything related to integration builds, as they were not an original part of the V2 build pipeline
> Add SBOM generation task to V2

- src/Azure.Functions.Cli/Azure.Functions.Cli.nuspec
Removes V4 from the ID of the nupkg file generated so that major versions are not redundant.
> Removed V4 from package ID so that versions are not redundant

- src/Azure.Functions.Cli/ConsoleApp.cs
Cherry-pick of the changes from #2623, fixing a typo in the documentation of a command.
> Fix typo in RunAsync() V3

- .github/pull_request_template.md
Updates the pull request template, so that there is no reference to `release_notes.md`, as that file does not exist in this repository. Also removes the Additional Information section, as all information is expected to be included at the top. This is to be ported to `v4.x` in preparation for making that the default branch
> Removed reference to release_notes.md

- src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
- src/Azure.Functions.Cli/Helpers/AzureHelper.cs
resolves #2813 for Core Tools V4. This is to be ported to `v3.x`.
> Remove Function key by default when publishing

- build/Settings.cs
- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
- src/Azure.Functions.Cli/npm/lib/install.js
Related to https://github.com/Azure/azure-functions-core-tools/issues/2834
I was able to do some basic sanity testing (func init, func new, func start) on an M1 Mac for both JS and C# with a build created from this branch. I think that's good enough to get the PR going, but will continue to do more testing.
> Add preliminary support for osx-arm64

- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
Release Java worker 2.1.0-SNAPSHOT
https://github.com/Azure/azure-functions-java-worker/releases/tag/2.1.0-SNAPSHOT
> Release Java worker 2.1.0-SNAPSHOT

- publish-scripts/shared/constants.py
Alters the Chocolatey package name to `azure-functions-core-tools`, as all future releases to Chocolatey will be done under that name. Same changes as done in #2950 . These changes will require documentation changes as described in #2954
> Alter Chocolatey package name

- azure-pipelines.yml
- validateWorkerVersions.ps1
Currently, the process for updating workers in this repo is very disjointed and could easily lead to a situation where core tools ships a host/worker combination that is not possible in Azure. I've added a script to ensure that the worker versions match what was shipped with the respective version of the host. The script can be used to either validate the versions (as a part of the dev ops build) or update the versions (run manually before submitting a PR). Here is the criteria used to determine if a worker version matches:
1. Check the version of "Microsoft.Azure.WebJobs.Script.WebHost" in `Azure.Functions.Cli.csproj`
2. Find the matching github tag on the host repo (i.e. https://github.com/Azure/azure-functions-host/tree/v4.1.3)
3. Make sure the worker versions on that tag match what's …
> Add script to validate host/worker versions

- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
Remote builds are currently failing with this:
> /Users/erijiz/Repos/func-cli/src/Azure.Functions.Cli/Azure.Functions.Cli.csproj : error NU1605: Detected package downgrade: Microsoft.ApplicationInsights from 2.20.0 to 2.18.0. Reference the package directly from the project to select a different version. 
> /Users/erijiz/Repos/func-cli/src/Azure.Functions.Cli/Azure.Functions.Cli.csproj : error NU1605:  Microsoft.Azure.Functions.CoreTools -> Microsoft.Azure.WebJobs.Script.WebHost 4.1.3 -> Microsoft.Azure.WebJobs.Script 4.1.3 -> Microsoft.Azure.WebJobs.Script.Abstractions 1.0.3-preview -> Microsoft.ApplicationInsights (>= 2.20.0) 
> /Users/erijiz/Repos/func-cli/src/Azure.Functions.Cli/Azure.Functions.Cli.csproj : error NU1605:  Microsoft.Azure.Functions.CoreTools -> …
> Bump app insights package to fix build

- src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
resolves #1732.
If you have `"": ""` in `local.settings.json` (only repros for me on windows, not mac)
> Error: Insufficient memory to continue the execution of the program.
If you have `"": "non-empty-value"` in `local.settings.json` (repros on both windows and mac)
> Error: String cannot be of zero length. (Parameter 'variable')
> Warning: Skipping local setting with empty key.
NOTE: The issue was fixed on the dev branch by https://github.com/Azure/azure-functions-core-tools/pull/1735, but never ported to v3.x or v4.x branches. That PR did not address the second error case mentioned above and did not show a warning, so I created this PR with a new fix.
> Skip local setting with empty key

- src/Azure.Functions.Cli/Common/KeyVaultReferencesManager.cs
- test/Azure.Functions.Cli.Tests/KeyVaultReferencesManagerTests.cs
Resolves #2989. This PR corrects the regular expressions used in matching Key Vault references. Furthermore, issues with parsing Key Vault references should be non-blocking for `func start` (a warning is emitted instead). Support for other Key Vault reference formats that have secret version as an optional parameter has also been added.
The KeyVaultReferencesManager attempts to match items in the configuration with regular expressions intended to capture two Key Vault Reference formats:
1. The "primary format": `@Microsoft.KeyVault(SecretUri=https://myvault.vault.azure.net/secrets/mysecret/version)`
2. The "secondary format":  `@Microsoft.KeyVault(VaultName=myvault;SecretName=mysecret)`
While the regular expressions used indeed match with their corresponding formats, they were not …
> Make null and unsupported Key Vault reference formats non-blocking

- src/Azure.Functions.Cli/npm/npm-shrinkwrap.json
Fix for minimist https://github.com/advisories/GHSA-xvch-5gv4-984h
For those not familiar with Node.js,  `npm audit fix` updates the shrinkwrap file to fix any reported vulnerabilities that it can fix. I am on a more recent version of npm, so it also updated the shrinkwrap file to version 2, which has been the default for _a while_ and is backwards compatible with version 1.
> npm audit fix for minimist [v4]

- README.md
The "dev" branch has been our default for a while, so that's why it has the most up to date README. However, I want to copy it over to the "v4.x" branch for a few reasons:
1. The npm module gets it's readme from "v4.x" which means right now it looks out of date: https://www.npmjs.com/package/azure-functions-core-tools
2. Soon we will make v4.x the default branch
> Copy dev branch readme to v4

- src/Azure.Functions.Cli/npm/package.json
By default npm uses the "latest" tag when publishing, regardless of major version. However, we always want "latest" pointing to v4, so I've added config to use "v3" as the tag when publishing v3. I don't expect people to use this tag (you can already specify a major version by doing `azure-functions-core-tools@3` as described in our [readme](https://github.com/Azure/azure-functions-core-tools#to-install-with-npm)), but this was one of the recommended workarounds in https://github.com/npm/npm/issues/6778 and I see other people doing similar things (example [here](https://www.npmjs.com/package/npm) and [here](https://www.npmjs.com/package/@angular/core) if you go to the versions tab)
> Add v3 tag to npm package

- azure-pipelines.yml
- build/BuildSteps.cs
- build/Settings.cs
- repackageBinaries.ps1
Related to https://github.com/Azure/azure-functions-core-tools/issues/2834, Apple [requires](https://eclecticlight.co/2020/08/22/apple-silicon-macs-will-require-signed-code/) arm64 executables to be signed in order to run. Without signing, any command just silently fails. A few notes:
1. This requirement does not apply to x64 executables, but it's still encouraged to sign binaries when possible and it's trivial for us to sign both x64 and arm64 at the same time
1. The requirement does not extend to dlls or other binaries. My changes are the minimum required to unblock users from running `func`, but we may want to consider signing those other bits in the future
1. The `.exe` file extension is unique to windows. Mac executables have _no_ file extension
1. Mac signatures are completely …
> Sign mac executables

- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
- src/Azure.Functions.Cli/Kubernetes/FuncKeys/FuncAppKeysHelper.cs
Resolves #2944 for Core Tools V4. **This PR should not be merged until the WebHost and worker versions have been updated for the next Core Tools V4 release corresponding to Host version 4.3.1 or later.** This change is to be backported to `v3.x`.
> Alter key generation logic V4

- src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
- src/Azure.Functions.Cli/Helpers/ProjectHelpers.cs
- test/Azure.Functions.Cli.Tests/E2E/StartTests.cs
resolves [#issue_for_this_pr](https://github.com/Azure/azure-functions-dotnet-worker/issues/827)
Reference PR - https://github.com/Azure/azure-functions-core-tools/pull/2464
> Allow user secrets in dotnet-isolated projects

- validateWorkerVersions.ps1
Alters the path specified for the Core Tools .csproj file in the validateWorkerVersions.ps1 script to use `$PSScriptRoot` rather than `.`. Currently, on a Windows machine, the use of `.` sets the path to be `C:`, which causes issues when attempting to save changes to the .csproj. This change is to be ported over to the `v3.x` branch.
> Added PSScriptRoot to validateWorkerVersions script V4

- src/Azure.Functions.Cli/Kubernetes/KEDA/V2/KedaV2Resource.cs
- test/Azure.Functions.Cli.Tests/KedaHelperUnitTests.cs
If a function with Storage Queue trigger or a Service Bus trigger doesn't have a "Connection" parameter, the default is obtained from `AzureWebJobsStorage` and `AzureWebJobsServiceBus` environment variables respectively. In this case, the generated function bindings will not have a `connection` key. While populating metadata dictionary, the code currently directly calls `metadata["connection"]` which throws a `KeyNotFoundException`. 
Hence in this PR, I added a `ContainsKey` check before accessing the `connection` key in the metadata dictionary.
> Check if connection key exists in bindings

- src/Azure.Functions.Cli/StaticResources/bundleConfig.json
Cherry-pick of changes from #3093, making the default Extension Bundles version V3.
> Upgrade default extensions bundle version (#3093)

- src/Azure.Functions.Cli/StaticResources/javascriptPackage.json
- src/Azure.Functions.Cli/StaticResources/package.json
Add azure-functions-core-tools as a dev dependency to init templates
Adds the node package of these tools as a dev dependency in package.json by default, thus enabling users to actually run `npm start` right off the bat on a fresh template without needing the core tools globally installed.
Resolves #255
> Add azure-functions-core-tools as a dev dependency to init templates package.json

- src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
- src/Azure.Functions.Cli/Actions/LocalActions/InstallExtensionAction.cs
- src/Azure.Functions.Cli/Common/Constants.cs
- src/Azure.Functions.Cli/Helpers/ExtensionsHelper.cs
- src/Azure.Functions.Cli/Helpers/ProjectHelpers.cs
- test/Azure.Functions.Cli.Tests/PublishActionTests.cs
Currently, Core Tools V4 ensures the `linuxFxVersion` setting remains empty for Linux Consumption applications, updating it only for other SKUs. However, with .NET 7 function apps on Linux, we rely on setting the value to `DOTNET-ISOLATED|7.0`. This PR:
1. Updates the `linuxFxVersion` setting for Linux Consumption publishing. 
2. Automatically detects the target framework version for .NET isolated function apps by parsing the .csproj file.
> Update linuxFxVersion for publishing .NET 7 applications

- src/Azure.Functions.Cli/StaticResources/funcignore
The default template for a Typescript function app (created using `func init --language typescript --worker-runtime node`) will install development tooling into `node_modules` when you run `npm install`.
Publishing this simple app using `func azure functionapp publish myappname` includes all this, and is therefore very slow.
This PR reduces the amount deployed to Azure by about 181 MB (on Windows) so it is substantially faster to publish.
> Improve publishing speed for Typescript apps

- src/Azure.Functions.Cli/Actions/LocalActions/CreateFunctionAction.cs
Prevents the PyStein awareness message from being printed for apps using a different language.
> Remove PyStein awareness message for non-Python apps

- .github/fabricbot.json
- azure-pipelines.yml
- build/BuildSteps.cs
- build/Settings.cs
- generateMsiFiles.ps1
- publish-scripts/chocolatey/buildNUPKG.py
- publish-scripts/chocolatey/installps_template
- repackageBinaries.ps1
- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
- src/Azure.Functions.Cli/npm/lib/install.js
Adds support for the `win-arm64` target runtime for Core Tools V4. These changes are to be ported to the `v3.x`.
> Add support for win-arm64

- src/Azure.Functions.Cli/Common/DurableManager.cs
- test/Azure.Functions.Cli.Tests/Azure.Functions.Cli.Tests.csproj
- test/Azure.Functions.Cli.Tests/E2E/DurableTests.cs
- test/Azure.Functions.Cli.Tests/E2E/Helpers/CliTester.cs
- test/Azure.Functions.Cli.Tests/E2E/Helpers/DurableHelper.cs
The Durable commands currently only work with the Azure Storage backend, and not when users configure alternate backends, like MSSQL or Netherite. This PR adds detection for those other backend types and returns an error if the user tries to run a command against function apps that use those other backend types.
(I'm not aware of any issue opened for this)
> Check for non-Azure Storage backends

- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
Resolves https://github.com/Azure/azure-functions-core-tools/issues/3183
This is a follow up PR for https://github.com/Azure/azure-functions-core-tools/pull/3184. I had a typo and meant to update `Microsoft.ApplicationInsights` to version `2.21.0` instead of `2.20.1`
> Update Microsoft.ApplicationInsights to version 2.21.0

- pipelineUtilities.psm1
Fixes error where commit was merged into `release_4.0` before `v4.x`.
> Forcing dotnet 2.1 install for ESRP Authenticode

- build/Settings.cs
- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
- validateWorkerVersions.ps1
This PR contains the following change:
* Add PowerShell 7.4 language worker to the Core Tools for integration testing -- Partially resolves https://github.com/Azure/azure-functions-core-tools/issues/3266 
* Update Functions Host to version `4.17.0`
Please note that I have removed the the `worker.config.json` from the `PowerShell 7.2` language worker. Going forward, the Functions Host will use the `worker.config.json` included in the `PowerShell 7.4` language worker nuget package.
> Add PowerShell 7.4 language worker for integration testing

- src/Azure.Functions.Cli/npm/lib/install.js
- src/Azure.Functions.Cli/npm/npm-shrinkwrap.json
- src/Azure.Functions.Cli/npm/package.json
This PR fixes an issue with `postinstall` execution script which extracts the Functions CLI tools, however in a corrupt state due to an issue occurring in https://github.com/ZJONSSON/node-unzipper/issues/271 
**These changes need to be backported to v3.x and eventually other branches. Which branches should be part of the backport?**
resolves #3335
* [] Otherwise: Documentation issue linked to PR
> Replace broken unzipper with extract-zip

- build/Settings.cs
Unhandled exception. System.Exception: sigcheck.exe test failed. Following files are unsigned: d:\a\_work\1\s\artifacts\postsigntest\azure.functions.cli.min.win-arm64.4.0.5065\_manifest\manifest.json.sha256, d:\a\_work\1\s\artifacts\postsigntest\azure.functions.cli.min.win-arm64.4.0.5065\_manifest\spdx_2.2\manifest.spdx.json.sha256
> Fixing the following exception in the pipeline.

- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
- src/Azure.Functions.Cli/Common/Constants.cs
- src/Azure.Functions.Cli/Helpers/PythonHelpers.cs
- src/Azure.Functions.Cli/StaticResources/Dockerfile.python3.11
- src/Azure.Functions.Cli/StaticResources/StaticResources.cs
- test/Azure.Functions.Cli.Tests/PythonHelperTests.cs
> Enable support for Python3.11

- src/Azure.Functions.Cli/StaticResources/package-js-v4.json
- src/Azure.Functions.Cli/StaticResources/package-ts-v4.json
I just released 4.0.0, so we can clean these versions up now.
> Remove "-alpha" from node.js v4 model templates

- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
Host 4.27.2 takes a dependency on Azure.Identity >= 1.10.0. Upgrading that here.
> Upgrading Azure Identity per host 4.27.2 requirements

- src/Azure.Functions.Cli/StaticResources/node-v4-templates.json
1. Dapr publish output binding
2. Dapr service invocation trigger
3. Dapr topic trigger
**Step 1:** Initialize the template
**Step 2:** Create new function
**Step 3:** Select the template
**Step 4:** Generated Azure function with Dapr extension using core-tool cli
> Adding Dapr node-v4 static templates

- pipelineUtilities.psm1
The release branch builds are failing without .NET 2.1. This step installs it.
> Adding Dotnet 2.1 for Authenticode step

- azure-pipelines.yml
Making the `PublishPipelineArtifacts` step run only if prev steps succeed
> Adding succeed condition to PublishPipelineArtifacts

- build/Settings.cs
- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
- src/Azure.Functions.Cli/Helpers/GlobalCoreToolsSettings.cs
- src/Azure.Functions.Cli/Helpers/WorkerRuntimeLanguageHelper.cs
- test/Azure.Functions.Cli.Tests/E2E/StartTests.cs
resolves #3603
Also cleans up some label inconsistency and leads with the isolated worker model in prompting.
> updating .NET templates and updating .NET model prompts

- azure-pipelines.yml
- publish-scripts/ubuntu/buildDEB.py
> Use xz compression for debian 11.

- src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
Modified the description of the --no-build flag for the func start command to match the grammar in the documentation.
> Fix grammar in --no-build flag description

- src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs
- test/Azure.Functions.Cli.Tests/E2E/InitTests.cs
This really helps in mono-repo scenarios in which the NPM install is not actually needed but takes a significant time to initialize a new project. (A proper warning is added if NPM installation is skipped)
resolves #3332
> Added --skip-npm-install option for NodeJS V4 programming model

- build/BuildSteps.cs
- build/Program.cs
- build/Shell.cs
- pipelineUtilities.psm1
- src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
- src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs
- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
- src/Azure.Functions.Cli/Common/Constants.cs
- src/Azure.Functions.Cli/Common/ProcessManager.cs
- src/Azure.Functions.Cli/Helpers/GlobalCoreToolsSettings.cs
- src/Azure.Functions.Cli/Interfaces/IProcessManager.cs
- src/Azure.Functions.Cli/Program.cs
- test/Azure.Functions.Cli.Tests/Azure.Functions.Cli.Tests.csproj
.NET8 Inproc support for host start action.
Follow up PRs with test (once project template change is in) will be coming.
* [x My changes **do not** need to be backported to a previous version
> .NET8 Inproc support for host start action

- src/Azure.Functions.Cli/Actions/AzureActions/LogStreamAction.cs
> Fixed typo

- build/BuildSteps.cs
- build/Program.cs
- build/Settings.cs
- build/Shell.cs
- pipelineUtilities.psm1
- src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
- src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs
- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
- src/Azure.Functions.Cli/Common/Constants.cs
- src/Azure.Functions.Cli/Common/ProcessManager.cs
- src/Azure.Functions.Cli/Helpers/GlobalCoreToolsSettings.cs
- src/Azure.Functions.Cli/Helpers/TargetFrameworkHelper.cs
- src/Azure.Functions.Cli/Interfaces/IProcessManager.cs
- src/Azure.Functions.Cli/Program.cs
- test/Azure.Functions.Cli.Tests/Azure.Functions.Cli.Tests.csproj
- test/Azure.Functions.Cli.Tests/E2E/InitTests.cs
- test/Azure.Functions.Cli.Tests/E2E/StartTests.cs
Core tools changes to support .NET8 in-proc.
The core tools artifact will now have a child folder called "in-proc8" which is the output of `dotnet publish -f net8.0` (We use an MSbuild target to do this publishing). In the `start` action, we will inspect the local.settings.json file for the presence of `FUNCTIONS_INPROC_NET8_ENABLED` setting. If this is present, that indicates the app is an in-proc net8 app. Instead of starting the app with the current core tools process (which is built for net6.0), we will launch a child func.exe process from the "in-proc8" folder.
Updated Microsoft.Azure.WebJobs.Script.WebHost to 4.834.2
> Core tools changes to support .NET8 in-proc

- src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
- src/Azure.Functions.Cli/Common/Constants.cs
This change allows Core Tools to show the forwarded URL in Core Tools when displaying the Functions during debugging - for easier invocation and debugging.
> Limelight forwarding URL display

- build/BuildSteps.cs
Include net8 artifact directories for the sign steps.
> Include net8 artifact directories for the sign steps

- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
Removing package reference of `Microsoft.IdentityModel.JsonWebTokens` & `System.IdentityModel.Tokens.Jwt` packages. Host will load the appropriate (6x or 7x) version of this package based on the TFM since `Microsoft.Azure.WebJobs.Script.WebHost` is a multi-targeted package(net6.0 and net8.0)
> Removing package reference of Microsoft.IdentityModel.JsonWebTokens & System.IdentityModel.Tokens.Jwt packages

- README.md
The instructions currently end at ubuntu 20.04, which can give the impression that 22.04 is not supported.
Tested for 22.04 and worked.
> add instructions for ubuntu 22.04

- src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
Updated Publish command dotnet-version parameter helper text to show example for .net 6 instead of old example of .net 5
resolves #3437
> Update publish dotnet-version help text to .net 6

- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
- test/Azure.Functions.Cli.Tests/E2E/InitTests.cs
Bumping a version forward to help us navigate some changes to other deps in other PRs.
Also bumping a test timeout that wasn't specified and was coming in a bit long (possibly due to new stdout)
> pinning transitive dependency forward

- src/Azure.Functions.Cli/npm/package.json
https://github.com/Azure/azure-functions-core-tools/commit/2b7cdb580f3197b97312222a7dc9b304c8e4d9f0 (from https://github.com/Azure/azure-functions-core-tools/pull/3264) reintroduced a dependency that had previously been removed by https://github.com/Azure/azure-functions-core-tools/commit/3147e27873a7521677a676d81f9f2307e4fdef8e (from https://github.com/Azure/azure-functions-core-tools/pull/3338).
The reintroduction prompted 2 other PRs to adjust that dependency, which I will close in favor of this one.
> removing unneeded dependency

- eng/ci/public-build.yml
Public builds from forks are currently failing, for example on [this PR](https://github.com/Azure/azure-functions-core-tools/pull/3371).
I copied the fix from the host: https://github.com/Azure/azure-functions-host/pull/10256
> Fix public builds from fork

- src/Azure.Functions.Cli/Program.cs
- test/Azure.Functions.Cli.Tests/ActionsTests/ResolveActionTests.cs
Kill child process when Ctrl + break key is pressed. 
Also made `IProcessManager` dependency singleton. This is a safe change because the current implementation does not store any state other than the child process count). We want a single instance (which was used to register the child process) so that we have the same child processes when we handle the Ctrl + Break key event handler, where we terminate the child processes.
> Kill child process when Ctrl + break key is pressed. 

- check-vulnerabilities.ps1
- eng/ci/templates/public/jobs/build-test-public.yml
- pipelineUtilities.psm1
Moving the scan ahead of the build so we can exit early instead of waiting for over an hour of tests before an easily detected fail state. Also removed behavior where older .NET versions we wouldn't even use were installed.
> Restructuring CI to reduce time-to-failure for scanning

- src/Azure.Functions.Cli/Common/FileSystemHelpers.cs
- src/Azure.Functions.Cli/Helpers/DotnetHelpers.cs
add searchOption parameter to GetFiles to allow for non-recursive searching
use non-recursive searching when looking for .csproj and .fsproj files during validation.
resolves #3594
* I could not find any existing tests for this function
> Fix Issue 3594: Look for csproj and fsproj non-recursively

- src/Azure.Functions.Cli/ConsoleApp.cs
- test/Azure.Functions.Cli.Tests/ActionsTests/ResolveActionTests.cs
Do not swallow `CliArgumentsException`. Return non-zero exit code if CLI arguments are incorrect.
Fixes https://github.com/Azure/azure-functions-core-tools/issues/3277
> Return non-zero exit status if failed to parse the action

- src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
- src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs
- src/Azure.Functions.Cli/Common/Constants.cs
The flag is no longer required as of host v4.28 which finished rolling out in January. Release notes [here](https://github.com/Azure/azure-functions-host/releases/tag/v4.28.0) and PR [here](https://github.com/Azure/azure-functions-host/pull/9574).
> Remove EnableWorkerIndexing flag

- src/Azure.Functions.Cli/npm/lib/install.js
resolves #3766
Setting executable permissions for `in-proc8/func` executable in install path, for unix scenarios.
Validation pending on OSX.
> Setting executable permissions for `in-proc8/func` executable in install path

- src/Azure.Functions.Cli/Common/FileSystemHelpers.cs
- src/Azure.Functions.Cli/Helpers/DotnetHelpers.cs
- src/Azure.Functions.Cli/npm/lib/install.js
##cherry-picked below commit to the release_4.0_hotfix branch
[Setting executable permissions for](https://github.com/Azure/azure-functions-core-tools/commit/098dd97f46b091f13de4f4e8c30fabb17dac2c1a) [in-proc8/func](https://github.com/Azure/azure-functions-core-tools/commit/098dd97f46b091f13de4f4e8c30fabb17dac2c1a) [executable in install code path. (](https://github.com/Azure/azure-functions-core-tools/commit/098dd97f46b091f13de4f4e8c30fabb17dac2c1a)https://github.com/Azure/azure-functions-core-tools/pull/3797[)](https://github.com/Azure/azure-functions-core-tools/commit/098dd97f46b091f13de4f4e8c30fabb17dac2c1a)
[Fix Issue 3594: Look for csproj and fsproj non-recursively](https://github.com/Azure/azure-functions-core-tools/commit/1cbe0a1e63df9e9874bb937ec8a2b0fc57514ee4)https://github.com/ …
> Hotfix 4.0.5907 Tag and adding (#3773) (#3797) commit to branch

- src/Azure.Functions.Cli/Actions/LocalActions/CreateFunctionAction.cs
- test/Azure.Functions.Cli.Tests/E2E/CreateFunctionTests.cs
resolves #2250 
Updated the 'ConfigureAuthorizationLevel' method in 'CreateFunctionAction.cs', to change the 'authLevel' value from PascalCase to camelCase in the 'function.json' file when creating an 'HttpTrigger' function in the PowerShell worker runtime.
> AuthLevel flag on HttpTrigger generates upper case values fix - 2250

- src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs
- src/Azure.Functions.Cli/Helpers/DotnetHelpers.cs
- test/Azure.Functions.Cli.Tests/E2E/InitTests.cs
resolves #3771 
-> This PR checks the current worker runtime of function app is dotnet and gets the target framework from the directory of function app, locating to the project file(.csproj). later in the method used to configure the Docker file
> Initializing Dockerfile for .NET isolated project does not honor existing TFM

- build/BuildSteps.cs
Before for e.g. macOS or Windows the `gozip` executable did not match the target OS architecture. This PR fixes that:
Fixes https://github.com/Azure/azure-functions-core-tools/issues/3648
cc @arroyc
> fix: gozip across different host OS architectures

- azure-pipelines.yml
- build.ps1
- build/BuildSteps.cs
- build/Program.cs
- build/Settings.cs
- code-mirror.yml
- eng/ci/official-build.yml
- eng/ci/public-build.yml
- pipelineUtilities.psm1
- src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
- src/Azure.Functions.Cli/Common/DotnetConstants.cs
- test/Azure.Functions.Cli.Tests/Azure.Functions.Cli.Tests.csproj
- test/Azure.Functions.Cli.Tests/E2E/CreateFunctionTests.cs
- test/Azure.Functions.Cli.Tests/E2E/InitTests.cs
- test/Azure.Functions.Cli.Tests/E2E/StartTests.cs
- validateWorkerVersions.ps1
resolves #3744 
This PR creates the feature branch `feature/oop-host`, which has the OOP host build. This PR also includes checks for the user passing in the `--runtime` param specifying the host and infers the host if that is not specified. I've also added tests which checks that we try to execute the correct func.exe (even though those tests technically fail since there is no `inproc-6` or `inproc-8` folder). We also only run on .NET 8 TFM and remove multi-targeting in the feature branch.
For when the user specifies the `--runtime` parameter, these are the following scenarios we support today where the first row is the options the user may put in and the first column are the potential apps a user may have:
| | inproc6|inproc8|default|
|--|:-------:|:-------:|:-------:|
|.NET Isolated …
> Core Tools OOP Host

- build/BuildSteps.cs
- build/Program.cs
We don't want `UploadToStorage` to run as part of the build process, since this causes the daily build to run this version of core tools.
> Fix build to remove uploadToStorage

- eng/ci/official-build.yml
- eng/ci/public-build.yml
- eng/ci/templates/official/jobs/build-test.yml
- eng/ci/templates/public/jobs/build-test-public.yml
- test/Azure.Functions.Cli.Tests/E2E/InitTests.cs
- test/Azure.Functions.Cli.Tests/E2E/StartTests.cs
Build YAML changes for producing net6 and net8 artifacts.  This change was originally part of #3837, but the public build was not using the src code from the PR branch for building it, which caused it to fail. Tried force pushing to that branch, but that also did not help. So I removed those CI file changes. Adding them in this PR now.
> Build YAML changes to produce net6 and net8 artifacts.

- src/Azure.Functions.ArtifactAssembler/ArtifactAssembler.cs
- src/Azure.Functions.ArtifactAssembler/Program.cs
Updating the inproc artifact name to include "_inproc" suffix in the name. Example value after this change `Azure.Functions.Cli.min.win-x64_inproc.4.0.6353.zip`
> Updating the inproc artifact name to include "_inproc" suffix in the name

- test/Azure.Functions.Cli.Tests/E2E/StartTests.cs
Rename tests to follow csharp naming patterns & separate func start commands from func init commands.
There should be no functional changes in this PR other than fixing one path mistake (I'll point this out below)
Chain of PRs:
1. #3847
2. #3850 
3. #3846
> StartTests: Rename tests & seperate func start commands from init

- src/Azure.Functions.Cli/Common/Executable.cs
- src/Azure.Functions.Cli/Common/JobObjectRegistry.cs
- test/Azure.Functions.Cli.Tests/E2E/Helpers/CliTester.cs
- test/Azure.Functions.Cli.Tests/E2E/Helpers/LogWatcher.cs
- test/Azure.Functions.Cli.Tests/E2E/Helpers/ProcessHelper.cs
- test/Azure.Functions.Cli.Tests/E2E/Helpers/RetryHelper.cs
- test/Azure.Functions.Cli.Tests/E2E/Helpers/RunConfiguration.cs
- test/Azure.Functions.Cli.Tests/E2E/StartTests.cs
- Implement test cleanup measure to kill processes on a given port 
- Make `Executable` class disposable by implementing `IAsyncDisposable` interface
- Add job registry to clean up child processes
- Add log watcher with timeout to check for a specific log message
- Add logic to wait for function host to be in a running state
Chain of PRs:
1. #3847
2. #3850 
3. #3846
> Implement measures to fix flakey tests

- host/src/CoreToolsHost/CoreToolsHost.csproj
We observed an issue with the custom host when using .NET 6 in-process on some devices. This would lead to a VS launch getting `...\4.90.0-inprocess\cli_x64\func.exe (process 25096) exited with code -1073740791 (0xc0000409)`. After checking with the .NET team, it was determined that this was due to the changes described in https://github.com/dotnet/docs/issues/42600. Disabling CET worked for my own repro.
> Disabling CET compatiblity for custom host

- host/src/CoreToolsHost/Logger.cs
- host/src/CoreToolsHost/Program.cs
Resolves #3858
The existing setup allows for early exits with an error code of 0. This should be 1 to reflect the error state. These changes also add defensiveness and reduce the set of scenarios that can cause us to exit. The logic is more tolerant of the project lacking or having a malformed `local.settings.json`. My justification for this is that we should not care if `FUNCTIONS_WORKER_RUNTIME` is present or not from the custom host's perspective. That state simply implies that .NET 6 should be used. For .NET 8 on the in-process model, we hard-require the two settings are provided through `local.settings.json`. The custom host logic just needs to determine if those .NET 8 criteria are met.
Also included are some minor changes to the custom host logger to make it more consistent with …
> Restructuring custom host to improve error handling

- host/src/CoreToolsHost/LocalSettingsJsonParser.cs
- host/src/CoreToolsHost/Program.cs
This addresses two known issues with the custom host version of the Core Tools.
Previous versions of the Core Tools tolerated JSON comments just fine, but the custom host would break on them. This PR adds tolerance for JSON comments.
It also appears that FUNCTIONS_INPROC_NET8_ENABLED could be set with an integer value rather than a string in previous versions. Although we document this as being a string, the system did not enforce this until the custom host version of the Core Tools. This PR removes that enforcement and re-allows integer values.
I've verified these through local testing.
These changes are connected to https://github.com/Azure/azure-functions-core-tools/issues/3856 and https://github.com/Azure/azure-functions-core-tools/issues/3864. It is not known at present if this is …
> Support comments and int values of FUNCTIONS_INPROC_NET8_ENABLED

- test/Azure.Functions.Cli.Tests/E2E/Helpers/ProcessHelper.cs
- test/Azure.Functions.Cli.Tests/E2E/Helpers/RunConfiguration.cs
- test/Azure.Functions.Cli.Tests/E2E/StartTests.cs
Following up on PR feedback from my last [PR](https://github.com/Azure/azure-functions-core-tools/pull/3850), to address potential port issues:
https://github.com/Azure/azure-functions-core-tools/pull/3850#discussion_r1786874896
> Use dynamic port generator for StartTests

- host/src/CoreToolsHost/Program.cs
Makes the string comparison tolerate different casing for FUNCTIONS_WORKER_RUNTIME
> Fixing custom host string comparison

- .vscode/tasks.json
I use the VS Code publish task when I work on core tools and it's currently giving this error:
> The 'Publish' target is not supported without specifying a target framework. The current project targets multiple frameworks, you must specify one of the following frameworks in order to publish: net6.0, net8.0
So I added config that allows you to pick the framework when running the task.
> Specify framework in VS Code publish task

- src/Azure.Functions.Cli/Actions/KubernetesActions/KubernetesDeployAction.cs
--build-image sets `BuildImage` property
the code in src/Azure.Functions.Cli/Actions/KubernetesActions/KubernetesDeployAction.cs:L117 needs false to skip building
Update helpstring to reflect reality.
> kubernetes deploy: --image-build fix help text

- src/Azure.Functions.Cli/npm/lib/install.js
- src/Azure.Functions.Cli/npm/package.json
Part of https://github.com/Azure/azure-functions-core-tools/issues/3826
We need the CDN link to be updated when publishing the NPM artifacts. We pass in the consolidatedBuildId into package.json by reading the value from `metadata.json` in the powershell script and updating it to correspond to it. The install.js file then reads the value passed in and proceeds.
> NPM publish update

- publish-scripts/chocolatey/buildNUPKG.py
- publish-scripts/driver.py
Related to issue: https://github.com/Azure/azure-functions-core-tools/issues/3826
We need to update the driver.py script so that we download the correct version of the artifacts with the updated CDN link
> Update Chocolatey script for CDN download

- publish-scripts/driver.py
For the core tools release we need to make sure that the nupkg name does not change just because we are adding an additional argument.
Related to issue: https://github.com/Azure/azure-functions-core-tools/issues/3826
> Fix publish script bug for chocolatey

- src/Azure.Functions.ArtifactAssembler/ArtifactAssembler.cs
- src/Azure.Functions.ArtifactAssembler/CliArtifactZipper.cs
- src/Azure.Functions.ArtifactAssembler/Constants.cs
- src/Azure.Functions.ArtifactAssembler/Program.cs
Related to issue: https://github.com/Azure/azure-functions-core-tools/issues/3826
I added the cli artifact zipper to the artifact assembler project, since homebrew fails for linux and mac with zipping through powershell. I tested this out by having homebrew consume a zip file that I uploaded to a blob storage account after running the zip script locally and saw that installation worked as expected.
> Add CLI artifact zipper

- src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
- src/Azure.Functions.Cli/Helpers/GlobalCoreToolsSettings.cs
- test/Azure.Functions.Cli.Tests/E2E/StartTests.cs
-> when local.settings.json is absent.
Scenario1: running 'func host start' will Display Available WorkerRuntime on the screen and user can select the Runtime from the list so the FUNCTION_WORKER_RUNTIME setting is added and start hosting the function app
Scenario2: running 'func host start --{WorkerRuntime}' will add FUNCTION_WORKER_RUNTIME setting and start hosting the function app.
resolves #3544
> When local.settings.json is absent, runnig func host start does not work for newer worker models #3544 (Refreshed Branch Changes)

- src/Azure.Functions.Cli/Common/Constants.cs
- test/Azure.Functions.Cli.Tests/E2E/InitTests.cs
Item pending GA of PowerShell 7.4 by 8/31 and matching Stacks API change here: https://github.com/Azure/azure-functions-ux/pull/7768
Does this need to be backported?
> Set the default PowerShell worker to 7.4

- eng/ci/linux-build.yml
- eng/ci/templates/official/jobs/linux-package.yml
- publish-scripts/driver.py
- publish-scripts/shared/helper.py
Part of issue [#3826](https://github.com/Azure/azure-functions-core-tools/issues/3826)
This PR fixes the linux package pipeline by adding the `feature/oop-host` branch to the `trigger:` in the `linux-build.yml` file and corrects the CDN link. The runner of the pipeline now has to update the `ConsolidatedBuildId` variable manually when running the pipeline, but this will create the linux packages that are needed for the APT step.
> Fix linux package pipeline

- README.md
- code-mirror.yml
- eng/ci/build-core-tools-host-artifacts-windows.yml
- eng/ci/linux-build.yml
- eng/ci/official-build.yml
- eng/ci/public-build.yml
This PR updates the pipeline references from `v4.x` to `main` in the Azure Functions Core Tools repository to let the pipelines build the default host.
> Update pipeline references from v4.x to main

- src/Azure.Functions.ArtifactAssembler/ArtifactAssembler.cs
resolves [#4203](https://github.com/Azure/azure-functions-core-tools/issues/4203)
Instead of having the mac custom host, we decided to have the .NET 6 binaries for OSX artifacts be deployed as part of the tooling feed VS release. Although signing in the osx custom host works today, there is an issue being hit when trying to test E2E. Therefore, today the value in the tooling feed is hardcoded as a previously released .NET 6 inproc version. This change allows the tooling feed to at least release the latest bits for the OSX artifacts.
Note this is also targeting `aibhandari/custom-host-e2e-tests` as I have some major refactoring/changes that I made to the ArtifactAssembler that I wanted to preserve here.
> Adding .NET 6 Binaries for VS OSX Artifacts

- check-vulnerabilities.ps1
- skipPackagesCve.json
The core tools pipeline today is blocked due to the CVE for `DotNetZip`. Brett has a PR out for resolving the changes [here](https://github.com/Azure/azure-functions-core-tools/pull/4212), but in order to unblock the daily builds and pending PRs, I have created a workaround for any CVEs that we want to skip when running the security vulnerability check to be specified in `skipPackagesCve.json`. 
Please note that any CVEs that have been addressed after will have to be removed from the JSON file. If the CVE is resolved and the package is not removed from the JSON file, the security vulnerability check will fail.
> Update check-vulernabilities.ps1 to skip packages specified in JSON file

- src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
- src/Azure.Functions.Cli/Helpers/WorkerRuntimeLanguageHelper.cs
- test/Azure.Functions.Cli.Tests/E2E/StartTests.cs
resolves https://github.com/Azure/azure-functions-core-tools/issues/4193
There was a regression in a previous core tools release where the environment was no longer being check for `FUNCTIONS_WORKER_RUNTIME`. This PR fixes this by checking for the worker runtime in the environment during the start operation. This PR also cleans up the tests for "MissingLocalSettingsJson".
> Check environment for 'FUNCTIONS_WORKER_RUNTIME' on start

- publish-scripts/chocolatey/installps_template
Part I:  when we install Azure Function Core Tool via chocolatey, the shim is generating twice as we have 3.exe files (in root folder inproc6 and inproc8 folder). Now we have added additional checks to ignore func.exe from subfolders (inproc6 and inproc8 folder) and generate shim for func.exe in root directory.
resolves #3776
> Ensure only root level func.exe is symlinked in Chocolatey package

- src/Azure.Functions.Cli/Common/Constants.cs
- src/Azure.Functions.Cli/Helpers/VersionHelper.cs
- test/Azure.Functions.Cli.Tests/E2E/VersionTests.cs
Part II: we are getting message of older version when we install Azure Function Core Tool latest version via Windows and macOS. 
To resolve this In **VersionHelper.cs** 'IsRunningOlderversion' method we have changed the logic to get the **Latest Release version** from [GitHubReleaseApiUrl](https://api.github.com/repos/Azure/azure-functions-core-tools/releases/latest)  by extracting it from **tag_name** and compare it with **Cliversion**
resolves #3776
> Update VersionHelper to utilize GH release tag for version check

- test/Azure.Functions.Cli.Tests/E2E/CreateFunctionTests.cs
- test/Azure.Functions.Cli.Tests/E2E/InitTests.cs
- test/Azure.Functions.Cli.Tests/E2E/StartTests.cs
- test/Azure.Functions.Cli.Tests/E2E/StartTests_default.runsettings
- test/Azure.Functions.Cli.Tests/ExtensionsTests/ExtensionBundleTests.cs
I accidently stopped tests from running in my previous PR, so I'm fixing them in this PR  to ensure they still run.
One key change I made previously was that we assert `ExitInError` now to ensure that the tests error out when expected to do so. A lot of the unit tests need to add the assertion as well to make sure the tests pass as expected
> Fixing Core tools tests

- src/Azure.Functions.Cli/StaticResources/ExtensionsProj.csproj.template
- test/Azure.Functions.Cli.Tests/E2E/InitTests.cs
resolves [#3707 ](https://github.com/Azure/azure-functions-core-tools/issues/3707)
This PR sets the TFM for extensions proj to net6 to address issues compatibility issues.
> Setting TFM to net6 for ExtensionsProj

- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
- test/Azure.Functions.Cli.Tests/E2E/InitTests.cs
- validateWorkerVersions.ps1
With the refactor of the host, each Worker.props file has been split into `eng/build/Worker.[WorkerName].props`, rather than having the worker references directly in the csproj. The `validateWorkersVersions.ps1` script has been updated to reflect this change.
Example of running `validateWorkerVersions.ps1 -Update -HostVersion 4.1037.0`:
> Fix validateWorkersVersions.ps1 script

- publish-scripts/ubuntu/buildDEB.py
> Update the debian pack script

- check-vulnerabilities.ps1
- eng/ci/templates/official/jobs/build-test.yml
- eng/ci/templates/public/jobs/build-test-public.yml
- pipelineUtilities.psm1
- skipPackagesCve.json
- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
- test/Azure.Functions.Cli.Tests/E2E/InitTests.cs
- validateWorkerVersions.ps1
The in-proc builds for the core tools pipeline breaks, due to the architecture of the build not being specified like how it is for the main branch. This PR also addresses the CVE for DotnetZip which will be addressed by Brett's PR [here](https://github.com/Azure/azure-functions-core-tools/pull/4212)
This PR also addresses bumping up the host and worker versions as well which will be used in the next release.
> Fixing in-proc pipeline

- eng/ci/linux-build.yml
- eng/ci/templates/official/jobs/linux-package.yml
The linux build pipeline fails on every single run as its always trying to upload the package to blob, and since the version of core tools its trying to upload already exists, the upload step fails leading to a pipeline failure.
Instead, I want to change the pipeline so thay when it runs on main, it just builds the pipeline, and when we want to upload the pkg to storage, we can set that variable.
This is a temp fix for now, and we are planning to redesign this pipeline in future. The upload step should move to a release pipeline.
> Update linux build pipeline to not upload to storage by default

- README.md
- build/Settings.cs
- src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
- src/Azure.Functions.Cli/npm/lib/install.js
Add support for Debian11 (bulleye) on ARM64. 
part of  #3112
> Add preliminary support for linux-arm64

- src/Azure.Functions.ArtifactAssembler/PipelineHelpers/generateMetadataFile.ps1
The `metadata.json` file was not being generated correctly due to a bug in the script for parsing the visual studio files to have a `.zip` ending in the name, which is not valid anymore. This PR fixes the bug by updating the regular expression to match the correct file name.
> Fix metadata.json file

- src/Azure.Functions.Cli/npm/lib/main.js
> Handle SIGINT and SIGTERM for Node.js process

- eng/ci/consolidate-artifacts.yml
- eng/ci/templates/official/jobs/assemble-artifacts.yml
- eng/ci/templates/official/jobs/build-test.yml
- eng/ci/templates/official/jobs/process-nuget-package.yml
- src/Azure.Functions.ArtifactAssembler/ArtifactAssembler.cs
- src/Azure.Functions.ArtifactAssembler/PipelineHelpers/generateSha.ps1
- src/Azure.Functions.ArtifactAssembler/PipelineHelpers/moveNugetPackage.ps1
- src/Azure.Functions.ArtifactAssembler/Program.cs
- src/Azure.Functions.ArtifactAssembler/REAME.MD
resolves #4270 #4271
This PR converts the consolidated pipeline which was initially based off of azure classic pipelines UX to a yaml based pipeline.
I have updated the `ArtifactAssembler` within core tools to be able to process each artifact type one at a time. For example, if I were to pass in `Azure.Functions.Cli.win-x64` when running the artifact assembler, the artifact assembler would only assemble artifacts for that win-x64. This enables us to use parallelization when running the consolidated pipeline, which significantly improves the run time overall.
The consolidated pipeline also publishes the artifacts to the pipeline directly, rather than publishing to a storage account. Please look at [this run](https://azfunc.visualstudio.com/internal/_build/results?buildId=206028&view=results …
> Convert consolidated pipeline to a YAML based pipeline and enable nightly builds

- src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
- test/Azure.Functions.Cli.Tests/E2E/StartTests.cs
->updated message precisely to set 'FUNCTIONS_INPROC_NET8_ENABLED' to 1 when we are running .NET 8 inproc app
-> Also added a warning to migrate to supported version if user intended to run in .NET 6 inproc6 app
resolves #4155
> Updated message when we run .NET 8 inproc app and added warning to migrate when running on .NET 6 inproc6 app

- build/Build.csproj
- eng/Directory.Build.Common.props
- src/Cli/ArtifactAssembler/ArtifactAssembler.cs
- src/Cli/ArtifactAssembler/Program.cs
- src/Cli/func/Actions/HostActions/StartHostAction.cs
- src/Cli/func/Actions/HostActions/Startup.cs
- src/Cli/func/Actions/HostActions/WebHost/Security/CliAuthenticationHandler.cs
- src/Cli/func/ConsoleApp.cs
- src/Cli/func/Helpers/RetryHelper.cs
- src/Cli/func/Telemetry/ExternalTelemetryProperties.cs
- src/Cli/func/Telemetry/Telemetry.cs
- src/CoreToolsHost/AppLoader/HostFxr.cs
- src/CoreToolsHost/LocalSettingsJsonParser.cs
> Fix warnings in solution (excluding build csproj)

- src/Cli/func/Actions/LocalActions/CreateFunctionAction.cs
On [https://learn.microsoft.com/en-us/azure/azure-functions/create-first-function-cli-python](https://learn.microsoft.com/en-us/azure/azure-functions/create-first-function-cli-python?tabs=linux%2Cbash%2Cazure-cli%2Cbrowser#create-a-local-function) it is explained that a new function can be created with the command: `func new --name HttpExample --template "HTTP trigger" --authlevel "anonymous"`, however executing this command generates invalid code. When trying to run func start afterwards, an exception is raised.
Expected Generated Code:
@app.route(route="HttpExample", auth_level=func.AuthLevel.ANONYMOUS)
Actual Generated Code:
@app.route(route="HttpExample", auth_level=func.AuthLevel.Anonymous)
This code contains a fix for this issue. The problem is that in python the enums should be …
> Fix: func new not creating a valid template with Python

- src/Cli/func/Telemetry/DockerContainerDetectorForTelemetry.cs
- src/Cli/func/Telemetry/ExternalTelemetryProperties.cs
- src/Cli/func/Telemetry/IDockerContainerDetector.cs
- src/Cli/func/Telemetry/ITelemetry.cs
- src/Cli/func/Telemetry/MacAddressGetter.cs
- src/Cli/func/Telemetry/PersistenceChannel/BaseStorageService.cs
- src/Cli/func/Telemetry/PersistenceChannel/FixedSizeQueue.cs
- src/Cli/func/Telemetry/PersistenceChannel/FlushManager.cs
- src/Cli/func/Telemetry/PersistenceChannel/PersistenceChannel.cs
- src/Cli/func/Telemetry/PersistenceChannel/PersistenceChannelDebugLog.cs
- src/Cli/func/Telemetry/PersistenceChannel/PersistenceTransmitter.cs
- src/Cli/func/Telemetry/PersistenceChannel/Sender.cs
- src/Cli/func/Telemetry/PersistenceChannel/SnapshottingCollection.cs
- src/Cli/func/Telemetry/PersistenceChannel/SnapshottingDictionary.cs
- src/Cli/func/Telemetry/PersistenceChannel/StorageService.cs
- src/Cli/func/Telemetry/PersistenceChannel/StorageTransmission.cs
- src/Cli/func/Telemetry/Sha256Hasher.cs
- src/Cli/func/Telemetry/Telemetry.cs
- src/Cli/func/Telemetry/TelemetryCommonProperties.cs
- src/Cli/func/Telemetry/TelemetryEvent.cs
Series of PRs to address error or warnings style issues in src/Cli/func
> Fix style in Telemetry/

- test/Cli/TestFramework/Assertions/CommandResultAssertions.cs
- test/Cli/TestFramework/Assertions/CommandResultExtensions.cs
- test/Cli/TestFramework/CommandInfo.cs
- test/Cli/TestFramework/Commands/FuncCommand.cs
- test/Cli/TestFramework/Helpers/FunctionAppSetupHelper.cs
When merging in the PR for adding the `Azure.Functions.Cli.TestFramework.csproj`, the namespaces were not updated to reflect the latest changes of being `Azure.Functions.Cli.Abstractions.Command` versus `Azure.Functions.Cli.Abstractions`.
> Updating namespaces in `Azure.Functions.Cli.TestFramework`

- build/Settings.cs
> Update PowerShell worker runtime filters

- eng/ci/templates/official/jobs/build-test.yml
- eng/scripts/modules/pipelineUtilities.psm1
The official pipeline was broken due to the SBOM Manifest step failing due to an expired token. This is already handled by the 1ES template, so this PR removes that step completely and restores the official pipeline.
Example of pipeline passing: https://azfunc.visualstudio.com/internal/_build/results?buildId=214274&view=logs&s=2b1cf740-7e83-5b38-9f56-89c750cf5d77&j=6ce172a1-8e70-5920-fc7b-153ca736e7e6
> Fixing official pipeline

- build/Settings.cs
This pull request updates the version constants for various .NET templates in the `build/Settings.cs` file.
Version updates:
* Updated the following constants to version `4.0.5086`:
- `DotnetIsolatedItemTemplatesVersion`
- `DotnetIsolatedProjectTemplatesVersion`
- `DotnetItemTemplatesVersion`
- `DotnetProjectTemplatesVersion`
> updating template version to 4.0.5086

- eng/ci/consolidate-artifacts.yml
- eng/scripts/ArtifactAssemblerHelpers/generateMetadataFile.ps1
- src/Cli/ArtifactAssembler/ArtifactAssembler.cs
> Update CI to package linux arm64

- .vscode/launch.json
- src/Cli/func/Actions/HelpAction.cs
- src/Cli/func/Actions/HostActions/StartHostAction.cs
- src/Cli/func/Actions/LocalActions/InitAction.cs
- src/Cli/func/Azure.Functions.Cli.csproj
- src/Cli/func/Common/Constants.cs
- src/Cli/func/Common/Utilities.cs
- Refactored the CliVersion prop so we get the full version and not the assembley version. This ensures that when `func --version` is called, the user should see 4.0.8050-preview1` and not just `4.0.8050`.
- Updated project version to add `-preview1` suffix
- Implemented `WarnIfPreviewVersion` method to notify users that they are on a preview version of the CLI. This should print when in preview when `func`, `func --version`, `func init`, `func new`, or `func start` is invoked.
> Print warning if preview version

- src/Cli/func/Common/Utilities.cs
PowerShell does work in the preview with linux-arm64; removing from warning message
> Update preview warning message

- eng/ci/consolidate-artifacts.yml
- eng/ci/linux-build.yml
- eng/ci/templates/official/jobs/assemble-artifacts.yml
- eng/ci/templates/official/jobs/linux-package.yml
- eng/scripts/ArtifactAssemblerHelpers/generateMetadataFile.ps1
I updated the script for generating the metadata.json to correctly get the consolidated pipeline build id and upated the linux build pipeline to consume the new consolidated pipeline as an artifact, rather than having to input the consolidated build id.
Here's an example of metadata.json being generated in the consolidated pipeline: https://azfunc.visualstudio.com/internal/_build/results?buildId=217027&view=logs&j=e71a84ac-0726-52c9-51bd-2f019fee3725&t=310f7c14-8c13-538c-6908-6321dc994c01
and this is an example of the linux build pipeline: https://azfunc.visualstudio.com/internal/_build/results?buildId=217115&view=results. It fails since it can't find the blob on CDN but it produces the right output for the CDN link
> Updating release pipelines to have correct consolidatedBuildId and linux pipeline to consume new consolidated pipeline

- eng/ci/official-build.yml
Backport of #4415
Removing linux pipeline reference in core-tools.official for in-proc
> Remove linux pipeline reference in core-tools.official  for in-proc

- build/BuildSteps.cs
- build/Settings.cs
- src/Cli/func/Actions/HostActions/Startup.cs
- src/Cli/func/Azure.Functions.Cli.csproj
> Exclude python worker for win-arm64 builds & remove ArmAuthenticationOptions schema

- build/Settings.cs
- src/Cli/func/Azure.Functions.Cli.csproj
The python worker now throws an error when built for unsupported runtimes. We are going to exclude it for those builds. This PR is just adding linux-arm64 to the list
> Exclude python worker for linux-arm64 build

- publish-scripts/npm/lib/install.js
We are not shipping in-proc dotnet for the linux arm64 preview so we need to skip the chmod commands on the in-proc executables.
> Skip chmod on inproc func executable for arm64

- src/Cli/func/Azure.Functions.Cli.csproj
- src/Cli/func/Common/Constants.cs
- src/Cli/func/Helpers/PythonHelpers.cs
- src/Cli/func/StaticResources/Dockerfile.python3.13
- src/Cli/func/StaticResources/StaticResources.cs
- test/Azure.Functions.Cli.Tests/PythonHelperTests.cs
Supporting python 3.13 for core tools.
Updated warning logs to remove python 3.7 and 3.8. 
> Python 3.13 support 

- src/Cli/func/StaticResources/requirements.txt
- test/Cli/Func.E2E.Tests/Commands/FuncInit/PythonInitTests.cs
Adding azure-monitor-opentelemetry to requirements.txt file. 
`func init --python` will create a requirements.txt file with a comment on how to use azure-monitor-opentelemetry.
> Adding azure-monitor to requirements.txt file

- src/Cli/func/Actions/AzureActions/PublishFunctionAppAction.cs
As per [this teams thread](https://teams.microsoft.com/l/message/19:Bnp6k3byWyjErBrl4ZPm8YM1MUxEEYasnnv1DwPFX3E1@thread.tacv2/1751901676838?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=201c2bb2-812d-4986-ac92-9bfad0d6cc59&parentMessageId=1751373684116&teamName=Azure%20Functions%20Team&channelName=%5BInternal%5DAzure%20Functions%20Cognite%20Support&createdTime=1751901676838&ngc=true&allowXTenantAccess=true), adding more logs for what the exception is in the use case where the function app deploys successfully but has an error when trying to check the host status of it.
> The main problem as I see it is this exception handling will mask the underlaying error. I.e we have no clue if it times out after 15 retries checking status code of function app, or if there are some policies in …
> Add exception details if publishing function app has an error with host status

- eng/ci/code-mirror.yml
- eng/ci/consolidate-artifacts-build.yml
- eng/ci/host-artifacts-build.yml
- eng/ci/linux-artifacts-build.yml
- eng/ci/official-build.yml
- src/Cli/func/StaticResources/Dockerfile.custom
Fixes SCA warnings in our official CI pipelines.
**Docker**: Ignoring base file as it is technically compliant but the detector cannot detect the dependencies between multiple Dockerfiles, giving us a false positive.
**Kubernetes**: Disabling as the only kubernetes definitons we have are sample static templates for users to customize - they are non-prod and do not need to be scanned.
> Fix SCA warnings

- src/Cli/func/Actions/LocalActions/CreateFunctionAction.cs
- src/Cli/func/Common/TemplatesManager.cs
- src/Cli/func/Helpers/DotnetHelpers.cs
- src/Cli/func/Helpers/FileLockHelper.cs
resolves #4458
When we run dotnet new func, we are expecting the project and item templates to already be installed since they happen right before that  command for func new and func init. For some reason, when the tests run in parallel, the templateconfig.json somehow gets messed up when we have multiple instances of func new and func init running on the same machine, so it doesn't find the template for func. If we isolate each test so it isn't run in parallel, we don't see this error anymore.
I've come up with a fix where we install web jobs/isolated templates only if we need it, given that the template isn't already installed.
There also is a race condition when running E2E func new tests where `templatesManager.Templates.Result` is not set, so fetching the templates fail. This change …
> Implement file locking mechanism for templates/bundle installation

- eng/tools/publish-tools/chocolatey/installps_template
Due to community feedback and the fact that VS Code requires x64, we are updating the installation script to default to x64
> Chocolatey: default installation to x64

- build/BuildSteps.cs
resolves #4493
This PR includes adding the contents of the `workers` directory for the inproc8 build,  specifically for the Logic Apps scenario when using core tools. We do not include the contents of the workers directory for minified versions.
> Including workers in inproc8 build

- release_notes.md
- src/Cli/func/Helpers/DotnetHelpers.cs
- test/Cli/Func.UnitTests/HelperTests/DotnetHelpersTests.cs
resolves #4399
Fix check for installed templates in the dotnet templates helper. We now check for the entire package name instead of just the prefix i.e. `Microsoft.Azure.Functions.Worker.ItemTemplates` and `Microsoft.Azure.Functions.Worker.ProjectTemplates`. Validated with local build & tests.
> Fix dotnet templates installation check

- release_notes.md
- src/Cli/func/Actions/LocalActions/InitAction.cs
> Default to .NET 8 for inproc

- src/Azure.Functions.Cli/Common/Utilities.cs
resolves #4460
Shims in `MinorVersionPrefix` of `6` or `8` (based on TFM) during `PrintVersion`. This is to handle versions of `WebJobs.Script.dll` which do not differentiate net6 and net8 version in its assembly.
> Shim in MinorVersionPrefix in PrintVersion

- release_notes.md
- src/Cli/func/Common/AppSettingsFile.cs
- src/Cli/func/Common/SecretsManager.cs
- src/Cli/func/NativeMethods/EnvironmentNativeMethods.cs
- test/Cli/Func.UnitTests/AppSettingsFileTests.cs
resolves #1401
- Warn if unable to parse local settings json due to json exception. Did not want to throw to avoid breaking behaviour
- Lazy init for AppSettingsFile as we do not need to read the local settings json every time we check the secrets.
- Minor fix to the SetEnvironmentVariable console log to include the key
> Warn on JsonException when parsing local.settings.json

- src/Cli/func/Actions/LocalActions/CreateFunctionAction.cs
n/a
Similar to other languages, display a default name for a new Function. Default name is based on the template name. Validated this works with both the in-proc and out-of-proc templates.
```log
> $testcli new -t HttpTrigger
Template: HttpTrigger
Function name: [HttpTrigger]
HttpTrigger
Creating dotnet function...
The template "HttpTrigger" was created successfully.
The function "HttpTrigger" was created successfully from the "HttpTrigger" template.
-----
> $testcli new
Select a number for template:
1. QueueTrigger
2. HttpTrigger
3. BlobTrigger
4. TimerTrigger
5. KafkaTrigger
6. KafkaOutput
7. DurableFunctionsOrchestration
8. SendGrid
9. EventHubTrigger
10. ServiceBusQueueTrigger
11. ServiceBusTopicTrigger
12. EventGridTrigger
13. EventGridCloudEventTrigger
14. CosmosDBTrigger
15. …
```
> Display a default function name for new dotnet functions

- .editorconfig
This pull request makes a minor update to the `.editorconfig` file to standardize file encoding settings across the project. The main change is the addition of a `charset = utf-8` (no BOM) setting for all files, replacing the previous `utf-8-bom` setting for code files.
I am **not** changing all files with this PR to avoid the churn and history mess. This will ensure the configuration is enforced as we continue to work on the repo. We can evaluate changes to other files if needed.
> Updating default file encoding configuration

- eng/scripts/generate-msi-files.ps1
Strip the preview suffix from the CLI version for MSI versioning as only x.x.x is supported.
This is only a temp fix as we are not releasing any preview MSI packages at the moment so there is no impact here but unblocking the CI in this branch. However, we should figure out a stratergy for MSI versioning when we have pre-release versions in future as semver is not supported.
> Temp fix for MSI version

- src/Cli/func/Common/SecretsManager.cs
resolves #4604
This is an unfortunate overlap with how the help command is designed today, and how the start action's args use customer options.
Unfortunately the way that the help action is designed today makes it so that we need to load an action to get it's arguements/options. So in a situation like this where you run `func` to see the commands, we run the StartAction.ParseArgs -> which inits the secret manager to get host options (if any) -> secret manager looks for local.settings.json -> that doesn't exist outside of a func app dir -> exception. 
This will all be reworked as part of our upcoming refactor, which will seperate these two things and cleanup the help command in general.
Updated `GetHostStartSettings` to catch the exception when local.settings.json does not exist and …
> Return HostStartSettings if local.settings.json is not loaded
