src/Azure.Functions.Cli/Actions/LocalActions/ListSettingsAction.cs

Added in description for settings -ShowValue to resolve null reference exception. Closes 113

Resolves Null Ref Error on settings. Closes 113

---

src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs

It doesn't work yet. all this will do is error.

Don't try to init Edge on non-Windows

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
src/Azure.Functions.Cli/Diagnostics/ConsoleLoggerFactoryBuilder.cs

@ahmelsayed I want to get better worker diagnostics in the console, this can help in the interim.

Add worker logs to cli output

---

.gitignore
src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs
src/Azure.Functions.Cli/Actions/LocalActions/RunFunctionAction.cs
src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
src/Azure.Functions.Cli/Common/StaticSettings.cs
src/Azure.Functions.Cli/Helpers/DebuggerHelper.cs

Enable node & java debugging on the cli

---

src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionApp.cs
src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
src/Azure.Functions.Cli/Common/SecretsManager.cs
src/Azure.Functions.Cli/Helpers/ScriptHostHelpers.cs

Alternate proposal to https://github.com/Azure/azure-functions-cli/pull/263

Add --script-root to func host start

---

README.md

dependency added

---

src/Azure.Functions.Cli/Actions/LocalActions/InstallExtensionAction.cs
src/Azure.Functions.Cli/Helpers/ExtensionsHelper.cs

Changing default output folder for extensions project file

---

src/Azure.Functions.Cli/Common/TemplatesManager.cs

Add missing $ in the template string

Add missing $ in the template string

---

src/Azure.Functions.Cli/npm/lib/install.js
src/Azure.Functions.Cli/npm/package-lock.json
src/Azure.Functions.Cli/npm/package.json

@ahmelsayed 
This PR improves the UX by adding a progress indicator when downloading `azure-functions-cli`

Added progress bar

---

README.md

Per Functions/CDA team meeting today to make this command more discoverable for Macs

Update readme to reflect installation for non-windows platforms

---

README.md

before command cannot install in macOS.
so fix.

Fix install command for non windows platform

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Addressing the issue reported by myself on [#397](https://github.com/Azure/azure-functions-core-tools/issues/397)

Fix ExtensionsProj.txt Logical Name

---

src/Azure.Functions.Cli/ConsoleApp.cs

the change is a little raw...though

add --version, #433

---

.nuget/NuGet.Config
src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Update Nuget feeds to consume appropriate packages 

---

src/Azure.Functions.Cli/Helpers/ExtensionsHelper.cs

Changing default extensions project location to app root

---

src/Azure.Functions.Cli/App.config
test/Azure.Functions.Cli.Tests/app.config

removed not-supported-by-net-core section from config, which prevented to start proxies

removed not-supported-by-net-core section from config

---

src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs

Workaround for https://github.com/Azure/azure-functions-host/issues/2894
More details: https://github.com/Microsoft/vscode-azurefunctions/issues/387

Inject language worker debug options as environment variables

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
src/Azure.Functions.Cli/npm/package.json

Updating version to ensure test verification passes.
@ahmelsayed is this your typical flow? Do you always bump this once you tag?

Updating version to 2.0.1-beta.29

---

src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
src/Azure.Functions.Cli/Actions/HostActions/WebHost/Security/CliAuthenticationHandler.cs

Adding handler for the ArmToken auth scheme

---

src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs

Update node debug key

---

src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs

display correct proxy endpoint

display correct proxy endpoint

---

README.md
src/Azure.Functions.Cli/Actions/DeployActions/DeployFunctionAction.cs
src/Azure.Functions.Cli/Actions/DeployActions/Platforms/KubernetesPlatform.cs
src/Azure.Functions.Cli/Actions/DeployActions/Platforms/Models/Kubernetes.cs
src/Azure.Functions.Cli/Actions/DeployActions/Platforms/PlatformFactory.cs

Adds Virtual Kubelet support to Functions deployed on Kubernetes

---

src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs

Incorrect Proxy Endpoint Shown
https://github.com/Azure/azure-functions-core-tools/issues/602

Incorrect Proxy Endpoint Shown

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Updating functions runtime bits and java worker bits

Azure functions v2.0.11961 release

---

src/Azure.Functions.Cli/Actions/LocalActions/CreateFunctionAction.cs
test/Azure.Functions.Cli.Tests/E2E/CreateFunctionTests.cs

Added a success message for creating Functions using Templates.

Fixes #614

---

src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs

https://github.com/Azure/azure-functions-core-tools/issues/639

v1 CLI shows proxy name instead of route

---

src/Azure.Functions.Cli/Actions/LocalActions/CreateFunctionAction.cs
src/Azure.Functions.Cli/Common/Utilities.cs
test/Azure.Functions.Cli.Tests/E2E/CreateFunctionTests.cs

Added sanitization when creating new dotnet functions using templates.

fixes #641

---

tools/python/packapp.py

Hide most of the output of python/packapp behind the --verbose flag

---

src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
src/Azure.Functions.Cli/Helpers/SecurityHelpers.cs

Added ability to create local certificates for https using openssl

Add ability to create certs locally

---

src/Azure.Functions.Cli/Extensions/ZipArchiveExtensions.cs

Update flags for opening files to add to the zip stream

---

src/Azure.Functions.Cli/Actions/AzureActions/ListFunctionsActions.cs
src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
src/Azure.Functions.Cli/Arm/Models/Site.cs
src/Azure.Functions.Cli/Helpers/AzureHelper.cs

Print the details of all the functions after publish is completed (including the key).

Fixes #678 - show func info after publish

---

src/Azure.Functions.Cli/Actions/DeployActions/DeployFunctionAction.cs
src/Azure.Functions.Cli/Exceptions/ImageNameFormatException.cs
src/Azure.Functions.Cli/Extensions/StringExtensions.cs
test/Azure.Functions.Cli.Tests/ExtensionsTests/StringExtensionsTests.cs

* Fix docker image generation #741 
* Add unit tests

Fix docker image name generation

---

src/Azure.Functions.Cli/Helpers/PythonHelpers.cs

A few questions/considerations regarding this PR-
1) In the change, we are detecting if venv directory is present in the current directory. So, this will not work if venv is submerged in some deep sub-directories, but that seems very unlikely.
2) The change takes in account that for some reason `.funcignore` may already be present. To keep things simple, it adds an empty line and then appends the `venv` to it. So, when the `.funcignore` does not exist, it has an empty line and then the venv. This is not breaking anything, but if it looks bad, I can make changes.

Fixes #794 - ignore venv when packing

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
src/Azure.Functions.Cli/Common/Constants.cs
src/Azure.Functions.Cli/npm/package.json
src/Azure.Functions.Cli/packages.config
test/Azure.Functions.Cli.Tests/Azure.Functions.Cli.Tests.csproj
test/Azure.Functions.Cli.Tests/packages.config

Updating core tools version and nugets

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Tons of good stuff inside :)
cc @pragnagopa @SteveL-MSFT @daxian-dbw @asavaritayal @soninaren

update PowerShell Worker Version

---

build.ps1
src/Azure.Functions.Cli/Actions/AzureActions/BaseAzureAction.cs
src/Azure.Functions.Cli/Common/CommandChecker.cs

This would allow users to have Azure PowerShell installed and not az CLI.
I've verified this on linux. Need to do proper testing and see if there's an opportunity for tests to be added.
cc @ahmelsayed @stevel-msft @daxian-dbw @asavaritayal @joeyaiello @Francisco-Gamino 
fixes https://github.com/Azure/azure-functions-core-tools/issues/840

Inital Azure Powershell support

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

NuGet package is already pushed.
No template updates are needed.
cc @ahmelsayed @daxian-dbw @pragnagopa @soninaren

Update powershell worker

---

build/Settings.cs
src/Azure.Functions.Cli/Helpers/PythonHelpers.cs

Updating CLI to latest versions of Python worker and library

Python public preview cli update

---

build/Settings.cs
src/Azure.Functions.Cli/Helpers/PythonHelpers.cs

This reverts commit 3a6c2a14e3db4d699cb4a94f192f52db1089c504.

Revert "Python public preview cli update"

---

src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs

Part 2 of this PR is to update the documentation as well.

Fixes #926 - incorrect description for --nozip

---

src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs

1. Should I retry if md5 mismatch fails?
2. Do we also need this for `/api/zipdeploy` or is that handled properly?

Fixes #920 - Verify md5

---

src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
src/Azure.Functions.Cli/Helpers/RetryHelper.cs

Fixes #962 - Add a retry logic to runfrompackage

---

src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs

Currently Core Tools sets the WEBSITE_HOSTNAME setting to `0.0.0.0` (the URL for the ASP.Net listener.) This causes extension webhook URLs starting with `http://0.0.0.0:{port}/` to be generated, which has led to some [downstream issues](https://github.com/Azure/azure-functions-durable-extension/issues/570) [(2)](https://github.com/Azure/azure-functions-durable-js/issues/28) in when running locally.

Pass base address (localhost) to WEBSITE_HOSTNAME setting.

---

src/Azure.Functions.Cli/Actions/AzureActions/LogStreamAction.cs

\cc @dariagrigoriu for appropriate message.

Fixes #953 - Linux Consumption log streaming error

---

src/Azure.Functions.Cli/Helpers/NetworkHelpers.cs
test/Azure.Functions.Cli.Tests/E2E/Helpers/CliTester.cs
test/Azure.Functions.Cli.Tests/E2E/StartTests.cs

Closes #907 
Closes #956 
Tested on Windows and Linux. I'm having issues with WSL. I'll try on a different machine.

simplify check for available port

---

src/Azure.Functions.Cli/Helpers/WorkerRuntimeLanguageHelper.cs

Hide Java from func init command

---

src/Azure.Functions.Cli/Common/Constants.cs

Quick test in progress. Will update once completed.
UPDATE: Tested, works fine.

Update docker version to use the one with new worker

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

https://github.com/Azure/azure-functions-host/releases/tag/v2.0.12303

Azure Functions Runtime 2.0.12303

---

src/Azure.Functions.Cli/Common/Executable.cs
src/Azure.Functions.Cli/Extensions/ProcessExtensions.cs
test/Azure.Functions.Cli.Tests/ExtensionsTests/ProcessExtensionsTests.cs

Register process event handlers before launching the process.

---

src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs

To be consistent with naming, created this PR.
[Reference](https://github.com/Azure/app-service-announcements/issues/84)

Rename Zip to Package in Publish

---

build.ps1
build/BuildSteps.cs
build/FileHelpers.cs
build/OrchestratorParser.cs
build/Program.cs
build/Settings.cs

The signing job is only for master branch right now.
~~@ahmelsayed, we also need to add the connection string in Appveyor.~~ Thanks Ahmed!

Fixes #1038 - Sign the Core tools binaries

---

build/Orchestrator.cs

Might be a good idea to not show build steps that are skipped.

Do not show skipped build steps

---

src/Azure.Functions.Cli/StaticResources/profile.ps1

which has been fixed in 1.2 of Azure PowerShell which I've confirmed in West US 2.

Update to `-Identity`

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Note - downgrade from @pragnagopa 's changes that are for the next release

Update host, node worker, java worker, to be v2.0.12309

---

src/Azure.Functions.Cli/Actions/DeployActions/Platforms/Models/FunctionJson.cs
src/Azure.Functions.Cli/Actions/LocalActions/CreateFunctionAction.cs
src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs
src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
src/Azure.Functions.Cli/Common/Constants.cs
src/Azure.Functions.Cli/Helpers/WorkerRuntimeLanguageHelper.cs
src/Azure.Functions.Cli/StaticResources/StaticResources.cs
src/Azure.Functions.Cli/StaticResources/funcignore
src/Azure.Functions.Cli/StaticResources/package.json
src/Azure.Functions.Cli/StaticResources/tsconfig.json
test/Azure.Functions.Cli.Tests/E2E/CreateFunctionTests.cs
test/Azure.Functions.Cli.Tests/E2E/InitTests.cs

~~I still need to test properly and add a couple of e2e.~~
UPDATE: Added E2E tests. This should be ready to go.
But, wanted to get feedback on the changes while I do that.
Closes #1037

Add typescript options

---

src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs

Required for testing auth scenarios locally, both in our end-to-end testing on language workers and by users.
@paulbatum 🍰

Added flag to enable full host auth handling pipeline.

---

build/BuildSteps.cs
build/Settings.cs
src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Removing the venv and related changes will come in as a separate PR once this is in.

Consume python worker from a nuget package

---

build/BuildSteps.cs
build/Program.cs
build/Settings.cs
build/Shell.cs

I have skipped checking these ["aspnetcorev2_inprocess.dll","Microsoft.AspNetCore.Buffering.dll","Microsoft.AspNetCore.Server.IIS.dll"] files as they aren't directly ours and sometimes appear to be unsigned. 
Let me know if @fabiocav / @ahmelsayed think we should sign these guys too.

Fixes #1089 - Run sigcheck.exe check post build

---

src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs
src/Azure.Functions.Cli/Common/Constants.cs
src/Azure.Functions.Cli/Common/FileSystemHelpers.cs
src/Azure.Functions.Cli/Helpers/PythonHelpers.cs
src/Azure.Functions.Cli/StaticResources/python_bundle_script.py
src/Azure.Functions.Cli/StaticResources/python_docker_build.sh
test/Azure.Functions.Cli.Tests/E2E/InitTests.cs

DO NOT MERGE
Need to run some tests on the artifacts by appveyor. And this is dependent on python worker to be consumed as nuget package to be finished. Closes #1023

Remove venv from basic publishing path

---

src/Azure.Functions.Cli/Common/Constants.cs

Automatically install SignalR Service bindings

Add SignalR Service extension to package map

---

src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
src/Azure.Functions.Cli/Arm/ArmClient.cs
src/Azure.Functions.Cli/Common/Constants.cs

Add User-Agent to zipdeploy calls

---

src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs
test/Azure.Functions.Cli.Tests/E2E/InitTests.cs

Add --docker-only to init command

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

* Enabled Managed Dependencies feature - to install function app dependencies via requirements.psd1
* Enabled tiered compilation for the worker to help the cold start
* Enhanced Push-OutputBinding by using the output binding information
* System logging improvements
For more information, please see https://github.com/Azure/azure-functions-powershell-worker/releases

Update PowerShell worker to 0.1.81-preview. 

---

src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
src/Azure.Functions.Cli/Actions/LocalActions/PackAction.cs
src/Azure.Functions.Cli/Helpers/ZipHelper.cs

Fixes #1117: --no-build support

---

src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs

Skip extensions restore for csproj dotnet apps

---

appveyor.yml
src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
src/Azure.Functions.Cli/Helpers/PythonHelpers.cs
src/Azure.Functions.Cli/Helpers/SecurityHelpers.cs
test/Azure.Functions.Cli.Tests/E2E/Helpers/CliTester.cs
test/Azure.Functions.Cli.Tests/E2E/Helpers/RunConfiguration.cs
test/Azure.Functions.Cli.Tests/E2E/PackFunctionTests.cs

@ahmelsayed do you think I should also check and add the file `.python_packages/requirements.txt.md5` I am creating to `.funcignore`?
@asavaritayal, ~~I called the flag to force update `--force-sync`. Let me know if you have a better name.~~ On Asavari's suggestion, I have removed the flag to force update.
This needs a doc update. And this should be the last item for changing the Python publishing workflow for now.

Fixes #1118 - Reuse build artifacts

---

src/Azure.Functions.Cli/npm/lib/install.js

This might be the most important PR submitted on GitHub in 2019.

Fix capitalization of "CLI" in NPM install script

---

src/Azure.Functions.Cli/Common/FileSystemHelpers.cs

Stop ignoring "appsettings.json"

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

The major changes in this release are:
* Updating Managed Dependencies folder installation path for local development.

Update PowerShell worker to 0.1.95-preview.

---

src/Azure.Functions.Cli/Helpers/DotnetHelpers.cs
test/Azure.Functions.Cli.Tests/E2E/InitTests.cs

Set AzureFunctionsVersion to v2 in csproj

---

src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs
src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
src/Azure.Functions.Cli/StaticResources/StaticResources.cs
src/Azure.Functions.Cli/StaticResources/javascriptPackage.json
src/Azure.Functions.Cli/StaticResources/package.json
test/Azure.Functions.Cli.Tests/E2E/InitTests.cs

Resolves https://github.com/Azure/azure-functions-core-tools/issues/1171 and resolves https://github.com/Azure/azure-functions-core-tools/issues/1169

Package json fixes

---

src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
src/Azure.Functions.Cli/Arm/Models/Site.cs

Run from package as default

---

src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs

Fixes #1217 - Elastic Premium issues

---

src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs

I made the same change to Kudu a while ago (see https://github.com/projectkudu/kudu/pull/2940). Details on why this change is needed are in that linked PR.
I checked the Portal code [here](https://github.com/Azure/azure-functions-ux/blob/205f8e7705c61e6920ffa5e9062da3e81d0ebb84/client/src/app/shared/services/function-app.service.ts#L774) and it doesn't seem to be doing any SKU filtering.

SyncTriggers regardless of SKU

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
src/Azure.Functions.Cli/Helpers/PythonHelpers.cs

Waiting on https://github.com/Azure/azure-functions-docker/pull/98 to get merged and a new Docker image to get pushed out before updating the Docker image which this core tools is pinned to.

Update Python versions

---

src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
test/Azure.Functions.Cli.Tests/E2E/StartTests.cs

Handle empty settings in local.setting.json

---

src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
src/Azure.Functions.Cli/Helpers/PythonHelpers.cs

Fixes #1229 - Python version resolutions

---

test/Azure.Functions.Cli.Tests/E2E/StartTests.cs

Adding end to end test case for PowerShell to validate func init, new, and start.

Add end to end test case for PowerShell to validate func init, new, and start.

---

src/Azure.Functions.Cli/Helpers/PythonHelpers.cs

Fix issue with packapp using python when python3

---

src/Azure.Functions.Cli/Common/Constants.cs

Adding twiliosms to BindingPackageMap

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
src/Azure.Functions.Cli/Common/Constants.cs
src/Azure.Functions.Cli/npm/package.json
src/Azure.Functions.Cli/packages.config
test/Azure.Functions.Cli.Tests/Azure.Functions.Cli.Tests.csproj
test/Azure.Functions.Cli.Tests/packages.config

I ran `packageConfigParser` as well as `redirectCompare`.
I didn't get any updates to other extensions.

V1 host v1.12491 release

---

src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs

This is core-tools work item to support https://github.com/Azure/azure-functions-core-tools/issues/1069.
Unfortunately, I can't enable Run From Package for Linux dedicated yet. Will do that after ANT83, when the kudulite fix is deployed.
Already making this PR as it's useful for Windows cases as well to avoid race conditions, which I suspect some users might be hitting. And after this, Linux RunFromPackage support for core-tools would only need a minor change.

Add poll logic for kudu env settings

---

src/Azure.Functions.Cli/Actions/LocalActions/InstallExtensionAction.cs
src/Azure.Functions.Cli/Common/Constants.cs
src/Azure.Functions.Cli/ExtensionBundle/JsonFileConfigurationSource.cs
src/Azure.Functions.Cli/Helpers/ExtensionsHelper.cs
test/Azure.Functions.Cli.Tests/ExtensionsTests/InstallExtensionsTests.cs

Need to verify `ExtensionsMetadataGeneratorPackage` with @soninaren, and need to ensure i didn't break extensions commands' expectations.

Fixes #688 - Extensions Install should only update if needed

---

src/Azure.Functions.Cli/Actions/AzureActions/AddStorageAccountSettingAction.cs
src/Azure.Functions.Cli/Actions/AzureActions/BaseAzureAction.cs
src/Azure.Functions.Cli/Actions/AzureActions/FetchAppSettingsAction.cs
src/Azure.Functions.Cli/Actions/AzureActions/ListFunctionsActions.cs
src/Azure.Functions.Cli/Actions/AzureActions/LogStreamAction.cs
src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
src/Azure.Functions.Cli/Arm/ArmUriTemplates.cs
src/Azure.Functions.Cli/Common/Constants.cs
src/Azure.Functions.Cli/Helpers/AzureHelper.cs
test/Azure.Functions.Cli.Tests/E2E/ListFunctionsTests.cs

I am yet to test this thoroughly, to make sure all functionality is still fine. Still wanted to make the PR in case you had feedback, while I try and get testing environments.
I did not add getting management URL from powershell yet. If this looks good, let me know, I will have to figure out how to retrieve this same info from powershell.

Fixes #931 - Add support for other clouds

---

src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs

Fixes #1212 
Changed from 
```
Preparing archive...
Settings must be of the form "name=value".
Retry: 1 of 3
Settings must be of the form "name=value".
Retry: 2 of 3
Settings must be of the form "name=value".
Retry: 3 of 3
Settings must be of the form "name=value".
```
To 
```
Preparing archive...
Error creating a Blob container reference. Please make sure your connection string in "AzureWebJobsStorage" is valid
Retry: 1 of 3
Error creating a Blob container reference. Please make sure your connection string in "AzureWebJobsStorage" is valid
Retry: 2 of 3
Error creating a Blob container reference. Please make sure your connection string in "AzureWebJobsStorage" is valid
Retry: 3 of 3
Error creating a Blob container reference. Please make sure your connection string in "AzureWebJobsStorage" …
```

Better surface error if issue arised with storage account

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

https://github.com/Azure/azure-functions-host/releases/tag/2.0.12493

Update to Functions 2.0.12493

---

src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs

Fixes #1335 
An example would be-

Add logging for kudu builds

---

src/Azure.Functions.Cli/Actions/AzureActions/LogStreamAction.cs
src/Azure.Functions.Cli/Arm/ArmUriTemplates.cs
src/Azure.Functions.Cli/Arm/Models/ArgResponse.cs
src/Azure.Functions.Cli/Arm/Models/ArmResourceId.cs
src/Azure.Functions.Cli/Common/Utilities.cs
src/Azure.Functions.Cli/Helpers/AzureHelper.cs

Fixes #1334 
Works well in Windows. Will test Mac and Linux once build is done.

Add ability to open appinsight live metrics in a browser

---

src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
src/Azure.Functions.Cli/Common/Utilities.cs
src/Azure.Functions.Cli/Helpers/PythonHelpers.cs
test/Azure.Functions.Cli.Tests/E2E/InitTests.cs

Will test out on different python binaries once the build is complete.
Closes #1327

Detect all Python versions, and do not fail unless needed

---

src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Fixes https://github.com/Azure/azure-functions-host/issues/4458.
Relies on https://github.com/Azure/azure-functions-host/pull/4560.

throwing if invalid dependencies are detected

---

src/Azure.Functions.Cli/ExtensionBundle/JsonFileConfigurationSource.cs

Removing duplicate code for ConfigurationSource

---

src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs

Needed to fix https://github.com/Azure/azure-functions-python-worker/issues/434.

Flip priority of user and system dependencies

---

src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
src/Azure.Functions.Cli/NativeMethods/EnvironmentNativeMethods.cs
test/Azure.Functions.Cli.Tests/E2E/StartTests.cs

Allow empty string env var value on Windows

---

src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
test/Azure.Functions.Cli.Tests/E2E/StartTests.cs

Add --functions option to StartAction.

---

src/Azure.Functions.Cli/npm/lib/copy-metadata.js
src/Azure.Functions.Cli/npm/package.json

Add hook for README update during publish

---

README.md

I think it's not a good idea to suggest installing v1

Don't suggest to install v1

---

src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs

Check that dotnet is installed as a prerequisite for PowerShell function apps (in func start). 
This fixes #1410

Check that dotnet is installed as a prerequisite for PowerShell function apps (in func start).

---

src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs

As per https://github.com/Azure/azure-cli/issues/9027
We should remove WEBSITE_CONTENTAZUREFILECONNECTIONSTRING and WEBSITE_CONTENTSHARE in functionapp appsettings.
These two settings are set by default when user creating a function app with **Azure CLI < 2.0.65**
To allow these old function apps to use our server side build, we should remove these settings beforehand.
Otherwise, the SCM worker in Linux Consumption is not going to start.

Remove WEBSITE_CONTENTSHARE for Linux Consumption server side build

---

src/Azure.Functions.Cli/Helpers/GlobalCoreToolsSettings.cs
test/Azure.Functions.Cli.Tests/E2E/InitTests.cs

Ran into this typo because the language couldn't be determined.

Minor typo in error

---

src/Azure.Functions.Cli/Common/OutputTheme.cs
src/Azure.Functions.Cli/Helpers/GlobalCoreToolsSettings.cs
test/Azure.Functions.Cli.Tests/E2E/InitTests.cs

Don't make unknown worker runtime a fatal error

---

src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs

Listen to Any interface when setting up https

---

src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
src/Azure.Functions.Cli/Common/Constants.cs
src/Azure.Functions.Cli/Extensions/DictionaryExtensions.cs
src/Azure.Functions.Cli/Helpers/KuduLiteDeploymentHelpers.cs
src/Azure.Functions.Cli/Helpers/PythonHelpers.cs
src/Azure.Functions.Cli/Helpers/ZipHelper.cs

Add Dedicated Linux Remote Build

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Updating the PowerShellWorker again as discussed

Update PowerShellWorker to 0.1.152-preview

---

src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
tools/python/packapp/__main__.py

We add a description for --build flag

Add help description for remote build

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

/+ update to Powershell worker

Azure Functions Host v2.0.12641 release

---

src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
src/Azure.Functions.Cli/Helpers/WorkerRuntimeLanguageHelper.cs

This has already been released. But, we need to merge to dev and master later too

Hot fix python

---

src/Azure.Functions.Cli/Helpers/KuduLiteDeploymentHelpers.cs

Fixes #1510 
with ANT 84, kudulite's `/api/isdeploying` returns a JSON response with multiple elements, some of which are not boolean. We should only extract and parse to boolean what we know for to be boolean.

Fix dedicated linux build tiny bug

---

src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs

Fixes #1509 
Add request ID for better debugging.

Add request ID to sync triggers call

---

src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs

Fixes #1542 
I also simplified the logic in `WaitForAppSettingUpdateSCM` as it got super messy.
Adding `--nozip` also helps with having a safe flag to turn off the new Run From Package default on Linux Dedicated.

Fix --nozip Linux Dedicated and simply polling logic

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Service Bus change: https://github.com/Azure/azure-functions-python-library/pull/26

Update NuGet - includes service bus update

---

src/Azure.Functions.Cli/Helpers/KuduLiteDeploymentHelpers.cs

This PR depends on the following PR, please merge afterwards:
https://github.com/Azure/azure-functions-core-tools/pull/1561
Backgrounds:
The oryx build process has inner log which can be extracted. This includes detail steps such as **pip install** and **npm install**.
This information should be valuable for customer to debug dependency resolution issues.

Remote Build: print details log during oryx build

---

src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs
src/Azure.Functions.Cli/StaticResources/requirements.psd1

This PR contains the following:
* Updating requirements.psd1 template content
* Updated/simplified logic to generate requirements.psd1

Managed Dependencies update for PowerShell

---

src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs
src/Azure.Functions.Cli/Helpers/WorkerRuntimeLanguageHelper.cs

Remove preview flag from PowerShell.

Remove preview flag from PowerShell

---

src/Azure.Functions.Cli/StaticResources/Dockerfile.csx.dotnet
src/Azure.Functions.Cli/StaticResources/Dockerfile.dotnet
src/Azure.Functions.Cli/StaticResources/Dockerfile.node
src/Azure.Functions.Cli/StaticResources/Dockerfile.powershell
src/Azure.Functions.Cli/StaticResources/Dockerfile.python

Add appservice image references to dockerfiles

---

src/Azure.Functions.Cli/Common/WorkerLanguageVersionInfo.cs
src/Azure.Functions.Cli/Helpers/PythonHelpers.cs
test/Azure.Functions.Cli.Tests/PythonHelperTests.cs

Update **PythonHelper** **ValidatePythonVersion** to extract python version info from a local devbox in a more organized way.
This also benefits my upcoming PR to generate different Dockerfile depends on different python versions.
Feedbacks are welcome.

Refactor worker version extractor

---

build/BuildSteps.cs
build/Program.cs
src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs
src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
src/Azure.Functions.Cli/Common/Constants.cs
src/Azure.Functions.Cli/Common/WorkerLanguageVersionInfo.cs
src/Azure.Functions.Cli/ExtensionBundle/ExtensionBundleConfigurationBuilder.cs
src/Azure.Functions.Cli/Helpers/PythonHelpers.cs
test/Azure.Functions.Cli.Tests/E2E/InitTests.cs
test/Azure.Functions.Cli.Tests/PythonHelperTests.cs

Will make another PR to check and warn user when publishing environment does not match local environment (in terms of language version). 
Need to test it before merge
Closes #1534

Allow Python 3.7 to run locally

---

src/Azure.Functions.Cli/StaticResources/Dockerfile.java

Creating Java docker for support the core tools, for future use.

-Add the Dockerfile java file

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

- Added experimental support for the [Function Chaining pattern](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-overview#chaining) (Durable Functions).
**Please note: this implementation is incomplete, has known limitations, and the programming model will change soon, so avoid using enabling Durable PowerShell Functions in production!**
For more information, please see https://github.com/Azure/azure-functions-powershell-worker/releases/tag/v1.0.197.

Update PowerShellWorker to v1.0.197

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Corresponding worker change: https://github.com/Azure/azure-functions-python-worker/pull/570
Release Note: https://github.com/Azure/azure-functions-python-worker/releases/tag/1.0.1

Update Python worker with local debugging fixes

---

src/Azure.Functions.Cli/Common/Constants.cs
src/Azure.Functions.Cli/Common/StaticSettings.cs
src/Azure.Functions.Cli/Helpers/TelemetryHelpers.cs

Part of work for https://github.com/Azure/azure-functions-core-tools/issues/1574
Pending other parts once this is in.

Add telemetry to be enabled via file

---

azure-pipelines.yml
build/BuildSteps.cs
src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs
test/Azure.Functions.Cli.Tests/ExtensionsTests/ExtensionBundleTests.cs
test/Azure.Functions.Cli.Tests/ExtensionsTests/InstallExtensionsTests.cs

Add extension bundle config by default, publish test results

Add extension bundle config by default, publish test results

---

src/Azure.Functions.Cli/Diagnostics/ColoredConsoleLogger.cs

Rebasing #1558 for @aaronpowell to get this merged.

Fixing #1557 by checking for debug mode and unpacking the exception if it is debug mode

---

.github/lock.yml

Using https://github.com/apps/lock 
/cc @fabiocav @ankitkumarr @ahmedelnably

Auto lock closed issues

---

build/Settings.cs
src/Azure.Functions.Cli/Common/Constants.cs
src/Azure.Functions.Cli/ExtensionBundle/ExtensionBundleHelper.cs
src/Azure.Functions.Cli/Helpers/PythonHelpers.cs
src/Azure.Functions.Cli/Helpers/ZipHelper.cs

Need to test it in all environments and make sure that permissions are actually preserved.
Also need to chmod +x gozip in all installers

Use go zip to preseve file permissions

---

src/Azure.Functions.Cli/Common/GitIgnoreParser.cs
test/Azure.Functions.Cli.Tests/GitIgnoreParserTests.cs

Fixed .funcignore parser to ignore files/directories based on an exact match rather than on contains

---

src/Azure.Functions.Cli/Actions/AzureActions/FetchAppSettingsAction.cs
src/Azure.Functions.Cli/Actions/AzureActions/ListFunctionsActions.cs
src/Azure.Functions.Cli/Actions/AzureActions/LogStreamAction.cs
src/Azure.Functions.Cli/Arm/Models/ArmSubscriptionsArray.cs
src/Azure.Functions.Cli/Helpers/AzureHelper.cs

Fixes https://github.com/Azure/azure-functions-core-tools/issues/1724

Fix bug when too many subscriptions are available

---

src/Azure.Functions.Cli/Common/Constants.cs
src/Azure.Functions.Cli/StaticResources/ExtensionsProj.csproj.template

updating packages for function extension install command

---

src/Azure.Functions.Cli/Actions/LocalActions/CreateFunctionAction.cs
src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs
src/Azure.Functions.Cli/Helpers/SelectionMenuHelper.cs

Changing selection menu prompt to be platform specific.

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

https://github.com/Azure/azure-functions-python-worker/releases/tag/1.0.3

[Pack] Update Python Worker to 1.0.3 for v3

---

src/Azure.Functions.Cli/Actions/LocalActions/InstallExtensionAction.cs
src/Azure.Functions.Cli/Common/Constants.cs
test/Azure.Functions.Cli.Tests/ExtensionsTests/InstallExtensionsTests.cs

Extensions install will fetch latest version if not specified.

---

src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
test/Azure.Functions.Cli.Tests/ActionsTests/StartHostActionTests.cs

Add flag to skip AzureWebJobsStorage check.

---

build.ps1
build/BuildSteps.cs
build/Settings.cs
src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

PowerShell worker release notes:
- https://github.com/Azure/azure-functions-powershell-worker/releases/tag/v3.0.235
- https://github.com/Azure/azure-functions-powershell-worker/releases/tag/v3.0.237

Update PowerShellWorker versions to 3.0.235 (PS6) and 3.0.237 (PS7)

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

PowerShell worker release notes: https://github.com/Azure/azure-functions-powershell-worker/releases/tag/v2.0.240

Update PowerShellWorker version to 2.0.240

---

src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
src/Azure.Functions.Cli/Common/Constants.cs

Display AZURE_FUNCTIONS_ENVIRONMENT and set ASPNETCORE_ENVIRONMENT

---

azure-pipelines.yml

[Build MSI] Fixing build script's argument passing.

---

src/Azure.Functions.Cli/StaticResources/host.json
test/Azure.Functions.Cli.Tests/E2E/InitTests.cs

related issue https://github.com/Azure/azure-functions-templates/issues/906

disabling sampling of requests in default host.json

---

src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
src/Azure.Functions.Cli/Common/Constants.cs
test/Azure.Functions.Cli.Tests/E2E/StartTests.cs

Check if bundle config exists, hostJson exists

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

https://github.com/Azure/azure-functions-python-worker/releases/tag/1.1.0

[pack] Update Python worker to 1.1.0

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
src/Azure.Functions.Cli/Helpers/ZipHelper.cs

We should no longer need this.

Remove DotNetZip

---

src/Azure.Functions.Cli/npm/npm-shrinkwrap.json
src/Azure.Functions.Cli/npm/package.json

Update npm dependencies

---

src/Azure.Functions.Cli/Helpers/ZipHelper.cs

Fixes https://github.com/Azure/azure-functions-core-tools/issues/1867
Need to also cherry-pick in v3

Fix zip command to work with spaced paths

---

src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs

Cherry-pick of https://github.com/Azure/azure-functions-core-tools/pull/1951

Fixed issue where AzureWebJobsStorage wasn't being properly set in local.settings.json

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Reverts Azure/azure-functions-core-tools#1953

Revert "Update java worker release to 1.6.0"

---

.nuget/NuGet.Config
NuGet.Config
build/BuildSteps.cs
src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

PowerShell worker release notes: https://github.com/Azure/azure-functions-powershell-worker/releases/tag/v2.0.281

Update PowerShellWorker to v2.0.281

---

src/Azure.Functions.Cli/Helpers/PythonHelpers.cs

Resolves https://github.com/Azure/azure-functions-core-tools/issues/1979

Update error message recommendation for python version

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Release info: https://github.com/Azure/azure-functions-python-worker/releases/tag/1.1.1
Myget release: https://azfunc.visualstudio.com/Azure%20Functions%20Python/_releaseProgress?_a=release-environment-logs&releaseId=229&environmentId=229

[pack] Updating V3 Python Worker version

---

src/Azure.Functions.Cli/Actions/LocalActions/CreateFunctionAction.cs
src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs
test/Azure.Functions.Cli.Tests/E2E/CreateFunctionTests.cs

func new will now run init if the proper files are not present

---

azure-pipelines.yml

Fixes https://github.com/Azure/azure-functions-core-tools/issues/2087

Fix pipelines build

---

README.md

Added Version3 Azure functions core tools instruction for windows

Version 3 Azure functions instruction

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

https://github.com/Azure/azure-functions-python-worker/releases/tag/1.1.3

[pack] Update Python worker to 1.1.4 v2

---

README.md

Also list v3 instructions ahead of v2
Resolves #2076 
/cc @ankitkumarr

Add MSI instructions

---

src/Azure.Functions.Cli/Actions/LocalActions/CreateFunctionAction.cs
src/Azure.Functions.Cli/Common/Constants.cs
src/Azure.Functions.Cli/Common/ExtensionPackage.cs
src/Azure.Functions.Cli/Helpers/DotnetHelpers.cs
test/Azure.Functions.Cli.Tests/E2E/CreateFunctionTests.cs

Adding AuthLevel to HttpTrigger

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

PowerShell worker release notes:
* https://github.com/Azure/azure-functions-powershell-worker/releases/tag/v3.0.291
* https://github.com/Azure/azure-functions-powershell-worker/releases/tag/v3.0.293

Upgrade PowerShellWorker to 3.0.291 and 3.0.293

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Reverts Azure/azure-functions-core-tools#2113

Revert "Upgrade PowerShellWorker to 3.0.291 and 3.0.293"

---

build/Settings.cs
src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs
src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
src/Azure.Functions.Cli/Common/Constants.cs
src/Azure.Functions.Cli/Common/TemplatesManager.cs
src/Azure.Functions.Cli/Extensions/StringExtensions.cs
src/Azure.Functions.Cli/Helpers/GlobalCoreToolsSettings.cs
src/Azure.Functions.Cli/Helpers/LanguageWorkerHelper.cs
src/Azure.Functions.Cli/Helpers/WorkerRuntimeLanguageHelper.cs
src/Azure.Functions.Cli/StaticResources/Dockerfile.custom
src/Azure.Functions.Cli/StaticResources/StaticResources.cs
src/Azure.Functions.Cli/StaticResources/customHandler.json
src/Azure.Functions.Cli/StaticResources/customHandlerConfig.json
test/Azure.Functions.Cli.Tests/E2E/CreateFunctionTests.cs

Fixes #2052 
Corresponding template PR: https://github.com/Azure/azure-functions-templates/pull/964. Currently blocked until template is released which is tracked by this work item https://github.com/Azure/azure-functions-templates/issues/965.

func init and new for custom handlers

---

src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
src/Azure.Functions.Cli/Actions/HostActions/Startup.cs
src/Azure.Functions.Cli/Common/Utilities.cs
src/Azure.Functions.Cli/Diagnostics/ColoredConsoleLogger.cs
src/Azure.Functions.Cli/Diagnostics/ColoredConsoleLoggerProvider.cs
src/Azure.Functions.Cli/Diagnostics/LoggingBuilder.cs

Force log-white listed logs

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

PowerShell worker release notes: https://github.com/Azure/azure-functions-powershell-worker/releases/tag/v2.0.292

Upgrade PowerShellWorker to 2.0.292

---

src/Azure.Functions.Cli/Actions/AzureActions/BaseAzureAction.cs
src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
src/Azure.Functions.Cli/Actions/HelpAction.cs
src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
src/Azure.Functions.Cli/Actions/LocalActions/PackAction.cs
src/Azure.Functions.Cli/Common/DurableManager.cs
src/Azure.Functions.Cli/Common/OutputTheme.cs
src/Azure.Functions.Cli/Helpers/PythonHelpers.cs
src/Azure.Functions.Cli/Helpers/SecurityHelpers.cs
src/Azure.Functions.Cli/Helpers/ZipHelper.cs

Fixes #2069. Making most of the colors to the darker shade to make it visible in both light and dark backgrounds. I modified the theme, but also places with random colors that weren't really following the theme.
I think this should at least solve the P1 issue to make things legible.
Here's some before and after pictures -
**Before**
**After**
**Before**
**After**
**Before**
**After**

Change colors to be more accessible

---

test/Azure.Functions.Cli.Tests/E2E/StartTests.cs

Moving from V2 - https://github.com/Azure/azure-functions-core-tools/pull/2166

Fix powershell test

---

src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
src/Azure.Functions.Cli/Actions/HostActions/Startup.cs
src/Azure.Functions.Cli/Common/DisplayFunctionsInfoUtilities.cs
src/Azure.Functions.Cli/Common/Utilities.cs
src/Azure.Functions.Cli/Diagnostics/ColoredConsoleLogger.cs
src/Azure.Functions.Cli/Diagnostics/ColoredConsoleLoggerProvider.cs
src/Azure.Functions.Cli/Diagnostics/LoggingBuilder.cs
src/Azure.Functions.Cli/Diagnostics/LoggingFilterHelper.cs
src/Azure.Functions.Cli/ExtensionBundle/ExtensionBundleHelper.cs
test/Azure.Functions.Cli.Tests/ColoredConsoleLoggerTests.cs
test/Azure.Functions.Cli.Tests/E2E/StartTests.cs
test/Azure.Functions.Cli.Tests/LoggingFilterHelperTests.cs
test/Azure.Functions.Cli.Tests/UtilitiesTests.cs

porting commit # 1050abb9978a81de9c710cdb85ed4f0b7d0835cc

[V2]Less verbose logs on func start

---

src/Azure.Functions.Cli/Common/Utilities.cs

Fix null ref when debugging from VS

---

src/Azure.Functions.Cli/Common/Utilities.cs

Port commit 04b0445fd5def6f3c80d04f190402595cb195ac3

Fix null ref when debugging from VS (#2186)

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Updating in preparation of release: https://github.com/Azure/azure-functions-host/releases/tag/v3.0.14492
https://github.com/Azure/azure-functions-host/blob/v3.0.14492/src/WebJobs.Script/WebJobs.Script.csproj

Updating WebHost to 3.0.14492

---

src/Azure.Functions.Cli/Common/Utilities.cs
src/Azure.Functions.Cli/Helpers/GlobalCoreToolsSettings.cs

port # 135d489f0a5e755671f8b53e90d5f7916999df14

Filter ConsoleLogs from user code as function logs

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
src/Azure.Functions.Cli/Common/Constants.cs
src/Azure.Functions.Cli/npm/package.json
src/Azure.Functions.Cli/packages.config
test/Azure.Functions.Cli.Tests/Azure.Functions.Cli.Tests.csproj
test/Azure.Functions.Cli.Tests/packages.config

@yojagad 's commit from -- https://github.com/Azure/azure-functions-core-tools/pull/2153.
Had to pull it here to do some tests and fix the build.

Update v1 Host to 1.0.13146

---

src/Azure.Functions.Cli/Actions/LocalActions/CreateFunctionAction.cs
src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs
test/Azure.Functions.Cli.Tests/E2E/CreateFunctionTests.cs

func new will now run init if the proper files have not already been created for the function app.

---

src/Azure.Functions.Cli/Diagnostics/ColoredConsoleLogger.cs
src/Azure.Functions.Cli/Diagnostics/LoggingFilterHelper.cs
test/Azure.Functions.Cli.Tests/E2E/StartTests.cs
test/Azure.Functions.Cli.Tests/LoggingFilterHelperTests.cs
test/Azure.Functions.Cli.Tests/TestUtils.cs
test/Azure.Functions.Cli.Tests/UtilitiesTests.cs

Fixes #2174 
- Re-enable tests
- Minor fix to date time format

[Logging]Fix DateTime format, enable tests

---

src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs

Porting https://github.com/Azure/azure-functions-core-tools/pull/2241 to V3

throw error when using unsupported build flag (#2241)

---

build/BuildSteps.cs
src/Azure.Functions.Cli/Common/Utilities.cs
src/Azure.Functions.Cli/Program.cs

Adding v2 upgrade warning.

---

NuGet.Config
build.ps1
build/BuildSteps.cs
build/IntegrationTestBuildManifest.cs
build/Program.cs
build/Settings.cs
build/uploadContentToStorageAccount.ps1
src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

This PR contains the following:
* Updated the Core Tools build to support building for ingratiation tests. This mode can be set by populating the environment variable `$env:INTEGRATIONBUILDNUMBER`, e.g., `$env:INTEGRATIONBUILDNUMBER = "PreRelease20200904"`. 
When running in this mode, we download a list of nutget packages that need to be updated from https://raw.githubusercontent.com/Azure/azure-functions-integration-tests/dev/integrationTestsBuild/V3/CoreToolsBuild.json. The nuget packages are pulled from our internal `AzureFunctionsPreRelease` feed and get added via `dotnet add package <packageName> -v <packageVersion> -s <internalFeedName> --no-restore`. After building the Core Tools, we create a `integrationTestBuildManifest.json` file with the build information.
Here is what the file …

Enable building the Core Tools for integration tests.

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
test/Azure.Functions.Cli.Tests/E2E/DurableTests.cs
test/Azure.Functions.Cli.Tests/E2E/StartTests.cs

Part of the Functions host 3.0.156065 release. (Updated for 3.0.15149 hotfix.)

Update Microsoft.Azure.WebJobs.Script.WebHost reference to 3.0.15149.

---

appveyor.yml
azure-pipelines.yml
build/BuildSteps.cs
build/Program.cs
src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Update to pipeline also required.

Expose Core Tools as a .NET Core Tool. Resolves #2071

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

https://github.com/Azure/azure-functions-host/releases/tag/v3.0.15185

Update Functions Host to 3.0.15185

---

build/BuildSteps.cs

revert to exisiting way of removing workers

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Updating WebHost reference to 3.0.15352 for new host release.

Update WebHost to 3.0.15352

---

azure-pipelines.yml

need to extend build timeout to pass build on release_3.0(60minutes by default)

Adding timeoutInMinutes

---

src/Azure.Functions.Cli/StaticResources/keda-v2.yaml

KEDA 2.1 is out 🎉
https://github.com/kedacore/keda/releases/tag/v2.1.0

feat: Support KEDA 2.1

---

README.md

MSDN forums have been migrated to Microsoft Q&A

Update MSDN link

---

build/Settings.cs
src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

* Java: 1.8.2-SNAPSHOT
* Python: 3.1.1.12

Updated WebJost to 3.0.15417, workers to:

---

src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
src/Azure.Functions.Cli/Helpers/PythonHelpers.cs
test/Azure.Functions.Cli.Tests/PythonHelperTests.cs

Resolves https://github.com/Azure/azure-functions-core-tools/issues/2236

Python version warning (when local != remote)

---

src/Azure.Functions.Cli/Kubernetes/KubectlHelper.cs

Bug introduced by #2434
cc @tomkerkhove

Fixes a bug in empty namespace handling

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Reverts https://github.com/Azure/azure-functions-core-tools/commit/3f59245fb21d6b9303ebc61e4271d95ec8fd1e58.

Revert update PowerShell Worker (PS7) to 3.0.705

---

src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
src/Azure.Functions.Cli/Common/Constants.cs

updating the MaxRequestBodySize request size to 100 Mb

---

src/Azure.Functions.Cli/Actions/KubernetesActions/KubernetesDeployAction.cs
src/Azure.Functions.Cli/Helpers/DockerHelpers.cs
src/Azure.Functions.Cli/Kubernetes/KubernetesHelpers.cs
test/Azure.Functions.Cli.Tests/KubernetesHelperUnitTests.cs

- don't append ":latest" to image name
- replace \r\n line endings in shell script
- double quote numerical strings in YamlDotnet

Kubernetes deploy fixes

---

src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
src/Azure.Functions.Cli/Actions/HostActions/Startup.cs
src/Azure.Functions.Cli/Diagnostics/ColoredConsoleLogger.cs
src/Azure.Functions.Cli/Diagnostics/ColoredConsoleLoggerProvider.cs
src/Azure.Functions.Cli/Diagnostics/LoggingBuilder.cs

@ankitkumarr still iterating on a couple of things, but wanted to have this out for initial feedback and to get the artifacts.

[pack] Enhancements to JSON output to support files

---

src/Azure.Functions.Cli/Helpers/WorkerRuntimeLanguageHelper.cs

Fixes https://github.com/Azure/azure-functions-core-tools/issues/2542

Fix java showing up in 'func init'

---

src/Azure.Functions.Cli/Actions/LocalActions/GetExtensionBundlePath.cs
src/Azure.Functions.Cli/ExtensionBundle/ExtensionBundleHelper.cs
test/Azure.Functions.Cli.Tests/ExtensionsTests/ExtensionBundleTests.cs

Adding a command to locate extension bundles root directory

---

src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs
src/Azure.Functions.Cli/Helpers/WorkerRuntimeLanguageHelper.cs

Explicitly implement ToString for WorkerRuntime

---

src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
test/Azure.Functions.Cli.Tests/PublishActionTests.cs

Creating the `UpdateFrameworkVersions` method to make this easier to test in v4, where the logic has a few more steps.

refactoring publish action

---

src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs
src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
src/Azure.Functions.Cli/Common/Constants.cs
src/Azure.Functions.Cli/Helpers/PythonHelpers.cs
src/Azure.Functions.Cli/StaticResources/StaticResources.cs
src/Azure.Functions.Cli/StaticResources/funcignore
src/Azure.Functions.Cli/StaticResources/getting_started_python_function.md
src/Azure.Functions.Cli/StaticResources/requirements.txt
test/Azure.Functions.Cli.Tests/E2E/InitTests.cs

Creating a `getting_started.md` file whenever a new **Python Function app** is created. This file will contain the important resources and links for the customer to get started.

Getting Started for Python Function apps.

---

src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
test/Azure.Functions.Cli.Tests/ActionsTests/StartHostActionTests.cs

Cherry-picked commit 5e114c9 (support secretless extensions) from dev branch (v2) into v3.x branch. 
Fixes #2552

Support secretless extensions in V3

---

CODEOWNERS
src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Python Worker Release note [1.2.6](https://github.com/Azure/azure-functions-python-worker/releases/tag/1.2.6)

Update v3 Python Worker Version to 1.2.6

---

NuGet.Config
src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

https://github.com/Azure/azure-functions-java-worker/releases/tag/2.0.0

Release Java worker 2.0.0

---

src/Azure.Functions.Cli/Kubernetes/KEDA/V2/KedaV2Resource.cs
test/Azure.Functions.Cli.Tests/KedaV2ResourceTests.cs

Cherry picking the changes from PR https://github.com/Azure/azure-functions-core-tools/pull/2793
Related to https://github.com/microsoft/durabletask-mssql/issues/42

Cherry-Pick Null Fix to v4.x

---

publish-scripts/shared/constants.py

This PR ensures the package name is `azure-functions-core-tools-4` when preparing packages for chocolatey and Ubuntu

Update PACKAGENAME for publishing

---

src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs

It appears only the last filter is used, so to filter both we would need to combine it into one filter.

Filter both shm and app insights warnings

---

src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs

Cherry-picked commit from this PR: https://github.com/Azure/azure-functions-core-tools/pull/2814

Port "Filter both shm and app insights warnings" to v4.x

---

azure-pipelines.yml

resolves https://github.com/Azure/azure-functions-core-tools/issues/2846

Update .Net 6 to version 6.0.100 for the Core Tools V4

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

resolves https://github.com/Azure/azure-functions-core-tools/issues/2854

Add nuget package Microsoft.Build version 17.0.0

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

* Update PowerShell Worker `7.0` to `4.0.1273` (release notes: https://github.com/Azure/azure-functions-powershell-worker/releases/tag/v4.0.1273)
* Update PowerShell Worker `7.2` to `4.0.1274` (release notes: https://github.com/Azure/azure-functions-powershell-worker/releases/tag/v4.0.1274)

Update PowerShell Worker 7.0 to 4.0.1273 and 7.2 to 4.0.1274

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Update PowerShell Worker `3.0.1272` (release notes: https://github.com/Azure/azure-functions-powershell-worker/releases/tag/v3.0.1272)

Update PowerShell Worker to 3.0.1272

---

azure-pipelines.yml

Fixes 1ES Hosted Pool demands.

fixes 1ES Hosted Pool image demands

---

azure-pipelines.yml
build.fsx
build.ps1

Moves the parsing logic for SimulateReleaseBuild to the pipeline.

Move SimulateReleaseBuild logic to the pipeline

---

azure-pipelines.yml
build.ps1

Moves the parsing logic for SimulateReleaseBuild to the pipeline.

Move SimulateReleaseBuild logic to the pipeline V3

---

azure-pipelines.yml
build.ps1

Cherry-pick of changes made in #2911

Move SimulateReleaseBuild logic to the pipeline V4

---

build.ps1

Enables running the integration test build command for Core Tools V4

Fix integration test command V4

---

build.ps1

Fixes the command to run integration tests in Core Tools V3.

Fix integration test build command V3

---

src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
src/Azure.Functions.Cli/Common/Constants.cs

resolves #2727
Example when running `func start`

Warn users not to use proxies on v4

---

.vscode/extensions.json
.vscode/launch.json
.vscode/settings.json
.vscode/tasks.json

The config was super out of date, so I wanted to fix a few annoying prompts and make it so that debugging was as easy as hitting F5.
I plan to port this to v3.x and dev branches.

Update VS Code config

---

src/Azure.Functions.Cli/Azure.Functions.Cli.nuspec

Removes V3 from the ID of the nupkg file generated so that versions are not redundant.

Removed V3 from the package ID so that versions are not redundant

---

src/Azure.Functions.Cli/Actions/LocalActions/CreateFunctionAction.cs
src/Azure.Functions.Cli/Actions/LocalActions/ListTemplatesAction.cs

resolves #2891 for Core Tools V4. I am planning on porting this over to `v3.x` as well.

Make grouping insensitive to the case of language spellings

---

src/Azure.Functions.Cli/Actions/LocalActions/CreateFunctionAction.cs
src/Azure.Functions.Cli/Actions/LocalActions/ListTemplatesAction.cs

Cherry-pick of changes from #2922. Resolves #2891

Make grouping insensitive to the case of language spellings (#2922)

---

src/Azure.Functions.Cli/ConsoleApp.cs

Cherry-pick of changes from #2623

Fix typo in RunAsync() V4

---

README.md

Adds instructions to install Core Tools V3 and V4 through winget. This is to be ported to `v4.x` in preparation for renaming that branch `dev`.

Added winget instructions to install Core Tools V3 and V4

---

src/Azure.Functions.Cli/StaticResources/keda-v2.yaml

https://github.com/kedacore/keda/releases/tag/v2.6.0
N/A

feat: Upgrade to KEDA v2.6

---

.github/pull_request_template.md

Cherry-pick of changes from #2939 in preparation for making `v4.x` the default branch.

Removed reference to release_notes.md as that file does not exist V4

---

src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
src/Azure.Functions.Cli/Helpers/AzureHelper.cs

Remove Function key by default when publishing V3

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Release Java worker 1.10.0-SNAPSHOT
https://github.com/Azure/azure-functions-java-worker/releases/tag/1.10.0-SNAPSHOT

Release Java worker 1.10.0-SNAPSHOT

---

src/Azure.Functions.Cli/StaticResources/keda-v2.yaml

https://github.com/kedacore/keda/releases/tag/v2.6.1
N/A

feat: Upgrade to KEDA v2.6.1

---

generateMsiFiles.ps1

Cherry-pick of changes from #2966.

Ensure MSI generation does not silently fail V4

---

generateMsiFiles.ps1

Ensures arguments passed into the .msi generation script are correctly parsed and that the commands do not silently fail.

Ensure MSI generation does not silently fail V3

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

webhost updates

---

src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs

Port of https://github.com/Azure/azure-functions-core-tools/pull/2982

Port "Skip local setting with empty key" to v3.x

---

src/Azure.Functions.Cli/Common/KeyVaultReferencesManager.cs
test/Azure.Functions.Cli.Tests/KeyVaultReferencesManagerTests.cs

Resolves #2989 for Core Tools V3. Cherry-pick of changes from #2991.

Make null and unsupported Key Vault references non-blocking V3

---

tools/go/gozip/go.mod

Resolves #2993 for Core Tools V4.

Update the version of Go used

---

tools/go/gozip/go.mod

Resolves #2993 for Core Tools V3. Cherry-pick of changes for #2996.

Update Go for V3

---

src/Azure.Functions.Cli/Helpers/DotnetHelpers.cs

Adds the KafkaTrigger and KafkaOutput to the list of functions that may be created with Core Tools V3.

Add KafkaTrigger and KafkaOutput for C# functions

---

src/Azure.Functions.Cli/npm/npm-shrinkwrap.json

Port of https://github.com/Azure/azure-functions-core-tools/pull/3003

npm audit fix for minimist [v3]

---

src/Azure.Functions.Cli/npm/npm-shrinkwrap.json

Port of https://github.com/Azure/azure-functions-core-tools/pull/3003

npm audit fix for minimist [v2]

---

src/Azure.Functions.Cli/npm/package.json

Port of https://github.com/Azure/azure-functions-core-tools/pull/3011

Add v2 tag to npm package

---

build/Settings.cs

Updates the function templates used by Core Tools V3. Resolves #2559 for V3.

Update dotnet and dotnet-isolated templates versions V3

---

build/BuildSteps.cs
build/Settings.cs
src/Azure.Functions.Cli/Helpers/DotnetHelpers.cs

Updates template versions used by Core Tools V4.

Update dotnet and dotnet-isolated templates V4

---

src/Azure.Functions.Cli/Helpers/KuduLiteDeploymentHelpers.cs
src/Azure.Functions.Cli/Models/DeploymentLogResponse.cs
src/Azure.Functions.Cli/Models/DeploymentResponse.cs

Allows helper methods to correctly parse nested JSON responses for publishing. This change is to be ported to `v4.x`.

Allow parsing nested JSON responses V3

---

src/Azure.Functions.Cli/Helpers/KuduLiteDeploymentHelpers.cs
src/Azure.Functions.Cli/Models/DeploymentLogResponse.cs
src/Azure.Functions.Cli/Models/DeploymentResponse.cs

Cherry-pick of PR #3015. Allows helper methods to correctly parse nested JSON responses for publishing.

Allow parsing nested JSON responses V4

---

src/Azure.Functions.Cli/Common/DurableManager.cs

When deleting a Task hub via the CLI, the default hardcoded partition count is used (currently 4). This means that only the default number of queues are deleted, resulting in orphaned queues in the storage account.
This pull request uses the partition count specified in the host.json if it is present.
* [ X] My changes **do not** require documentation changes
* [ X] My changes **do not** need to be backported to a previous version

Added PartitionCount lookup from host.json - moved from dev

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Updating host, java worker, and powershell worker.
* [ x] My changes **do not** need to be backported to a previous version
* [ x] I have added all required tests (Unit tests, E2E tests)

Updating host version to 3.5.2

---

src/Azure.Functions.Cli/Common/DurableManager.cs

Added PartitionCount lookup from host.json

---

README.md

Add Chocolatey v4 instructions

---

src/Azure.Functions.Cli/NativeMethods/EnvironmentNativeMethods.cs

fixing a typo in the output
resolves #3048

chore: typo environemt

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Updating Java, Node, Powershell, Python, and host.

Updating host version to 4.3.2

---

src/Azure.Functions.Cli/StaticResources/keda-v2.yaml

Use KEDA v2.7.
Relates to https://github.com/Azure/azure-functions-core-tools/issues/3045

feat: Use KEDA v2.7

---

src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
src/Azure.Functions.Cli/Helpers/ProjectHelpers.cs
test/Azure.Functions.Cli.Tests/E2E/StartTests.cs

Cherry-picking this commit to V4 - https://github.com/Azure/azure-functions-core-tools/commit/f47e2e8d922f4ab3cfd4b89ace3da88cf4dbf3fd
resolves [#issue_for_this_pr](https://github.com/Azure/azure-functions-dotnet-worker/issues/827)

Allow user secrets in dotnet-isolated projects (#3052)

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Update WebHost version to 4.5.1

---

publish-scripts/ubuntu/control_template

Fix displayed package versions for APT in V4

---

build/Settings.cs
src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
validateWorkerVersions.ps1

Update host version 3.7.1

---

src/Azure.Functions.Cli/Kubernetes/FuncKeys/FuncAppKeysHelper.cs

Resolves #2944 for Core Tools V3. This PR should not be merged until the WebHost and worker versions have been updated for the next Core Tools V3 release corresponding to Host version 3.6.1 or later.

Alter key generation logic V3

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Update Host Version 4.5.2

---

src/Azure.Functions.Cli/StaticResources/package.json

See here for more info: https://github.com/Azure/azure-functions-nodejs-worker/issues/587

Add node types to TS project template [v4]

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Update coretools host version to 3.8.2

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

update host version 4.6.1

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
src/Azure.Functions.Cli/Common/Utilities.cs

Resolves #3090. Updates WebHost version to 4.7.2 to unblock integration testing.

Update WebHost version to 4.7.2

---

src/Azure.Functions.Cli/StaticResources/bundleConfig.json

Upgrade the default extensions bundle version to V3. This change is to be ported to `v3.x`.

Upgrade default extensions bundle version

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

host version update 3.10.2

---

src/Azure.Functions.Cli/Actions/KubernetesActions/KubernetesDeployAction.cs

resolves #3105 in V4. This change is to be ported to the `v3.x` branch.

Fix typo in Kubernetes deployments action V4

---

src/Azure.Functions.Cli/Actions/KubernetesActions/KubernetesDeployAction.cs

Fix typo in Kubernetes deployment action V3

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

coretools update v4.7.3

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

core tools update v3.11.0

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

core tools update 4.8.1

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

core tools update 3.12.1

---

src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs
src/Azure.Functions.Cli/Common/Constants.cs
test/Azure.Functions.Cli.Tests/E2E/InitTests.cs

resolves https://github.com/Azure/azure-functions-core-tools/issues/3134

Make PowerShell 7.2 the default when creating a PowerShell function app

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

core tools update v4.10.2

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Update version 4.10.4

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

core tool update v3.13.1

---

src/Azure.Functions.Cli/npm/lib/install.js
src/Azure.Functions.Cli/npm/lib/main.js
src/Azure.Functions.Cli/npm/npm-shrinkwrap.json
src/Azure.Functions.Cli/npm/package.json

Get rid of unused npm dependencies [v3.x]

---

src/Azure.Functions.Cli/npm/lib/install.js
src/Azure.Functions.Cli/npm/lib/main.js
src/Azure.Functions.Cli/npm/npm-shrinkwrap.json
src/Azure.Functions.Cli/npm/package.json

Get rid of unused npm dependencies [v4.x]

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Updates the host to a version published on GitHub to resolve integration build failures.

Update host to 4.12.1

---

src/Azure.Functions.Cli/Common/DurableManager.cs
test/Azure.Functions.Cli.Tests/Azure.Functions.Cli.Tests.csproj
test/Azure.Functions.Cli.Tests/E2E/DurableTests.cs
test/Azure.Functions.Cli.Tests/E2E/Helpers/CliTester.cs
test/Azure.Functions.Cli.Tests/E2E/Helpers/DurableHelper.cs

This is the cherry-pick of https://github.com/Azure/azure-functions-core-tools/pull/3126 into the v3 branch.

Durable commands to check for non-Azure Storage backends (#3126)

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Update Coretools version to 4.11.2

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

updated host version to 3.14.1

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Updated Coretools 4.12.2

---

src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
src/Azure.Functions.Cli/Common/TemplatesManager.cs
src/Azure.Functions.Cli/ExtensionBundle/ExtensionBundleHelper.cs

Increases extension bundle download timeout

V3: Increase extension bundle download timeout. 

---

src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
src/Azure.Functions.Cli/Common/TemplatesManager.cs
src/Azure.Functions.Cli/ExtensionBundle/ExtensionBundleHelper.cs

Increasing the timeout of extension bundle download. 

V4: Increase extension bundle download timeout

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Updated Core tools version to 3.15.1

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Resolves https://github.com/Azure/azure-functions-core-tools/issues/3183.

Update Microsoft.ApplicationInsights to version 2.20.1

---

build/Settings.cs

Updates .NET isolated templates to match what is present in the tooling feed.

Update .NET isolated templates to 4.0.2288

---

validateWorkerVersions.ps1

Update .csproj path in validateWorkerVersions.ps1 script

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
validateWorkerVersions.ps1

update core tools host version 3.16.0

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Updated Coretools version 4.13.0

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Updated core tools to 3.17.0

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Update Core tools version 4.14.0

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

updated Core tools version to 4.15.1

---

pipelineUtilities.psm1

Resolving error made when pushing changes for v4 build issue.

Merge Release to v4.x

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

updated Coretools version 4.15.2

---

test/Azure.Functions.Cli.Tests/E2E/CreateFunctionTests.cs

Increasing the test timeout for V4 tests and tests are failing in pipeline because of timeout. 

Node v4 Test timeout fix. 

---

src/Azure.Functions.Cli/Actions/LocalActions/CreateFunctionAction.cs
src/Azure.Functions.Cli/Common/TemplatesManager.cs

Added small checks for templates so that v3 doesn't accidently pick up the v4 template. 

Added new checks for templates.

---

src/Azure.Functions.Cli/Actions/LocalActions/CreateFunctionAction.cs
src/Azure.Functions.Cli/Common/ContextHelpManager.cs
src/Azure.Functions.Cli/Interfaces/IContextHelpManager.cs

Some cleanups for context help

Node v4: Help Update

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

 Updated Coretools version to 4.16.3

---

test/Azure.Functions.Cli.Tests/E2E/InitTests.cs

Addressed the node test timeout.

---

src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs

- Fixing the bug > The consumption check should only be for Linux (not Windows)
- Updated the error message
- https://github.com/Azure/azure-functions-core-tools/issues/2672
- https://github.com/Azure/azure-functions-core-tools/issues/2671

Managed identity fix.

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Updated Coretools version to 4.16.4

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Updated Coretools version to 4.16.5

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Update core tools version to 4.19.1

---

src/Azure.Functions.Cli/Actions/ContainerService/AzureContainerAppsDeployAction.cs
src/Azure.Functions.Cli/ContainerApps/Models/ContainerAppFunctonCreateResponse.cs
src/Azure.Functions.Cli/Helpers/AzureHelper.cs

Getting the hostname from different source if not available 

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Update core tools version to 4.19.2

---

src/Azure.Functions.Cli/StaticResources/package-ts-v4.json
src/Azure.Functions.Cli/StaticResources/package-ts.json

- Add a clean script to model v4, related to [this issue](https://github.com/ejizba/func-nodejs-prototype/issues/18) by @hossam-nasr
- Update a few versions

Update TypeScript package.json templates

---

src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs
src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
src/Azure.Functions.Cli/StaticResources/Dockerfile.dotnet
src/Azure.Functions.Cli/StaticResources/Dockerfile.dotnetIsolated
src/Azure.Functions.Cli/StaticResources/Dockerfile.node18
src/Azure.Functions.Cli/StaticResources/Dockerfile.typescript.node18
src/Azure.Functions.Cli/StaticResources/StaticResources.cs

Updating the docker files.

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Update core tools version to 4.21.1

---

src/Azure.Functions.Cli/npm/npm-shrinkwrap.json

NPM package agent-base updated.

NPM package agent-base updated.

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Update core tools version to 4.22.0

---

NuGet.Config

resolves https://github.com/Azure/azure-functions-core-tools/issues/3396

Add AzureFunctionsTempStaging feed

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Update core tools version to 4.23.0

---

src/Azure.Functions.Cli/StaticResources/bundleConfig.json
src/Azure.Functions.Cli/StaticResources/bundleConfigNodeV4.json

standardizing on bundles v4

---

build/Settings.cs
src/Azure.Functions.Cli/Actions/ContainerService/AzureContainerAppsDeployAction.cs
src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs
src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
src/Azure.Functions.Cli/Common/TargetFramework.cs
src/Azure.Functions.Cli/Helpers/TargetFrameworkHelper.cs
src/Azure.Functions.Cli/StaticResources/Dockerfile.dotnet8Isolated
src/Azure.Functions.Cli/StaticResources/StaticResources.cs

.NET 8 (Preview) support in Core Tools. 

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Updating Microsoft.Azure.WebJobs.Script.WebHost package to 4.23.2

---

src/Azure.Functions.Cli/Actions/LocalActions/CreateFunctionAction.cs
test/Azure.Functions.Cli.Tests/E2E/StartTests.cs

V3 - .NET User Experience Bug Fix

---

build/Settings.cs

Updated the template versions.

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Updated Core Tools to 4.24.4

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Updated Core Tools to 4.24.5

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Updated Core Tools to 4.25.3

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Update core tools version to 4.26.1

---

build/Settings.cs

Adding json.sha256 in the filter

---

build/Settings.cs
src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
src/Azure.Functions.Cli/Common/Constants.cs

Enabling Worker Indexing

---

build/Settings.cs

Adding json.sha256 in the filter (#3459)

---

build/Settings.cs
test/Azure.Functions.Cli.Tests/E2E/StartTests.cs

Increased timeouts for Node tests

---

src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
src/Azure.Functions.Cli/Common/Constants.cs
test/Azure.Functions.Cli.Tests/E2E/StartTests.cs

Adding worker indexing for core tools 4.25.3.

4.25.3 hotfix

---

build/Settings.cs
src/Azure.Functions.Cli/Actions/KubernetesActions/KubernetesDeployAction.cs
src/Azure.Functions.Cli/StaticResources/print-functions.sh

From https://github.com/Azure/azure-functions-core-tools/pull/3000#pullrequestreview-1627610822 For https://github.com/Azure/azure-functions-core-tools/issues/2825
Unfortunately, the PR build fails when PR is created from fork (we are working on that). I have cherry-picked the commit and have created new PR from my branch (all changes are from the mentioned PR).

func kubernetes deploy dryrun fix

---

build/BuildSteps.cs
src/Azure.Functions.Cli/Actions/LocalActions/CreateFunctionAction.cs
src/Azure.Functions.Cli/Actions/UserInputHandler.cs
src/Azure.Functions.Cli/Common/Constants.cs
src/Azure.Functions.Cli/Common/TemplatesManager.cs

Merging https://github.com/Azure/azure-functions-core-tools/commit/092511134486902c1897b895e96cd663979d9549 into the hotfix branch.

Using ext bundle instead of hard-coded v2 templates (#3391)

---

build/Settings.cs
src/Azure.Functions.Cli/Common/CommandChecker.cs
test/Azure.Functions.Cli.Tests/ExtensionsTests/ExtensionBundleTests.cs

Use where.exe from System directory on Windows

---

src/Azure.Functions.Cli/Helpers/DotnetHelpers.cs

From the AshiqueMD PR at https://github.com/Azure/azure-functions-core-tools/pull/3451. Had to create a new PR because of build issue.  Following description is from the original PR. 
Adding Azure Functions Dapr extension core tool templates

Adding dapr triggers and binding templates

---

build/Settings.cs

Fix the PowerShell build issue for newest 7.4

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Update core tools to 4.27.5

---

build/Settings.cs

Templates Update

---

src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs

Updating the warning message

---

build/Settings.cs
src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs

Updating the release branch. 

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Host revert to 4.25

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Reverts Azure/azure-functions-core-tools#3500

Revert "Host revert to 4.25"

---

build/Settings.cs
src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
src/Azure.Functions.Cli/StaticResources/node-v4-templates.json

Release Update from v4.x

---

src/Azure.Functions.Cli/StaticResources/Dockerfile.dotnet7Isolated
src/Azure.Functions.Cli/StaticResources/Dockerfile.dotnet8Isolated

fix image name in comments dotnet-isolated

---

azure-pipelines.yml
check-vulnerabilities.ps1
pipelineUtilities.psm1
src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Vulnerability checks in the pipeline

---

azure-pipelines.yml
check-vulnerabilities.ps1

Removed the restore and moved the check.

---

src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
src/Azure.Functions.Cli/Common/Constants.cs

Support of --build flag for Windows

---

src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs

Fixing .NET 8 publish bug

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Update core tools to 4.28.2

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Updated Coretools to 4.28.3

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Updated Coretools to 4.28.3 (#3556)

---

src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs
src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
test/Azure.Functions.Cli.Tests/E2E/InitTests.cs

String and enum updates. I tested ad hoc. I don't believe additional unit tests are needed but please correct me on that. Docs already reflect passing the parameter itself.
resolves #3569

updating default TFM and help strings

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Updating host version to 3.21.1

---

src/Azure.Functions.Cli/Actions/LocalActions/CreateFunctionAction.cs
src/Azure.Functions.Cli/Actions/UserInputHandler.cs
src/Azure.Functions.Cli/Common/Constants.cs

Fixing bug where auth parameter was ignored by Python v2.
https://github.com/Azure/azure-functions-core-tools/issues/3555
https://github.com/Azure/azure-functions-core-tools/issues/3533
https://github.com/Azure/azure-functions-core-tools/issues/3470

Fixing bug where auth parameter was ignored by Python v2.

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Updating app insights to match the host's version.

Updating app insights package

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Updated Coretools to 4.31.1

---

azure-pipelines.yml
publish-scripts/driver.py

Linux Package Create

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Updated Core tools to 4.33.1

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Upgrading Azure.Identity to compliant version

Upgrading Azure.Identity to compliant version

---

src/Azure.Functions.Cli/Actions/HostActions/Startup.cs
src/Azure.Functions.Cli/Actions/HostActions/WebHost/Security/CliAuthenticationHandler.cs
src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
test/Azure.Functions.Cli.Tests/E2E/StartTests.cs

Updated core tools to 3.22.0

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Updated Core tools to 4.33.2

---

README.md

Apologies for my English. There are missing periods in the winget installation that cause it to return an error saying "package is not found". Once the missing periods are added, it works correctly.

Update README.md. Adding . in Install with winget

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Updated Azure Indentity version to 1.11.2

Updated Azure Indentity version to 1.11.2

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
test/Azure.Functions.Cli.Tests/Azure.Functions.Cli.Tests.csproj

Updated Newtonsoft to 13.0.3

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Updated Coretools to 4.34.1

---

build/BuildSteps.cs
src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Zip generation updates for Inproc8

Zip generation updates for Inproc8 

---

build/Settings.cs
src/Azure.Functions.Cli/Helpers/DotnetHelpers.cs

Add Event Grid Blob trigger

---

build/BuildSteps.cs

Publish self-contained binaries for the artifacts.

.NET8 In-proc publish --self-contained

---

build/Settings.cs

Updating template reference
resolves https://github.com/Azure/azure-functions-host/issues/10066

updating template reference for core tools

---

code-mirror.yml

Adding code mirroring yml

---

build/Settings.cs
code-mirror.yml
src/Azure.Functions.Cli/Actions/AzureActions/LogStreamAction.cs
src/Azure.Functions.Cli/Helpers/DotnetHelpers.cs

Update release branch from v4.x

---

src/Azure.Functions.Cli/Helpers/DotnetHelpers.cs
src/Azure.Functions.Cli/StaticResources/node-v4-templates.json

- Adds the Event Grid Blob trigger to the Node v4 templates

Add hard-coded Node templates for EventGrid Blob trigger

---

build/BuildSteps.cs
build/Settings.cs
build/Shell.cs
code-mirror.yml
pipelineUtilities.psm1
src/Azure.Functions.Cli/Actions/AzureActions/LogStreamAction.cs
src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs
src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
src/Azure.Functions.Cli/Common/Constants.cs
src/Azure.Functions.Cli/Common/ProcessManager.cs
src/Azure.Functions.Cli/Helpers/DotnetHelpers.cs
src/Azure.Functions.Cli/Helpers/GlobalCoreToolsSettings.cs
src/Azure.Functions.Cli/Helpers/TargetFrameworkHelper.cs
src/Azure.Functions.Cli/Interfaces/IProcessManager.cs
src/Azure.Functions.Cli/Program.cs
src/Azure.Functions.Cli/StaticResources/Dockerfile.dotnet8
src/Azure.Functions.Cli/StaticResources/StaticResources.cs
src/Azure.Functions.Cli/StaticResources/node-v4-templates.json
test/Azure.Functions.Cli.Tests/Azure.Functions.Cli.Tests.csproj
test/Azure.Functions.Cli.Tests/E2E/InitTests.cs
test/Azure.Functions.Cli.Tests/E2E/StartTests.cs

Merge v4.x to release_4.0 branch

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Bump Microsoft.Azure.WebJobs.Script.WebHost from 4.834.2 to 4.834.3

Bump Microsoft.Azure.WebJobs.Script.WebHost from 4.834.2 to 4.834.3

---

build/BuildSteps.cs
src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Fix signing for .net8 binaries and bump host version to support .net8 

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

#	src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Updated packages.

---

src/Azure.Functions.Cli/StaticResources/Dockerfile.dotnet8

Updates base image tag for scaffolded Dockerfile to use the modified format.

Correcting in-process model tag format

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
src/Azure.Functions.Cli/StaticResources/Dockerfile.dotnet8

Including dockerfile update into release. 

---

build.ps1
build/BuildSteps.cs
build/Program.cs
build/Settings.cs
eng/ci/official-build.yml
eng/ci/public-build.yml
eng/ci/templates/official/jobs/build-test.yml
eng/ci/templates/public/jobs/build-test-public.yml
src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs
src/Azure.Functions.Cli/Helpers/DotnetHelpers.cs
test/Azure.Functions.Cli.Tests/E2E/DeploymentTests.cs
test/Azure.Functions.Cli.Tests/E2E/E2ETestConstants.cs
test/Azure.Functions.Cli.Tests/E2E/InitTests.cs

New Pipelines (v3)

---

eng/ci/official-build.yml

Switched back to engineering release tag (v3)

---

eng/ci/official-build.yml
eng/ci/public-build.yml
eng/ci/templates/official/jobs/build-test.yml
test/Azure.Functions.Cli.Tests/E2E/CreateFunctionTests.cs
test/Azure.Functions.Cli.Tests/E2E/InitTests.cs
test/Azure.Functions.Cli.Tests/E2E/SettingsTests.cs
test/Azure.Functions.Cli.Tests/E2E/StartTests.cs
test/Azure.Functions.Cli.Tests/ExtensionsTests/ExtensionBundleTests.cs
test/Azure.Functions.Cli.Tests/ExtensionsTests/InstallExtensionsTests.cs

Switched to Engineering release tag (v4)

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Bringing in the changes from https://github.com/Azure/azure-functions-core-tools/pull/3724 to release_4.0

[release_4.0] Removing package reference of Microsoft.IdentityModel.JsonWebTokens & System.IdentityModel.Tokens.Jwt packages

---

eng/ci/templates/official/jobs/build-test.yml

Build number reset for new pipeline (v3)

---

src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs

Updating the executable name for net8 in-proc based on operating system.
resolves #3713

Set the in-proc net8 executable name based on operating system

---

build.ps1
build/BuildSteps.cs
build/Program.cs
build/Settings.cs
code-mirror.yml
eng/ci/official-build.yml
eng/ci/public-build.yml
eng/ci/templates/official/jobs/build-test.yml
eng/ci/templates/public/jobs/build-test-public.yml
src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs
src/Azure.Functions.Cli/Helpers/DotnetHelpers.cs
test/Azure.Functions.Cli.Tests/E2E/DeploymentTests.cs
test/Azure.Functions.Cli.Tests/E2E/E2ETestConstants.cs
test/Azure.Functions.Cli.Tests/E2E/InitTests.cs

Update release_3.0 from v3.x

---

src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
test/Azure.Functions.Cli.Tests/E2E/CreateFunctionTests.cs
test/Azure.Functions.Cli.Tests/E2E/InitTests.cs
test/Azure.Functions.Cli.Tests/E2E/SettingsTests.cs
test/Azure.Functions.Cli.Tests/E2E/StartTests.cs
test/Azure.Functions.Cli.Tests/ExtensionsTests/ExtensionBundleTests.cs
test/Azure.Functions.Cli.Tests/ExtensionsTests/InstallExtensionsTests.cs

Cherry picking https://github.com/Azure/azure-functions-core-tools/pull/3730 to release_4.0

[release_4.0] Set the inproc net8 executable name based on operating system. (#3730)

---

src/Azure.Functions.Cli/Actions/UserInputHandler.cs

Added new labels for OpenAI templates:
Templates PR Ref: https://github.com/Azure/azure-functions-templates/pull/1540

Added new labels for OpenAI templates

---

src/Azure.Functions.Cli/StaticResources/Dockerfile.node14
src/Azure.Functions.Cli/StaticResources/Dockerfile.node16
src/Azure.Functions.Cli/StaticResources/Dockerfile.node18
src/Azure.Functions.Cli/StaticResources/Dockerfile.typescript
src/Azure.Functions.Cli/StaticResources/Dockerfile.typescript.node18

Split 'npm install' and 'npm run build' stages

---

.github/ISSUE_TEMPLATE/01-bug-report.yml
.github/ISSUE_TEMPLATE/02-feature-request.yml
.github/ISSUE_TEMPLATE/config.yml

This PR updates the issue templates to bring an experience similar to what we have in the Functions .NET worker repo.

Creating issue templates

---

src/Azure.Functions.Cli/Telemetry/DockerContainerDetectorForTelemetry.cs

This fix has already been applied to the .NET SDK under PR https://github.com/dotnet/sdk/pull/22927.
Also disabling unnecessary platform compatibility warnings where the the platform specific APIs are in the correct platform specific code path.
Resolves #3236 
Note: I don't know what the backporting rules are. Happy to open other PRs to back port if necessary. 
Unit test wise, I can add some, but it'll require a little refactoring. Let me know if it's needed.

Handling a telemetry exception where a Linux file path isn't readable

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Updated Coretools to 4.35.3

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Updated Coretools to 4.35.4

---

src/Azure.Functions.Cli/Common/FileSystemHelpers.cs
src/Azure.Functions.Cli/Helpers/DotnetHelpers.cs
src/Azure.Functions.Cli/npm/lib/install.js

HF 4.0.5907 Tag and adding (#3773) (#3797) commit to branch"

---

src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
test/Azure.Functions.Cli.Tests/E2E/InitTests.cs

Adding #3760 to Core tools HotFix"

---

src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs
src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
src/Azure.Functions.Cli/Common/TargetFramework.cs
src/Azure.Functions.Cli/StaticResources/Dockerfile.dotnet9Isolated
src/Azure.Functions.Cli/StaticResources/StaticResources.cs
test/Azure.Functions.Cli.Tests/E2E/InitTests.cs

resolves #2590
This PR creates the docker .NET 9 isolated image (note that we need the image published first before merging/releasing this PR)

Update dockerfile with latest image for .NET 9 isolated

---

src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs
src/Azure.Functions.Cli/Common/Constants.cs
src/Azure.Functions.Cli/Common/DotnetConstants.cs
test/Azure.Functions.Cli.Tests/ActionsTests/StartHostActionTests.cs
test/Azure.Functions.Cli.Tests/E2E/StartTests.cs

Small refactoring and some unit tests.

Small refactor and new tests

---

host/src/CoreToolsHost/CoreToolsHost.csproj

Small note to document the CET configuration applied to the custom host.

Adding a comment to document our CET configuration

---

host/src/CoreToolsHost/LocalSettingsJsonParser.cs

resolves #[3868](https://github.com/Azure/azure-functions-core-tools/issues/3868)

Custom host: allow trailing commas in local.settings.json

---

src/Azure.Functions.ArtifactAssembler/PipelineHelpers/zipCliArtifacts.ps1

Generating sha files for core tools artifacts

Generating sha files for core tools artifacts

---

pipelineUtilities.psm1
src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Adding package reference explicitly

Adding package reference

---

eng/ci/templates/official/jobs/build-test.yml
src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Updating transitive reference for System.text.json for inproc branch

Updating System.Text.Json

---

eng/ci/templates/official/jobs/build-test.yml

We want to know if there's a security vulnerability in the codebase before we build the code in the oop feature branch

moving security vulnerability check to before build

---

eng/ci/templates/official/jobs/build-test.yml
eng/ci/templates/public/jobs/build-test-public.yml
src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
test/Azure.Functions.Cli.Tests/Azure.Functions.Cli.Tests.csproj
test/Azure.Functions.Cli.Tests/E2E/Helpers/QueueStorageHelper.cs
test/Azure.Functions.Cli.Tests/E2E/StartTests.cs
tools/start-emulators.ps1

resolves #3833
- Added new queue helper
- Added storage emulator script
- Refactored user secret tests to make sure a function can still execute successfully with user secrets
> I refactored a lot of the CliTester/StartTests but the PR was getting too big and complicated so I'm splitting this out into multiple PRs.
Chain of PRs:
1. #3847
2. #3850 
3. #3846

Update UserSecret E2E Tests

---

build/Settings.cs

Core Tools template updates to make default SDK 4.5.0

---

build/Build.csproj
src/Azure.Functions.Cli/Azure.Functions.Cli.csproj

Package Updates

---

src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
src/Azure.Functions.Cli/Helpers/GlobalCoreToolsSettings.cs
src/Azure.Functions.Cli/Helpers/WorkerRuntimeLanguageHelper.cs
test/Azure.Functions.Cli.Tests/PublishActionTests.cs

Throw argument exception when WorkerRuntime is 'None'

---

.github/workflows/dependency-review.yml

Adds a new github workflow which will review any dependency changes in a PR. See [dependency-review](https://github.com/marketplace/actions/dependency-review) for more information.

Add workflow to review PR dependencies

---

CONTRIBUTING.md

Update contributing doc to to include testing information

Update contributing doc to to include testing information

---

Azure.Functions.Cli.sln
build/BuildSteps.cs
build/Program.cs
eng/ci/public-build.yml
eng/ci/templates/public/jobs/build-test-public.yml
skipPackagesCve.json
src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs
src/Azure.Functions.Cli/Actions/LocalActions/PackAction.cs
src/Azure.Functions.Cli/Azure.Functions.Cli.csproj
src/Azure.Functions.Cli/Common/Constants.cs
src/Azure.Functions.Cli/Helpers/ZipHelper.cs
test/Azure.Functions.Cli.Tests/E2E/Helpers/ProcessHelper.cs
test/Azure.Functions.Cli.Tests/E2E/InitTests.cs
test/Azure.Functions.Cli.Tests/E2E/StartTests.cs
test/Azure.Functions.Cli.Tests/ZipHelperTests.cs
test/ZippedExe/Program.cs
test/ZippedExe/ZippedExe.csproj

cherry-pick of #4212 to in-proc branch

Updating package zipping

---

.editorconfig
eng/Directory.Build.Common.props
eng/Directory.Packages.props
src/Cli/Abstractions/Azure.Functions.Cli.Abstractions.csproj
src/Cli/ArtifactAssembler/Azure.Functions.Cli.ArtifactAssembler.csproj
src/Cli/func/Azure.Functions.Cli.csproj
src/CoreToolsHost/CoreToolsHost.csproj
stylecop.json

Add host stylecop rules & add analyzer reference to src projects
resolves #4367

Add editorconfig & stylecop analyzer

---

src/Cli/func/Actions/KubernetesActions/DeployKedaAction.cs
src/Cli/func/Actions/KubernetesActions/KubernetesDeleteAction.cs
src/Cli/func/Actions/KubernetesActions/KubernetesDeployAction.cs
src/Cli/func/Actions/KubernetesActions/RemoveKedaAction.cs
src/Cli/func/Actions/LocalActions/AddSettingAction.cs
src/Cli/func/Actions/LocalActions/CreateFunctionAction.cs
src/Cli/func/Actions/LocalActions/DecryptSettingAction.cs
src/Cli/func/Actions/LocalActions/DeleteSettingAction.cs
src/Cli/func/Actions/LocalActions/EncryptSettingsAction.cs
src/Cli/func/Actions/LocalActions/GetExtensionBundlePath.cs
src/Cli/func/Actions/LocalActions/InitAction.cs
src/Cli/func/Actions/LocalActions/InstallExtensionAction.cs
src/Cli/func/Actions/LocalActions/ListSettingsAction.cs
src/Cli/func/Actions/LocalActions/ListTemplatesAction.cs
src/Cli/func/Actions/LocalActions/PackAction.cs
src/Cli/func/Actions/LocalActions/SyncExtensionsAction.cs
src/Cli/func/Actions/LogsActions/GetLogsAction.cs

Series of PRs to address error or warnings style issues in src/Cli/func

Fix style in Actions/ (part 2)

---

.editorconfig
src/Cli/Abstractions/Command/Command.cs
src/Cli/Abstractions/Command/CommandLoggingContext.cs
src/Cli/Abstractions/Command/CommandResult.cs
src/Cli/Abstractions/Command/ICommand.cs
src/Cli/Abstractions/Environment/Env.cs
src/Cli/Abstractions/Environment/EnvironmentProvider.cs
src/Cli/Abstractions/Environment/IEnvironmentProvider.cs
src/Cli/Abstractions/Extensions/AnsiExtensions.cs
src/Cli/Abstractions/Extensions/CollectionExtensions.cs
src/Cli/Abstractions/Logging/AnsiConsole.cs
src/Cli/Abstractions/Logging/IReporter.cs
src/Cli/Abstractions/Logging/Reporter.cs
src/Cli/Abstractions/NativeMethods.cs
src/Cli/Abstractions/ProcessReaper.cs
src/Cli/Abstractions/README.md
src/Cli/Abstractions/Streams/StreamForwarder.cs

Fix style in Abstractions project

---

src/Cli/func/Arm/ArmClient.cs
src/Cli/func/Arm/ArmResourceNotFoundException.cs
src/Cli/func/Arm/ArmUriTemplates.cs
src/Cli/func/Arm/Models/AppServiceConnectionString.cs
src/Cli/func/Arm/Models/ArgResponse.cs
src/Cli/func/Arm/Models/ArmArrayWrapper.cs
src/Cli/func/Arm/Models/ArmGenericResource.cs
src/Cli/func/Arm/Models/ArmResourceId.cs
src/Cli/func/Arm/Models/ArmStorageKeys.cs
src/Cli/func/Arm/Models/ArmStorageKeysArray.cs
src/Cli/func/Arm/Models/ArmSubscription.cs
src/Cli/func/Arm/Models/ArmSubscriptionsArray.cs
src/Cli/func/Arm/Models/ArmWebsite.cs
src/Cli/func/Arm/Models/ArmWebsiteConfig.cs
src/Cli/func/Arm/Models/ArmWebsitePublishingCredentials.cs
src/Cli/func/Arm/Models/ArmWrapper.cs
src/Cli/func/Arm/Models/BasicAuthCheckResponse.cs
src/Cli/func/Arm/Models/FunctionInfo.cs
src/Cli/func/Arm/Models/Site.cs
src/Cli/func/Arm/Models/StorageAccount.cs

Series of PRs to address error or warnings style issues in src/Cli/func

Fix style in Arm/

---

src/Cli/func/ContainerApps/Models/ContainerAppFunctonCreateResponse.cs
src/Cli/func/ContainerApps/Models/ContainerAppsFunctionDeployResponse.cs
src/Cli/func/ContainerApps/Models/ContainerAppsFunctionPayload.cs
src/Cli/func/ContainerApps/Models/ManagedEnvironementGetResponse.cs
src/Cli/func/Diagnostics/ColoredConsoleLogger.cs
src/Cli/func/Diagnostics/ColoredConsoleLoggerProvider.cs
src/Cli/func/Diagnostics/DisableConsoleConfigurationBuilder.cs
src/Cli/func/Diagnostics/LoggerRuleSelector.cs
src/Cli/func/Diagnostics/LoggingBuilder.cs
src/Cli/func/Diagnostics/LoggingFilterHelper.cs
src/Cli/func/Diagnostics/ProviderAliasUtilities.cs
src/Cli/func/Models/DeploymentLogResponse.cs
src/Cli/func/Models/DeploymentResponse.cs
src/Cli/func/NativeMethods/ConsoleNativeMethods.cs
src/Cli/func/NativeMethods/EnvironmentNativeMethods.cs
src/Cli/func/NativeMethods/ProcessNativeMethods.cs
src/Cli/func/Properties/AssemblyInfo.cs
src/Cli/func/Secrets/UserSecretsConfigurationBuilder.cs
src/Cli/func/StacksApi/FlexFunctionsStacks.cs
src/Cli/func/StacksApi/FunctionsStacks.cs
src/Cli/func/StaticResources/StaticResources.cs

Series of PRs to address error or warnings style issues in src/Cli/func

Fix style in Models, ContainerApps, Diagnostics and misc

---

src/CoreToolsHost/AppLoader/AppLoader.cs
src/CoreToolsHost/AppLoader/HostFxr.cs
src/CoreToolsHost/AppLoader/NetHost.cs
src/CoreToolsHost/DotnetConstants.cs
src/CoreToolsHost/Environment/EnvironmentUtils.cs
src/CoreToolsHost/Environment/EnvironmentVariables.cs
src/CoreToolsHost/LocalSettingsJsonParser.cs
src/CoreToolsHost/Logger.cs
src/CoreToolsHost/Program.cs

fixing style issues in coretoolhost project
Partially resolves #4320

Fix style in coretoolhost Project

---

.editorconfig
Directory.Build.targets
eng/Directory.Build.Common.props
eng/build/Cli.Build.targets
test/Azure.Functions.Cli.Tests/.editorconfig
test/Cli/TestFramework/Azure.Functions.Cli.TestFramework.csproj

Warnings as errors in CI

---

eng/ci/templates/official/jobs/linux-package.yml
publish-scripts/shared/helper.py
publish-scripts/ubuntu/buildDEB.py

Update DEB publish scripts and linux-package CI to support arm64

---

eng/ci/templates/official/jobs/build-test.yml
eng/ci/templates/public/jobs/build-test-public.yml
pipelineUtilities.psm1

Fixing in-proc build by removing SBOM manifest related steps and utils

Fixing in-proc branch by removing SBOM manifest

---

build/Build.csproj
src/Cli/func/Helpers/TelemetryHelpers.cs

Suppress build.csproj warnings and CS0162

---

eng/scripts/ArtifactAssemblerHelpers/moveNugetPackage.ps1
src/Cli/ArtifactAssembler/Constants.cs

Update core tools version regex to allow for `-preview` suffix

Update core tools version regex to allow for `-preview` suffix

---

eng/ci/templates/official/jobs/linux-package.yml
publish-scripts/shared/helper.py

Fix linux package DEB script & CI pipeline.

Fix linux package DEB script & CI pipeline

---

src/CoreToolsHost/CoreToolsHost.csproj

This property is only relevant due to this project being native AOT.
https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/security#control-flow-guard

Enable ControlFlowGuard for host

---

eng/ci/host-artifacts-build.yml
eng/ci/official-build.yml
eng/ci/templates/official/jobs/consolidate-cli-artifacts.yml
eng/ci/templates/official/jobs/host-build-pack.yml
eng/ci/templates/official/jobs/publish-cli.yml
eng/ci/templates/official/jobs/upload-artifact-to-feed.yml
src/Cli/ArtifactAssembler/Constants.cs

Update host and consolidation CI pipelines
- Pipelines have been updates to output a single artifact making the consolidation pipeline simpler.
- Updated naming `core-tools` to `func-cli`
n/a

Update host and consolidation CI pipelines

---

eng/ci/templates/official/jobs/linux-package.yml

Use DefaultArtifactVersion for version tag

Fix linux package CI - use DefaultArtifactVersion for version tag

---

eng/ci/official-build.yml
eng/ci/templates/official/jobs/publish-cli.yml
eng/ci/templates/official/steps/sign-linux.yml

- Adding linux signing for func and gozip
- Update CI to sign after publish

Update CI to sign after publish & add linux signing 

---

eng/ci/templates/official/jobs/upload-artifact-to-feed.yml

n/a
Fixing the parameter syntax in the nightly build CI

Fixing the parameter syntax in the nightly build CI (#3837)

---

eng/tools/publish-tools/npm/npm-shrinkwrap.json
eng/tools/publish-tools/npm/package.json

n/a
Update the npm publish script template to the latest version of the CLI. This happens automatically in CI when we deploy, but `3.0.2106` is quiet old and we should keep this reletatively up to date for compliance.

Update CLI version in the npm publish script

---

eng/ci/templates/official/jobs/consolidate-cli-artifacts.yml
eng/ci/templates/official/jobs/host-build-pack.yml
eng/ci/templates/official/jobs/linux-deb-build-pack.yml
eng/scripts/artifact-assembler/generate-metadata-file.ps1
eng/scripts/generate-sha-files.ps1

n/a
Fixing bugs in the consolidation pipeline. Pipeline validated here: https://azfunc.visualstudio.com/internal/_build/results?buildId=227154&view=results . Also noticed the reference to the metadata file was wrong in the linux CI so fixing that as well.

Fix consolidated pipeline & nightly feed versioning for linux and host CI

---

src/Azure.Functions.Cli/Directory.Version.props

Bump CLI version for next release.

[in-proc] Bump CLI version for release

---

release_notes.md
src/Cli/func/Helpers/AzureHelper.cs

This PR adds more logging for detailed logging regarding calling the admin/host/status endpoint for flex to investigate a customer issue when migrating over when using core tools.

Adding more logs in `CheckFunctionHostStatusForFlex`

---

README.md
docs/get-started-kubernetes.md

n/a
Tidy up the README and break out kubernetes info into its own doc

Clean up readme

---

src/Cli/func/CancelKeyHandler.cs
src/Cli/func/Common/ProcessManager.cs
src/Cli/func/Interfaces/IProcessManager.cs
src/Cli/func/Program.cs
test/Cli/Func.UnitTests/CancelKeyHandlerTests.cs

n/a
Addressing additonal feedback for https://github.com/Azure/azure-functions-core-tools/pull/4540

Cleanup CancelKeyHandler

---

src/Azure.Functions.Cli/Directory.Version.props

Bump version for release

---

src/Cli/func/Actions/HostActions/StartHostAction.cs

resolves #4227
Let users know that `CONTAINER_NAME` is a protected environment variable until there are changes in the host to move away from this practice.

Notify of `CONTAINER_NAME` being a protected environment variable

---

.vscode/launch.json
src/Cli/func/Actions/LocalActions/GetExtensionBundlePath.cs
src/Cli/func/ExtensionBundle/ExtensionBundleHelper.cs
test/Cli/Func.UnitTests/ActionsTests/StartHostActionTests.cs
test/Cli/Func.UnitTests/HelperTests/ExtensionBundleHelperTests.cs
test/Cli/Func.UnitTests/HelperTests/HostHelperTests.cs
test/Cli/Func.UnitTests/HelperTests/ZipHelperTests.cs

Fix flakey tests

---

release_notes.md
src/Cli/func/Directory.Version.props

n/a
Prep for release for version 4.1.2. No Host Version update.

Release prep: v4.1.2

---

src/Cli/func/Common/AppSettingsFile.cs
test/Cli/Func.UnitTests/ActionsTests/StartHostActionTests.cs

n/a
- `AppSettingsFile` deserializing itself in the ctor is not great. Updated to use a JObject instead to avoid this weird recurrsion.
- Update `CheckNonOptionalSettingsPrintsWarningForMissingSettings` paths

Fix more flakey tests :(

---

eng/ci/templates/steps/run-e2e-tests.yml
src/Cli/func/Common/FileSystemHelpers.cs
src/Cli/func/Helpers/DotnetHelpers.E2E.cs
src/Cli/func/Helpers/DotnetHelpers.cs
test/Cli/Func.E2ETests/.runsettings/new_and_init_tests/run_sequentially.runsettings
test/Cli/Func.E2ETests/.runsettings/start_tests/ci_pipeline/default.runsettings
test/Cli/Func.E2ETests/.runsettings/start_tests/ci_pipeline/dotnet_inproc.runsettings
test/Cli/Func.E2ETests/Azure.Functions.Cli.E2ETests.csproj
test/Cli/Func.E2ETests/BaseE2ETests.cs
test/Cli/Func.E2ETests/Commands/FuncInit/DotnetInitTests.cs
test/Cli/Func.E2ETests/Commands/FuncInit/DotnetIsolatedInitTests.cs
test/Cli/Func.E2ETests/Commands/FuncNew/DotnetInProcTests.cs
test/Cli/Func.E2ETests/Commands/FuncNew/TestsWithFixtures/DotnetIsolatedTests.cs
test/Cli/Func.E2ETests/Fixtures/DotnetIsolatedFunctionAppFixture.cs
test/Cli/Func.E2ETests/Traits/TestTraits.cs

Implement custom hives for e2e tests

Implement custom hives for e2e tests

---

release_notes.md
src/Cli/func/Common/Utilities.cs
src/Cli/func/Directory.Version.props

resolves #4613
Prep for preview release

Prepare for preview release with python linux-arm64 support

---

eng/scripts/generate-msi-files.ps1

related to #4627
Update MSI versioning to ensure it's a) valid and b) accounts for `-<suffix>`

Fix MSI versioning

---

release_notes.md

reset release notes

---

release_notes.md
src/Cli/func/Directory.Version.props

- Version v4.2.3.
- No host updates.
- No core tools feature changes.
- Only change is the change to list of assemblies being signed.

Release prep: v4.2.3

---

eng/build/Packages.props
release_notes.md

updating host version 4.1042.100

Updating host version 4.1042.100
